/* ===========================================================
   ENGLISH CONTENT — CoachTanguy (edited via dashboard.html)
   =========================================================== */
window.SITE_CONTENT = {
  "nav": {
    "accueil": "Home",
    "visio": "Video coaching",
    "suivi": "Online tracking",
    "calculateur": "Calculator",
    "faq": "FAQ",
    "contact": "Contact",
    "cta": "Book a call"
  },
  "calc": {
    "eyebrow": "Free tool",
    "title": "Food calculator",
    "subtitle": "Estimate your calorie needs and macro split in seconds, based on your profile and goals."
  },
  "home": {
    "hero": {
      "eyebrow": "Certified personal trainer",
      "titleHtml": "Fitness made easy,<br />anywhere, anytime.",
      "subtitle": "Video coaching and online tracking, tailored to your level, your goals and your schedule.",
      "ctaPrimary": "Video coaching",
      "ctaSecondary": "Online follow-up",
      "pill1": "✓ Video call",
      "pill2": "✓ Personalised plans",
      "pill3": "✓ No commitment"
    },
    "trust": {
      "v1": "500+",
      "l1": "hours of training",
      "v2": "100%",
      "l2": "personalised",
      "v3": "7/7",
      "l3": "support",
      "v4": "1st",
      "l4": "session free"
    },
    "services": {
      "eyebrow": "Services",
      "title": "Support at your own pace",
      "subtitle": "Two formulas designed to help you progress, wherever you are.",
      "c1Title": "Video coaching",
      "c1Text": "Enjoy professional remote support via video call, to stay motivated wherever you are.",
      "c1Link": "Discover the offer →",
      "c2Title": "Online tracking",
      "c2Text": "Get personalised tracking, training plans and advice through an app.",
      "c2Link": "Discover the offer →"
    },
    "process": {
      "eyebrow": "How it works",
      "title": "Whether with video coaching or online follow-up, progress in 3 simple steps",
      "s1Title": "Discovery call",
      "s1Text": "A first free call to understand your needs, your goals and try the method together.",
      "s2Title": "Tailored plan",
      "s2Text": "I build a programme adapted to your level, your schedule and your equipment.",
      "s3Title": "Tracking & results",
      "s3Text": "We move forward together: sessions, regular adjustments and motivation for lasting results."
    },
    "about": {
      "eyebrow": "About",
      "title": "Tanguy, your personal coach",
      "p1": "Holder of a Bachelor's degree in Sports Coaching (Bachelier en Coaching Sportif), I rely on solid knowledge of anatomy, physiology, nutrition and training science to guide you safely.",
      "p2": "I've worked with varied profiles, from children to seniors, and adapt each programme to your needs. My background: over 500 hours of placement, 2 years of experience as a personal coach and more than 10 years of personal strength training.",
      "s1v": "500+",
      "s1l": "placement hours",
      "s2v": "2 yrs",
      "s2l": "of coaching",
      "s3v": "10+ yrs",
      "s3l": "of practice",
      "cta": "Work with me"
    },
    "faq": {
      "eyebrow": "FAQ",
      "title": "Frequently asked questions",
      "q1": "Why offer session packs?",
      "a1": "Packs simplify payment and encourage commitment. Consistency is the key to results: committing to several sessions helps you stay regular and progress over time.",
      "q2": "How do I book a session?",
      "a2": "A calendar link is shared every two weeks via WhatsApp. You choose the slots that best fit your availability.",
      "q3": "Can I cancel or reschedule a session?",
      "a3": "Yes, you can cancel or reschedule a session as long as your pack is valid. Once the pack expires, unused sessions are lost.",
      "q4": "How long is a pack valid?",
      "a4": "4-session packs are valid for 5 weeks, and 8-session packs for 10 weeks, from the date of purchase.",
      "q5": "Which payment methods are accepted?",
      "a5": "Visa, Mastercard, PayPal, Klarna, Apple Pay, Google Pay and other payment methods are accepted securely via Stripe.",
      "q6": "What if I go on holiday?",
      "a6": "No problem: your pack is paused during your absence and resumes when you return.",
      "q7": "Can I pay in instalments?",
      "a7": "Yes, payment in instalments is possible with Klarna."
    },
    "cta": {
      "title": "Ready to get started?",
      "text": "Contact me to discuss your goals and find the formula that suits you. The first session is free.",
      "button": "Contact me"
    },
    "payments": {
      "title": "Secure payment via Stripe"
    }
  },
  "footer": {
    "tagline": "Fitness made easy, anywhere, anytime.",
    "areas": "Personal trainer in Rhode-Saint-Genèse, Uccle, Waterloo, Beersel, Linkebeek and Braine-l'Alleud — in person or by video.",
    "lVisio": "Video coaching",
    "lSuivi": "Online tracking",
    "lFaq": "FAQ",
    "lContact": "Contact",
    "lMentions": "Legal notice",
    "lCgv": "Terms of sale",
    "copyright": "© 2026 CoachTanguy. All rights reserved."
  },
  "contact": {
    "eyebrow": "Contact",
    "title": "Contact Tanguy",
    "subtitle": "A question? Ready to start? Drop me a message, I'll reply quickly.",
    "asideTitle": "A question?",
    "asideText": "The simplest and quickest way: a direct message on WhatsApp.",
    "waLabel": "WhatsApp",
    "waSub": "+32 472 76 16 39",
    "emailLabel": "Email",
    "emailSub": "tanguy_coaching@hotmail.com",
    "note": "✓ First trial session free",
    "formTitle": "Quick message",
    "fName": "Name",
    "phName": "Your name",
    "fEmail": "Email",
    "phEmail": "you@email.com",
    "fSubject": "Subject",
    "optVisio": "Video coaching",
    "optSuivi": "Online tracking",
    "optEssai": "Free trial session",
    "optAutre": "Other question",
    "fMessage": "Message",
    "phMessage": "Tell me about your goals...",
    "submit": "Send message",
    "consent": "By sending this form, you agree to be contacted by CoachTanguy."
  },
  "visio": {
    "heroEyebrow": "Video Coaching",
    "heroTitleHtml": "Flexible, interactive,<br />effective.",
    "heroSubtitle": "Enjoy one-to-one remote sports coaching sessions, accessible anywhere. Personalised coaching, real-time advice and tailored follow-up via video call.",
    "heroCta1": "Go straight to the packs",
    "heroCta2": "Free trial session",
    "f1Title": "Tailored coaching",
    "f1Text": "Sessions adapted to your pace, your goals and your space, wherever you are.",
    "f2Title": "Session packs",
    "f2Text": "Packs designed around your training frequency to ensure real consistency.",
    "f3Title": "Free trial session",
    "f3Text": "A first chat to discover your needs, try the method and set your goals together.",
    "packsEyebrow": "Packs",
    "packsTitle": "Choose the formula that suits you",
    "packsSubtitle": "Adapted and personalised · feedback after every session · rescheduling possible during holidays.",
    "p1Name": "Single session",
    "p1Meta": "Session of 30 to 40 min",
    "p1l1": "Adapted and personalised session",
    "p1l2": "Feedback after the session",
    "p1l3": "No commitment",
    "p1Note": "💳 Payment upon booking",
    "p1Btn": "Book",
    "p2Ribbon": "Most chosen",
    "p2Name": "Pack of 4 sessions",
    "p2PriceSub": "i.e. 35€ / session",
    "p2Meta": "Valid 5 weeks",
    "p2l1": "4 personalised sessions",
    "p2l2": "Feedback after each session",
    "p2l3": "Rescheduling possible during holidays",
    "p2l4": "Ideal 1 session / week",
    "p2Btn": "Choose",
    "p3Name": "Pack of 8 sessions",
    "p3PriceSub": "i.e. 30€ / session",
    "p3Meta": "Valid 10 weeks",
    "p3l1": "8 personalised sessions",
    "p3l2": "Feedback after each session",
    "p3l3": "Rescheduling possible during holidays",
    "p3l4": "Best price / session",
    "p3Btn": "Choose",
    "ctaTitle": "Ready to get started?",
    "ctaText": "Book your free trial session and let's get going together.",
    "ctaBtn": "Get in touch"
  },
  "suivi": {
    "heroEyebrow": "Online Tracking",
    "heroTitleHtml": "Remote sports<br />coaching.",
    "heroSubtitle": "Tracking at your own pace, 100% personalised, wherever you are via the FitPros app. Evolving programme, regular advice and tailored support to progress effectively.",
    "heroCta1": "Go straight to the plans",
    "heroCta2": "Ask a question",
    "appEyebrow": "FitPros",
    "appTitle": "Your tailored programme in your pocket.",
    "appText": "A simple space to track your progress and stay motivated every day.",
    "appB1Title": "A simple space to track your progress.",
    "appB1Text": "In the app, you easily find your ongoing workouts, your weekly progress and your next planned sessions. Everything is centralised so you keep a clear view of your tracking and stay consistent.",
    "appB2Title": "Step-by-step guided sessions.",
    "appB2Text": "Each session is clearly organised with the exercises, sets, reps, related instructions and demonstration videos. You can start your workout directly from the app and follow the programme at your own pace, fully independently.",
    "appT1": "Step-by-step guided sessions",
    "appT2": "Clear tracking of your progress",
    "appT3": "Regular advice and adjustments",
    "appT4": "Direct communication via WhatsApp",
    "appBtn": "See the plans",
    "suivisEyebrow": "Plans",
    "suivisTitle": "Expert tracking, 100% personalised",
    "suivisSubtitle": "Tailored programme, regular adjustments and human support.",
    "flowLabel": "then",
    "s1Ribbon": "To get started",
    "s1Name": "Initial support",
    "s1PriceSub": "for 8 weeks",
    "s1l1": "Personalised support for 8 weeks",
    "s1l2": "Tailored training programme adapted to your goals",
    "s1l3": "Access via the FitPros app",
    "s1l4": "Communication & tracking via WhatsApp",
    "s1l5": "Introductory video call (~30 min) free",
    "s1l6": "Programme available within 72h after the call",
    "s1l7": "Check-up every 2 weeks via a form",
    "s1l8": "Regular adjustments for optimal results",
    "s1l9": "Pause possible during holidays",
    "s1Btn": "Choose",
    "s2Name": "Monthly tracking",
    "s2PriceSub": "per month",
    "s2Meta": "Only after the initial support",
    "s2l1": "Tailored training programme",
    "s2l2": "Access via the FitPros app",
    "s2l3": "Communication & tracking via WhatsApp",
    "s2l4": "Check-up every 2 weeks",
    "s2l5": "Regular adjustments",
    "s2l6": "Pause possible during holidays",
    "s2Btn": "Choose",
    "ctaTitle": "Ready to progress?",
    "ctaText": "Book your free introductory call and let's build your programme.",
    "ctaBtn": "Get in touch"
  },
  "stripe": {
    "unite": "contact.html",
    "pack4": "https://buy.stripe.com/5kQ4gBdvB0Yz85A7Pa0RG0a",
    "pack8": "https://buy.stripe.com/8x2cN7fDJePpadI8Te0RG0b",
    "initial": "https://buy.stripe.com/8x214p8bh22D0D84CY0RG08",
    "mensuel": "https://buy.stripe.com/dRm8wR63922DdpUfhC0RG09"
  },
  "meta": {
    "index": {
      "title": "Personal trainer in Rhode-Saint-Genèse & Brabant — CoachTanguy",
      "desc": "Personal trainer in Rhode-Saint-Genèse: at-home coaching, video sessions and online follow-up. Also in Waterloo, Beersel, Linkebeek and Braine-l'Alleud. 1st session free."
    },
    "visio": {
      "title": "Video Coaching — CoachTanguy",
      "desc": "One-on-one online sports coaching by video call. Flexible, interactive and effective. First trial session free."
    },
    "suivi": {
      "title": "Online Follow-up — CoachTanguy",
      "desc": "Fully personalised training follow-up via the FitPros app: evolving program, regular advice and tailored guidance to progress efficiently."
    },
    "contact": {
      "title": "Contact — CoachTanguy",
      "desc": "A question? Contact CoachTanguy via WhatsApp or message. First trial session free."
    },
    "calc": {
      "title": "Nutrition Calculator — CoachTanguy",
      "desc": "Free nutrition calculator: estimate your calorie needs and macro split (protein, carbs, fat) based on your profile and goals."
    }
  },
  "local": {
    "rhode": {
      "metaTitle": "Personal trainer in Rhode-Saint-Genèse | at home & video — CoachTanguy",
      "metaDesc": "Personal trainer in Rhode-Saint-Genèse: sessions at home or by video, tailored programme and nutrition. Qualified coach, first trial session free.",
      "heroEyebrow": "Personal training · Rhode-Saint-Genèse",
      "h1": "Personal trainer in Rhode-Saint-Genèse",
      "heroLead": "Based in Rhode-Saint-Genèse, I offer tailored personal training directly at your home or by video call. From the centre to the areas near the Sonian Forest, I adapt to your level, your goals and your schedule — beginner or experienced.",
      "btnEssai": "Free trial session",
      "btnVisio": "See video coaching",
      "secEyebrow": "In Rhode-Saint-Genèse and nearby",
      "h2": "Your personal trainer at home and by video in Rhode-Saint-Genèse",
      "secIntro": "No gym or long trips needed: I come to your home, or we train by video with a programme between sessions. Ideal if you're short on time or prefer a private, personalised setting.",
      "f1h": "At home in Rhode-Saint-Genèse",
      "f1p": "I come to you in Rhode-Saint-Genèse with the equipment needed. You train in a familiar setting, at a time that suits you.",
      "f2h": "Coaching by video",
      "f2p": "From Rhode-Saint-Genèse or on the move, follow your sessions by video call, with an updated programme and real-time corrections.",
      "f3h": "Tailored programme & nutrition",
      "f3p": "A plan adapted to your level and goals, with simple, concrete nutrition guidelines — no extreme diet.",
      "ctaH2": "Ready to (re)start training in Rhode-Saint-Genèse?",
      "ctaP": "First trial session free, no commitment. At home or by video, we start whenever you want.",
      "btnContact": "Contact me"
    },
    "uccle": {
      "metaTitle": "Personal trainer in Uccle | at home & video — CoachTanguy",
      "metaDesc": "Personal trainer in Uccle: sessions at home or by video, tailored programme and nutrition. Qualified coach, first trial session free.",
      "heroEyebrow": "Personal training · Uccle",
      "h1": "Personal trainer in Uccle",
      "heroLead": "Just north of Rhode-Saint-Genèse, I support the residents of Uccle with personalised training, at home or by video call. From Fort-Jaco to Vivier d'Oie, I adapt to your level, your goals and your schedule.",
      "btnEssai": "Free trial session",
      "btnVisio": "See video coaching",
      "secEyebrow": "In Uccle and nearby",
      "h2": "Your personal trainer at home and by video in Uccle",
      "secIntro": "No crowded gym needed: I come to your home, or we train by video with a programme between sessions. Convenient for busy schedules and Uccle's residential neighbourhoods.",
      "f1h": "At home in Uccle",
      "f1p": "I come to you in Uccle with the equipment needed. You train in a familiar setting, at a time that suits you.",
      "f2h": "Coaching by video",
      "f2p": "From Uccle or on the move, follow your sessions by video call, with an updated programme and real-time corrections.",
      "f3h": "Tailored programme & nutrition",
      "f3p": "A plan adapted to your level and goals, with simple, concrete nutrition guidelines — no extreme diet.",
      "ctaH2": "Ready to (re)start training in Uccle?",
      "ctaP": "First trial session free, no commitment. At home or by video, we start whenever you want.",
      "btnContact": "Contact me"
    },
    "waterloo": {
      "metaTitle": "Personal trainer in Waterloo | at home & video — CoachTanguy",
      "metaDesc": "Personal trainer in Waterloo: tailored coaching at home or by video — weight loss, fitness, muscle gain. First trial session free.",
      "heroEyebrow": "Personal training · Waterloo",
      "h1": "Personal trainer in Waterloo",
      "heroLead": "A few minutes from Rhode-Saint-Genèse, I support the people of Waterloo with personalised training, at home or by video. Weight loss, getting fit, muscle gain or physical preparation: together we build a realistic, progressive programme.",
      "btnEssai": "Free trial session",
      "btnVisio": "See video coaching",
      "secEyebrow": "In Waterloo and nearby",
      "h2": "Tailored personal training in Waterloo",
      "secIntro": "Whether you're a beginner or a regular, each session is adapted to how you feel that day. Between appointments, you keep a clear programme and advice to progress day to day, at your own pace.",
      "f1h": "At home in Waterloo",
      "f1p": "I come to you in Waterloo with the equipment needed. You train in a familiar setting, at a time that suits you.",
      "f2h": "Coaching by video",
      "f2p": "From Waterloo or on the move, follow your sessions by video call, with an updated programme and real-time corrections.",
      "f3h": "Tailored programme & nutrition",
      "f3p": "A plan adapted to your level and goals, with simple, concrete nutrition guidelines — no extreme diet.",
      "ctaH2": "Ready to (re)start training in Waterloo?",
      "ctaP": "First trial session free, no commitment. At home or by video, we start whenever you want.",
      "btnContact": "Contact me"
    },
    "beersel": {
      "metaTitle": "Personal trainer in Beersel | at home & video — CoachTanguy",
      "metaDesc": "Personal trainer in Beersel (Alsemberg, Huizingen, Lot): sessions at home or by video, tailored programme and nutrition. First trial session free.",
      "heroEyebrow": "Personal training · Beersel",
      "h1": "Personal trainer in Beersel",
      "heroLead": "Personalised training in Beersel and its villages (Alsemberg, Huizingen, Lot), at home or by video call. Professional, progressive support to reach your goals, without the hassle of the gym.",
      "btnEssai": "Free trial session",
      "btnVisio": "See video coaching",
      "secEyebrow": "In Beersel and nearby",
      "h2": "Guided training, close to home in Beersel",
      "secIntro": "Home coaching saves you time and keeps motivation high. Video lets you keep the rhythm even on busy weeks or away — it's consistency that delivers results.",
      "f1h": "At home in Beersel",
      "f1p": "I come to you in Beersel with the equipment needed. You train in a familiar setting, at a time that suits you.",
      "f2h": "Coaching by video",
      "f2p": "From Beersel or on the move, follow your sessions by video call, with an updated programme and real-time corrections.",
      "f3h": "Tailored programme & nutrition",
      "f3p": "A plan adapted to your level and goals, with simple, concrete nutrition guidelines — no extreme diet.",
      "ctaH2": "Ready to (re)start training in Beersel?",
      "ctaP": "First trial session free, no commitment. At home or by video, we start whenever you want.",
      "btnContact": "Contact me"
    },
    "linkebeek": {
      "metaTitle": "Personal trainer in Linkebeek & Holleken | at home & video — CoachTanguy",
      "metaDesc": "Personal trainer in Linkebeek and Holleken: coaching at home or by video, tailored programme, nutrition advice. Qualified coach, first trial session free.",
      "heroEyebrow": "Personal training · Linkebeek",
      "h1": "Personal trainer in Linkebeek",
      "heroLead": "Personal trainer for the people of Linkebeek and Holleken, right next to Rhode-Saint-Genèse. Sessions at home or by video, tailored programme, nutrition advice and regular follow-up for lasting results.",
      "btnEssai": "Free trial session",
      "btnVisio": "See video coaching",
      "secEyebrow": "In Linkebeek and nearby",
      "h2": "Coaching close to you in Linkebeek",
      "secIntro": "Thanks to the proximity to Rhode-Saint-Genèse, home sessions are easy to arrange. Video stays available so you never break the consistency — the real key to long-term progress.",
      "f1h": "At home in Linkebeek",
      "f1p": "I come to you in Linkebeek with the equipment needed. You train in a familiar setting, at a time that suits you.",
      "f2h": "Coaching by video",
      "f2p": "From Linkebeek or on the move, follow your sessions by video call, with an updated programme and real-time corrections.",
      "f3h": "Tailored programme & nutrition",
      "f3p": "A plan adapted to your level and goals, with simple, concrete nutrition guidelines — no extreme diet.",
      "ctaH2": "Ready to (re)start training in Linkebeek?",
      "ctaP": "First trial session free, no commitment. At home or by video, we start whenever you want.",
      "btnContact": "Contact me"
    },
    "braine": {
      "metaTitle": "Personal trainer in Braine-l'Alleud | at home & video — CoachTanguy",
      "metaDesc": "Personal trainer in Braine-l'Alleud: sessions at home or by video, led by a qualified coach. Fitness, physical preparation. First trial session free.",
      "heroEyebrow": "Personal training · Braine-l'Alleud",
      "h1": "Personal trainer in Braine-l'Alleud",
      "heroLead": "Personal training in Braine-l'Alleud: sessions led by a qualified coach, at home or by video call. From simple fitness to physical preparation, I guide you step by step, safely.",
      "btnEssai": "Free trial session",
      "btnVisio": "See video coaching",
      "secEyebrow": "In Braine-l'Alleud and nearby",
      "h2": "Ease back into training in Braine-l'Alleud",
      "secIntro": "We move forward step by step, with realistic goals and regular follow-up. The idea isn't to overhaul everything at once, but to build habits that last.",
      "f1h": "At home in Braine-l'Alleud",
      "f1p": "I come to you in Braine-l'Alleud with the equipment needed. You train in a familiar setting, at a time that suits you.",
      "f2h": "Coaching by video",
      "f2p": "From Braine-l'Alleud or on the move, follow your sessions by video call, with an updated programme and real-time corrections.",
      "f3h": "Tailored programme & nutrition",
      "f3p": "A plan adapted to your level and goals, with simple, concrete nutrition guidelines — no extreme diet.",
      "ctaH2": "Ready to (re)start training in Braine-l'Alleud?",
      "ctaP": "First trial session free, no commitment. At home or by video, we start whenever you want.",
      "btnContact": "Contact me"
    }
  }
};
(window.SITE_CONTENT_ALL = window.SITE_CONTENT_ALL || {}).en = window.SITE_CONTENT;
