/* ===========================================================
   ENGLISH CONTENT — CoachTanguy (edited via dashboard.html)
   =========================================================== */
window.SITE_CONTENT = {
  "nav": {
    "suivis": "Services",
    "avis": "Reviews",
    "accueil": "Home",
    "calculateur": "Calculator",
    "faq": "FAQ",
    "contact": "Contact",
    "cta": "Book a call",
    "collab": "Collaboration"
  },
  "calc": {
    "eyebrow": "Free tool",
    "title": "Food calculator",
    "subtitle": "Estimate your calorie needs and macro split in seconds, based on your profile and goals."
  },
  "home": {
    "hero": {
      "eyebrow": "Certified personal trainer",
      "titleHtml": "Fitness made easy,<br />anywhere, anytime.",
      "subtitle": "Video coaching and online tracking, tailored to your level, your goals and your schedule.",
      "ctaPrimary": "Video coaching",
      "ctaSecondary": "Online follow-up",
      "pill1": "✓ Video call",
      "pill2": "✓ Personalised plans",
      "pill3": "✓ No commitment"
    },
    "trust": {
      "v1": "500+",
      "l1": "hours of training",
      "v2": "100%",
      "l2": "personalised",
      "v3": "7/7",
      "l3": "support",
      "v4": "1st",
      "l4": "session free"
    },
    "services": {
      "eyebrow": "Services",
      "title": "Support at your own pace",
      "subtitle": "Two formulas designed to help you progress, wherever you are.",
      "c1Title": "Video coaching",
      "c1Text": "Enjoy professional remote support via video call, to stay motivated wherever you are.",
      "c1Link": "Discover the offer",
      "c2Title": "Online tracking",
      "c2Text": "Get personalised tracking, training plans and advice through an app.",
      "c2Link": "Discover the offer"
    },
    "process": {
      "eyebrow": "How it works",
      "title": "Whether with video coaching or online follow-up, progress in 3 simple steps",
      "s1Title": "Discovery call",
      "s1Text": "A first free call to understand your needs, your goals and try the method together.",
      "s2Title": "Tailored plan",
      "s2Text": "I build a programme adapted to your level, your schedule and your equipment.",
      "s3Title": "Tracking & results",
      "s3Text": "We move forward together: sessions, regular adjustments and motivation for lasting results."
    },
    "about": {
      "eyebrow": "About",
      "title": "Tanguy, your personal coach",
      "p1": "Holder of a Bachelor's degree in Sports Coaching (Bachelier en Coaching Sportif), I rely on solid knowledge of anatomy, physiology, nutrition and training science to guide you safely.",
      "p2": "I've worked with varied profiles, from children to seniors, and adapt each programme to your needs. My background: over 500 hours of placement, 2 years of experience as a personal coach and more than 10 years of personal strength training.",
      "s1v": "500+",
      "s1l": "placement hours",
      "s2v": "2 yrs",
      "s2l": "of coaching",
      "s3v": "10+ yrs",
      "s3l": "of practice",
      "cta": "Work with me"
    },
    "faq": {
      "eyebrow": "FAQ",
      "title": "Frequently asked questions.",
      "q1": "Why offer session packs?",
      "a1": "Packs make things simpler with a single payment while encouraging commitment over time. They also help you stay consistent and motivated in your sessions, which is essential to progress and achieve concrete results.",
      "q2": "How do I book a session?",
      "a2": "Every 2 weeks, you receive a link to my electronic calendar via WhatsApp to book your session. Bookings are made every 2 weeks to guarantee more flexibility and adapt to your schedule.",
      "q3": "Can I cancel or reschedule a session?",
      "a3": "No worries: you can cancel a session and reschedule it to another date as long as your pack is still valid. Once the pack's end date has passed, any unused session is lost.",
      "q4": "How long is a pack valid?",
      "a4": "4-session packs are valid for 5 weeks and 8-session packs for 10 weeks from the payment date. This duration ensures regular practice and optimal results. After these deadlines, unused sessions are lost. Rescheduling a session does not extend the pack's validity period.",
      "q5": "Which payment methods are accepted?",
      "a5": "Payments can be made with Visa, Mastercard, Revolut Pay, PayPal, Klarna, Bancontact, Apple Pay or Google Pay. Payment is processed securely via Stripe.",
      "q6": "What if I go on holiday?",
      "a6": "No problem: your pack or your follow-up is simply paused and resumes when you return.",
      "q7": "Can I pay in instalments?",
      "a7": "Yes, payment via Klarna is available. It can allow you to pay for your pack within 30 days, depending on your eligibility. Payment remains secure and is processed directly via Stripe."
    },
    "cta": {
      "title": "Ready to get started?",
      "text": "Contact me to discuss your goals and find the formula that suits you. The first session is free.",
      "button": "Contact me"
    },
    "payments": {
      "title": "Secure payment via Stripe"
    },
    "calcTeaser": {
      "eyebrow": "Free tool",
      "title": "Calculate your calorie needs in 2 minutes",
      "text": "Basal metabolic rate, target calories, macro split and practical guidelines to build your meals: my free nutrition calculator gives you a clear starting point, no sign-up needed.",
      "chip1": "✓ Calories & macros",
      "chip3": "✓ Meal ideas",
      "button": "Try the calculator"
    }
  },
  "avis": {
    "eyebrow": "Google reviews",
    "title": "They trust me.",
    "score": "5,0",
    "count": "16 Google reviews",
    "cta1": "Leave a review",
    "cta2": "See all reviews",
    "r1Name": "Laurence Bioul",
    "r1Text": "Super coach ! Il est très à l'écoute des besoins individuels, il adapte la séance en fonction de ma condition physique et des bobos du moment (migraines, douleur aux genoux etc.). Je recommande vivement !",
    "r2Name": "Sebastien Hayot",
    "r2Text": "Tanguy nous coache à domicile depuis près de deux ans, et nous sommes entièrement satisfaits de son accompagnement. Son approche est à la fois très professionnelle, bienveillante et parfaitement adaptée à nos besoins. Toujours à l'écoute, il sait motiver sans jamais mettre de pression, tout en restant humain et attentif à nos objectifs. Nous le recommandons sans la moindre hésitation.",
    "r3Name": "Didem Sengun",
    "r3Text": "Tanguy est très sympa et est un super coach qui sait me motiver ! Il a le peps et me donne envie de faire ma séance chaque séance.",
    "r4Name": "Maxime Lebg",
    "r4Text": "Super accompagnement ! J'ai apprécié le fait d'avoir un programme clair avec les exercices, les séries, les répétitions et les vidéos. On sait exactement quoi faire à chaque séance. Tanguy est sérieux, à l'écoute et très professionnel.",
    "r5Name": "Rosalie de Crombrugghe",
    "r5Text": "Tanguy m'a coachée à domicile pendant 1,5 an jusqu'à mes 6 mois de grossesse. J'adore son professionnalisme, ses coachings toujours différents, son écoute. De plus, il s'assure toujours que les mouvements soient bien faits. J'ai hâte de reprendre les coachings avec Tanguy !",
    "r6Name": "Tanguy R",
    "r6Text": "Je recommande vraiment le suivi en ligne avec Tanguy. C'est pratique, flexible et très bien organisé. Les exercices sont bien choisis et les consignes sont claires, ce qui permet de progresser sans devoir réfléchir à quoi faire.",
    "r7Name": "Caro Delvaux",
    "r7Text": "Super coach à domicile ! À l'écoute, professionnel, ponctuel, passionné. Adapte ses séances à l'évolution.",
    "r8Name": "Maggss115",
    "r8Text": "Tanguy est un coach très attentif et très à l'écoute. Il adapte le contenu des séances selon les besoins spécifiques du client et son niveau de fitness et le résultat est efficace, agréable et rapidement visible. Je le recommande vivement à quiconque veut se reprendre en main ou simplement rester en forme physique optimale.",
    "r9Name": "anne reynens",
    "r9Text": "Voilà 18 mois que Tanguy me suit. Il travaille mon physique et mon mental. Je le recommande.",
    "r10Name": "Laurence Henin",
    "r10Text": "Je recommande vivement le coach Tanguy. Jeune, dynamique et très professionnel, il sait parfaitement s'adapter aux besoins et aux objectifs de chacun. Son accompagnement est personnalisé, motivant et toujours réalisé avec bienveillance.",
    "r11Name": "Julien Rizk",
    "r11Text": "Très bon suivi en ligne. Le programme est clair, bien structuré et facile à suivre même quand on n'a pas énormément de temps. Tanguy est disponible, répond rapidement aux questions et adapte si besoin. Je recommande sans hésiter.",
    "r12Name": "Sonia B-Lila",
    "r12Text": "Je ne peux que conseiller Tanguy comme coach. Professionnel, à l'écoute, il sait adapter les entraînements en fonction des limites, points faibles et forts de chacun. Motivant, on se sent bien après ses séances malgré les challenges !",
    "r13Name": "Romain V.",
    "r13Text": "Très satisfait du suivi. Le programme était adapté à mes objectifs et à mon emploi du temps. J'ai surtout aimé le côté progressif, on ne se sent pas perdu et on voit qu'il y a une vraie logique derrière les séances.",
    "r14Name": "Estelle Bruyninckx",
    "r14Text": "Très satisfaite de mon suivi en ligne avec Tanguy. Le programme est clair, bien adapté à mon niveau et facile à suivre via l'application. L'accompagnement sur WhatsApp est un vrai plus : dès que j'ai une question sur un exercice, Tanguy me répond assez vite. Je recommande !"
  },
  "footer": {
    "tagline": "Fitness made easy, anywhere, anytime.",
    "areas": "Personal trainer in Rhode-Saint-Genèse, Uccle, Waterloo, Beersel, Linkebeek and Braine-l'Alleud, in person or by video.",
    "lVisio": "Video coaching",
    "lSuivi": "Online tracking",
    "lFaq": "FAQ",
    "lContact": "Contact",
    "lMentions": "Legal notice",
    "lCgv": "Terms of sale",
    "copyright": "© 2026 CoachTanguy. All rights reserved.",
    "lPrivacy": "Privacy",
    "lCookies": "Cookies",
    "lCollab": "Partner physio"
  },
  "contact": {
    "eyebrow": "Contact",
    "title": "Contact Tanguy",
    "subtitle": "A question? Ready to start? Drop me a message, I'll reply quickly.",
    "asideTitle": "A question?",
    "asideText": "The simplest and quickest way: a direct message on WhatsApp.",
    "waLabel": "WhatsApp",
    "waSub": "+32 472 76 16 39",
    "emailLabel": "Email",
    "emailSub": "contact@coachtanguy.com",
    "note": "✓ First trial session free",
    "formTitle": "Quick message",
    "fName": "Name",
    "phName": "Your name",
    "fEmail": "Email",
    "phEmail": "you@email.com",
    "fSubject": "Subject",
    "optVisio": "Video coaching",
    "optSuivi": "Online tracking",
    "optEssai": "Free trial session",
    "optAutre": "Other question",
    "fMessage": "Message",
    "phMessage": "Tell me about your goals...",
    "submit": "Send message",
    "consent": "Once you send this message, Tanguy will get back to you within the day.",
    "privacyText": "Your details (name, e-mail, message) are used solely to handle your request.",
    "privacyLink": "Privacy policy"
  },
  "visio": {
    "heroEyebrow": "Video Coaching",
    "heroTitleHtml": "Flexible, interactive,<br />effective.",
    "heroSubtitle": "Enjoy one-to-one remote sports coaching sessions, accessible anywhere. Personalised coaching, real-time advice and tailored follow-up via video call.",
    "heroCta1": "Go straight to the packs",
    "heroCta2": "Free trial session",
    "f1Title": "Tailored coaching",
    "f1Text": "Sessions adapted to your pace, your goals and your space, wherever you are.",
    "f2Title": "Session packs",
    "f2Text": "Packs designed around your training frequency to ensure real consistency.",
    "f3Title": "Free trial session",
    "f3Text": "A first chat to discover your needs, try the method and set your goals together.",
    "packsEyebrow": "Packs",
    "packsTitle": "Choose the formula that suits you",
    "packsSubtitle": "Adapted and personalised · feedback after every session · rescheduling possible during holidays.",
    "p1Name": "Single session",
    "p1Price": "40€",
    "p1Meta": "Session of 30 to 40 min",
    "p1l1": "Adapted and personalised session",
    "p1l2": "Feedback after the session",
    "p1l3": "No commitment",
    "p1Note": "💳 Payment upon booking",
    "p1lCalc": "Personalised nutrition calculator",
    "p1Btn": "Book",
    "p2Ribbon": "Most chosen",
    "p2Name": "Pack of 4 sessions",
    "p2Price": "140€",
    "p2PriceSub": "i.e. 35€ / session",
    "p2Meta": "Valid 5 weeks",
    "p2l1": "4 personalised sessions",
    "p2l2": "Feedback after each session",
    "p2l3": "Rescheduling possible during holidays",
    "p2l4": "Ideal 1 session / week",
    "p2lCalc": "Personalised nutrition calculator",
    "p2Btn": "Choose",
    "p3Name": "Pack of 8 sessions",
    "p3Price": "240€",
    "p3PriceSub": "i.e. 30€ / session",
    "p3Meta": "Valid 10 weeks",
    "p3l1": "8 personalised sessions",
    "p3l2": "Feedback after each session",
    "p3l3": "Rescheduling possible during holidays",
    "p3l4": "Best price / session",
    "p3lCalc": "Personalised nutrition calculator",
    "p3Btn": "Choose",
    "ctaTitle": "Ready to get started?",
    "ctaText": "Book your free trial session and let's get going together.",
    "ctaBtn": "Get in touch"
  },
  "suivi": {
    "heroEyebrow": "Online Tracking",
    "heroTitleHtml": "Remote sports<br />coaching.",
    "heroSubtitle": "Tracking at your own pace, 100% personalised, wherever you are via the FitPros app. Evolving programme, regular advice and tailored support to progress effectively.",
    "heroCta1": "Go straight to the plans",
    "heroCta2": "Ask a question",
    "appEyebrow": "FitPros",
    "appTitle": "Your tailored programme in your pocket.",
    "appText": "A simple space to track your progress and stay motivated every day.",
    "appB1Title": "A simple space to track your progress.",
    "appB1Text": "In the app, you easily find your ongoing workouts, your weekly progress and your next planned sessions. Everything is centralised so you keep a clear view of your tracking and stay consistent.",
    "appB2Title": "Step-by-step guided sessions.",
    "appB2Text": "Each session is clearly organised with the exercises, sets, reps, related instructions and demonstration videos. You can start your workout directly from the app and follow the programme at your own pace, fully independently.",
    "appT1": "Step-by-step guided sessions",
    "appT2": "Clear tracking of your progress",
    "appT3": "Regular advice and adjustments",
    "appT4": "Direct communication via WhatsApp",
    "appBtn": "See the plans",
    "suivisEyebrow": "Plans",
    "suivisTitle": "Expert tracking, 100% personalised",
    "suivisSubtitle": "Tailored programme, regular adjustments and human support.",
    "flowLabel": "then",
    "s1Ribbon": "To get started",
    "s1Name": "Initial support",
    "s1Price": "299€",
    "s1PriceSub": "for 8 weeks",
    "s1l1": "Personalised support for 8 weeks",
    "s1l2": "Tailored training programme adapted to your goals",
    "s1l3": "Access via the FitPros app",
    "s1l4": "Communication & tracking via WhatsApp",
    "s1l5": "Introductory video call (~30 min) free",
    "s1l6": "Programme available within 72h after the call",
    "s1l8": "Regular adjustments for optimal results",
    "s1l9": "Pause possible during holidays",
    "s1lCalc": "Personalised nutrition calculator",
    "s1Btn": "Choose",
    "s2Name": "Monthly tracking",
    "s2Price": "139€",
    "s2PriceSub": "per month",
    "s2Meta": "Only after the initial support",
    "s2l1": "Tailored training programme",
    "s2l2": "Access via the FitPros app",
    "s2l3": "Communication & tracking via WhatsApp",
    "s2l5": "Regular adjustments",
    "s2l6": "Pause possible during holidays",
    "s2lCalc": "Personalised nutrition calculator",
    "s2Btn": "Choose",
    "ctaTitle": "Ready to progress?",
    "ctaText": "Book your free introductory call and let's build your programme.",
    "ctaBtn": "Get in touch"
  },
  "stripe": {
    "unite": "contact.html",
    "pack4": "https://buy.stripe.com/5kQ4gBdvB0Yz85A7Pa0RG0a",
    "pack8": "https://buy.stripe.com/8x2cN7fDJePpadI8Te0RG0b",
    "initial": "https://buy.stripe.com/6oU3cx9fl6iTadIb1m0RG0c",
    "mensuel": "https://buy.stripe.com/6oU14p77d4aLadIglG0RG0g"
  },
  "meta": {
    "index": {
      "title": "Personal trainer in Rhode-Saint-Genèse & Brabant — CoachTanguy",
      "desc": "Personal trainer in Rhode-Saint-Genèse: at-home coaching, video sessions and online follow-up. Also in Waterloo, Beersel, Linkebeek and Braine-l'Alleud. 1st session free."
    },
    "visio": {
      "title": "Video Coaching — CoachTanguy",
      "desc": "One-on-one online sports coaching by video call. Flexible, interactive and effective. First trial session free."
    },
    "suivi": {
      "title": "Online Follow-up — CoachTanguy",
      "desc": "Fully personalised training follow-up via the FitPros app: evolving program, regular advice and tailored guidance to progress efficiently."
    },
    "contact": {
      "title": "Contact — CoachTanguy",
      "desc": "A question? Contact CoachTanguy via WhatsApp or message. First trial session free."
    },
    "calc": {
      "title": "Nutrition Calculator — CoachTanguy",
      "desc": "Free nutrition calculator: estimate your calorie needs and macro split (protein, carbs, fat) based on your profile and goals."
    }
  },
  "local": {
    "rhode": {
      "metaTitle": "Personal trainer in Rhode-Saint-Genèse | at home & video — CoachTanguy",
      "metaDesc": "Personal trainer in Rhode-Saint-Genèse: sessions at home or by video, tailored programme and nutrition. Qualified coach, first trial session free.",
      "heroEyebrow": "Personal training · Rhode-Saint-Genèse",
      "h1": "Personal trainer in Rhode-Saint-Genèse",
      "heroLead": "Based in Rhode-Saint-Genèse, I offer tailored personal training directly at your home or by video call. From the centre to the areas near the Sonian Forest, I adapt to your level, your goals and your schedule, beginner or experienced.",
      "btnEssai": "Free trial session",
      "btnVisio": "See video coaching",
      "secEyebrow": "In Rhode-Saint-Genèse and nearby",
      "h2": "Your personal trainer at home and by video in Rhode-Saint-Genèse",
      "secIntro": "No gym or long trips needed: I come to your home, or we train by video with a programme between sessions. Ideal if you're short on time or prefer a private, personalised setting.",
      "f1h": "At home in Rhode-Saint-Genèse",
      "f1p": "I come to you in Rhode-Saint-Genèse with the equipment needed. You train in a familiar setting, at a time that suits you.",
      "f2h": "Coaching by video",
      "f2p": "From Rhode-Saint-Genèse or on the move, follow your sessions by video call, with an updated programme and real-time corrections.",
      "f3h": "Tailored programme & nutrition",
      "f3p": "A plan adapted to your level and goals, with simple, concrete nutrition guidelines, no extreme diet.",
      "ctaH2": "Ready to (re)start training in Rhode-Saint-Genèse?",
      "ctaP": "First trial session free, no commitment. At home or by video, we start whenever you want.",
      "btnContact": "Contact me"
    },
    "uccle": {
      "metaTitle": "Personal trainer in Uccle | at home & video — CoachTanguy",
      "metaDesc": "Personal trainer in Uccle: sessions at home or by video, tailored programme and nutrition. Qualified coach, first trial session free.",
      "heroEyebrow": "Personal training · Uccle",
      "h1": "Personal trainer in Uccle",
      "heroLead": "Just north of Rhode-Saint-Genèse, I support the residents of Uccle with personalised training, at home or by video call. From Fort-Jaco to Vivier d'Oie, I adapt to your level, your goals and your schedule.",
      "btnEssai": "Free trial session",
      "btnVisio": "See video coaching",
      "secEyebrow": "In Uccle and nearby",
      "h2": "Your personal trainer at home and by video in Uccle",
      "secIntro": "No crowded gym needed: I come to your home, or we train by video with a programme between sessions. Convenient for busy schedules and Uccle's residential neighbourhoods.",
      "f1h": "At home in Uccle",
      "f1p": "I come to you in Uccle with the equipment needed. You train in a familiar setting, at a time that suits you.",
      "f2h": "Coaching by video",
      "f2p": "From Uccle or on the move, follow your sessions by video call, with an updated programme and real-time corrections.",
      "f3h": "Tailored programme & nutrition",
      "f3p": "A plan adapted to your level and goals, with simple, concrete nutrition guidelines, no extreme diet.",
      "ctaH2": "Ready to (re)start training in Uccle?",
      "ctaP": "First trial session free, no commitment. At home or by video, we start whenever you want.",
      "btnContact": "Contact me"
    },
    "waterloo": {
      "metaTitle": "Personal trainer in Waterloo | at home & video — CoachTanguy",
      "metaDesc": "Personal trainer in Waterloo: tailored coaching at home or by video — weight loss, fitness, muscle gain. First trial session free.",
      "heroEyebrow": "Personal training · Waterloo",
      "h1": "Personal trainer in Waterloo",
      "heroLead": "A few minutes from Rhode-Saint-Genèse, I support the people of Waterloo with personalised training, at home or by video. Weight loss, getting fit, muscle gain or physical preparation: together we build a realistic, progressive programme.",
      "btnEssai": "Free trial session",
      "btnVisio": "See video coaching",
      "secEyebrow": "In Waterloo and nearby",
      "h2": "Tailored personal training in Waterloo",
      "secIntro": "Whether you're a beginner or a regular, each session is adapted to how you feel that day. Between appointments, you keep a clear programme and advice to progress day to day, at your own pace.",
      "f1h": "At home in Waterloo",
      "f1p": "I come to you in Waterloo with the equipment needed. You train in a familiar setting, at a time that suits you.",
      "f2h": "Coaching by video",
      "f2p": "From Waterloo or on the move, follow your sessions by video call, with an updated programme and real-time corrections.",
      "f3h": "Tailored programme & nutrition",
      "f3p": "A plan adapted to your level and goals, with simple, concrete nutrition guidelines, no extreme diet.",
      "ctaH2": "Ready to (re)start training in Waterloo?",
      "ctaP": "First trial session free, no commitment. At home or by video, we start whenever you want.",
      "btnContact": "Contact me"
    },
    "beersel": {
      "metaTitle": "Personal trainer in Beersel | at home & video — CoachTanguy",
      "metaDesc": "Personal trainer in Beersel (Alsemberg, Huizingen, Lot): sessions at home or by video, tailored programme and nutrition. First trial session free.",
      "heroEyebrow": "Personal training · Beersel",
      "h1": "Personal trainer in Beersel",
      "heroLead": "Personalised training in Beersel and its villages (Alsemberg, Huizingen, Lot), at home or by video call. Professional, progressive support to reach your goals, without the hassle of the gym.",
      "btnEssai": "Free trial session",
      "btnVisio": "See video coaching",
      "secEyebrow": "In Beersel and nearby",
      "h2": "Guided training, close to home in Beersel",
      "secIntro": "Home coaching saves you time and keeps motivation high. Video lets you keep the rhythm even on busy weeks or away, it's consistency that delivers results.",
      "f1h": "At home in Beersel",
      "f1p": "I come to you in Beersel with the equipment needed. You train in a familiar setting, at a time that suits you.",
      "f2h": "Coaching by video",
      "f2p": "From Beersel or on the move, follow your sessions by video call, with an updated programme and real-time corrections.",
      "f3h": "Tailored programme & nutrition",
      "f3p": "A plan adapted to your level and goals, with simple, concrete nutrition guidelines, no extreme diet.",
      "ctaH2": "Ready to (re)start training in Beersel?",
      "ctaP": "First trial session free, no commitment. At home or by video, we start whenever you want.",
      "btnContact": "Contact me"
    },
    "linkebeek": {
      "metaTitle": "Personal trainer in Linkebeek & Holleken | at home & video — CoachTanguy",
      "metaDesc": "Personal trainer in Linkebeek and Holleken: coaching at home or by video, tailored programme, nutrition advice. Qualified coach, first trial session free.",
      "heroEyebrow": "Personal training · Linkebeek",
      "h1": "Personal trainer in Linkebeek",
      "heroLead": "Personal trainer for the people of Linkebeek and Holleken, right next to Rhode-Saint-Genèse. Sessions at home or by video, tailored programme, nutrition advice and regular follow-up for lasting results.",
      "btnEssai": "Free trial session",
      "btnVisio": "See video coaching",
      "secEyebrow": "In Linkebeek and nearby",
      "h2": "Coaching close to you in Linkebeek",
      "secIntro": "Thanks to the proximity to Rhode-Saint-Genèse, home sessions are easy to arrange. Video stays available so you never break the consistency, the real key to long-term progress.",
      "f1h": "At home in Linkebeek",
      "f1p": "I come to you in Linkebeek with the equipment needed. You train in a familiar setting, at a time that suits you.",
      "f2h": "Coaching by video",
      "f2p": "From Linkebeek or on the move, follow your sessions by video call, with an updated programme and real-time corrections.",
      "f3h": "Tailored programme & nutrition",
      "f3p": "A plan adapted to your level and goals, with simple, concrete nutrition guidelines, no extreme diet.",
      "ctaH2": "Ready to (re)start training in Linkebeek?",
      "ctaP": "First trial session free, no commitment. At home or by video, we start whenever you want.",
      "btnContact": "Contact me"
    },
    "braine": {
      "metaTitle": "Personal trainer in Braine-l'Alleud | at home & video — CoachTanguy",
      "metaDesc": "Personal trainer in Braine-l'Alleud: sessions at home or by video, led by a qualified coach. Fitness, physical preparation. First trial session free.",
      "heroEyebrow": "Personal training · Braine-l'Alleud",
      "h1": "Personal trainer in Braine-l'Alleud",
      "heroLead": "Personal training in Braine-l'Alleud: sessions led by a qualified coach, at home or by video call. From simple fitness to physical preparation, I guide you step by step, safely.",
      "btnEssai": "Free trial session",
      "btnVisio": "See video coaching",
      "secEyebrow": "In Braine-l'Alleud and nearby",
      "h2": "Ease back into training in Braine-l'Alleud",
      "secIntro": "We move forward step by step, with realistic goals and regular follow-up. The idea isn't to overhaul everything at once, but to build habits that last.",
      "f1h": "At home in Braine-l'Alleud",
      "f1p": "I come to you in Braine-l'Alleud with the equipment needed. You train in a familiar setting, at a time that suits you.",
      "f2h": "Coaching by video",
      "f2p": "From Braine-l'Alleud or on the move, follow your sessions by video call, with an updated programme and real-time corrections.",
      "f3h": "Tailored programme & nutrition",
      "f3p": "A plan adapted to your level and goals, with simple, concrete nutrition guidelines, no extreme diet.",
      "ctaH2": "Ready to (re)start training in Braine-l'Alleud?",
      "ctaP": "First trial session free, no commitment. At home or by video, we start whenever you want.",
      "btnContact": "Contact me"
    }
  },
  "legal": {
    "privacy": {
      "title": "Privacy policy — CoachTanguy",
      "desc": "How CoachTanguy processes your personal data: purposes, legal bases, retention periods and your rights (GDPR).",
      "body": "      <span class=\"eyebrow\">Privacy</span>\n      <h1>Privacy policy</h1>\n      <p class=\"legal__update\">Last updated: 29 July 2026</p>\n\n      <h2>1. Data controller</h2>\n      <p>The controller of the personal data is:</p>\n      <ul>\n        <li>Tanguy Witters, CoachTanguy</li>\n        <li>Independent sports coach</li>\n        <li>Address: Avenue de la Pépinière 11, 1640 Rhode-Saint-Genèse, Belgium</li>\n        <li>Company number (CBE): 1026.048.974</li>\n        <li>VAT number: BE1026048974</li>\n        <li>E-mail: <a href=\"mailto:contact@coachtanguy.com\">contact@coachtanguy.com</a></li>\n        <li>Phone: +32 472 76 16 39</li>\n      </ul>\n      <p>This policy explains how personal data is collected and used through the coachtanguy.com website and in the context of the sports coaching services.</p>\n\n      <h2>2. Data collected, purposes and legal bases</h2>\n\n      <h3>Contact requests</h3>\n      <p>When you use the contact form or contact CoachTanguy directly by e-mail, phone or WhatsApp, the following data may be processed:</p>\n      <ul>\n        <li>first name and last name;</li>\n        <li>e-mail address;</li>\n        <li>phone number;</li>\n        <li>content of the messages;</li>\n        <li>information relating to your request.</li>\n      </ul>\n      <p>This data is used to answer your request, arrange a call and provide you with the information you need before a possible order. The legal basis is the performance of pre-contractual measures taken at your request and the legitimate interest of CoachTanguy in replying to the people who contact him.</p>\n\n      <h3>Organisation of the coaching</h3>\n      <p>When you become a Client, the following data may in particular be processed:</p>\n      <ul>\n        <li>identity and contact details;</li>\n        <li>sports goals;</li>\n        <li>level and experience;</li>\n        <li>availability and organisation;</li>\n        <li>available equipment;</li>\n        <li>history of the sessions;</li>\n        <li>performance, progress and feedback;</li>\n        <li>training programmes;</li>\n        <li>answers to questionnaires and check-ups;</li>\n        <li>exchanges by e-mail or WhatsApp.</li>\n      </ul>\n      <p>This data is necessary in order to create, organise, personalise and follow up your coaching. The legal basis is the performance of the contract concluded with the Client.</p>\n\n      <h3>Health data</h3>\n      <p>In order to adapt the exercises and ensure the Client's safety, CoachTanguy may collect information about, in particular:</p>\n      <ul>\n        <li>pain;</li>\n        <li>injuries;</li>\n        <li>medical conditions;</li>\n        <li>physical limitations;</li>\n        <li>treatments that have an impact on sports practice;</li>\n        <li>pregnancy or breastfeeding where relevant;</li>\n        <li>medical history useful for the coaching.</li>\n      </ul>\n      <p>Health data is sensitive data. It is processed only with the explicit and separate consent of the Client and only to the extent necessary to adapt and secure the coaching. Consent may in particular be obtained through the following checkbox in the initial questionnaire:</p>\n      <blockquote>\n        <p>I explicitly consent to the health information I provide being used by CoachTanguy solely in order to adapt and secure my sports coaching.</p>\n      </blockquote>\n      <p>The Client may withdraw consent at any time. Where certain information is essential to the Client's safety, withdrawing it may prevent the continuation of certain exercises or of personalised coaching.</p>\n\n      <h3>Photos and videos</h3>\n      <p>The Client may voluntarily send photos or videos in order to allow:</p>\n      <ul>\n        <li>a technical correction;</li>\n        <li>the analysis of an exercise;</li>\n        <li>the follow-up of progress.</li>\n      </ul>\n      <p>This content is not published and is not used for advertising purposes without the prior, separate and explicit agreement of the Client.</p>\n\n      <h3>Bookings</h3>\n      <p>When a booking tool such as Zcal is used, the data required for the booking may be processed:</p>\n      <ul>\n        <li>name;</li>\n        <li>e-mail address;</li>\n        <li>date and time of the appointment;</li>\n        <li>information provided when booking.</li>\n      </ul>\n      <p>This data is used to organise and confirm the appointments.</p>\n\n      <h3>Payments and invoicing</h3>\n      <p>Payments are processed through Stripe and the payment methods available on its secure page. CoachTanguy does not directly collect or store the Client's full banking details.</p>\n      <p>The data required for invoicing and accounting may be sent to the Accountable tool or to an accounting adviser. It is processed in order to perform the order and to comply with tax and accounting obligations.</p>\n\n      <h3>Nutrition calculator</h3>\n      <p>The data entered in the free nutrition calculator, in particular age, sex, height, weight, activity and goal, is processed directly in the user's browser. It is not sent to CoachTanguy and is not stored on a server, unless a future change to the way the calculator works is clearly announced.</p>\n\n      <h3>Technical data</h3>\n      <p>When you browse the website, the hosting provider may process certain technical data necessary for the operation and security of the site, in particular:</p>\n      <ul>\n        <li>IP address;</li>\n        <li>browser and device type;</li>\n        <li>date and time of connection;</li>\n        <li>technical logs and security information.</li>\n      </ul>\n      <p>Information about cookies and local storage is set out in the <a href=\"cookies.html\">Cookie policy</a>.</p>\n\n      <h3>No profiling</h3>\n      <p>CoachTanguy currently does not use personal data for any automated decision producing legal effects, any automated profiling or any automated commercial prospecting.</p>\n\n      <h2>3. Mandatory or optional nature of the data</h2>\n      <p>The information indicated as mandatory is necessary in order to:</p>\n      <ul>\n        <li>answer a request;</li>\n        <li>make a booking;</li>\n        <li>issue an invoice;</li>\n        <li>create a programme;</li>\n        <li>ensure the safety and the follow-up of the Client.</li>\n      </ul>\n      <p>Refusing to provide certain data may prevent CoachTanguy from answering the request, concluding the order or offering sufficiently suitable coaching. Optional information is clearly presented as such.</p>\n      <p>The data is mainly obtained directly from the person concerned. For a minor Client, certain information may be provided by their legal representative.</p>\n\n      <h2>4. Recipients of the data</h2>\n      <p>Personal data is never sold. It is accessible only to CoachTanguy and, where necessary, to the following service providers:</p>\n      <ul>\n        <li>Netlify, for the hosting of the website and the contact form;</li>\n        <li>the provider of the e-mail service used by CoachTanguy;</li>\n        <li>WhatsApp and Meta, for communications made through WhatsApp;</li>\n        <li>FitPros, for the creation, hosting and follow-up of the sports programmes;</li>\n        <li>Zcal, for the booking of appointments;</li>\n        <li>the tool used for questionnaires and check-ups, in particular Google Forms when it is used;</li>\n        <li>Stripe and the payment providers chosen by the Client;</li>\n        <li>Accountable or the accounting adviser, for invoicing and accounting;</li>\n        <li>the administrative or judicial authorities where the law requires it.</li>\n      </ul>\n      <p>Each service provider receives only the data necessary for its task. When the Client uses an external platform, the use of that platform is also subject to the privacy policy of the provider concerned.</p>\n\n      <h2>5. Transfers outside the European Economic Area</h2>\n      <p>Certain technical providers, in particular Netlify, Meta, Stripe or Google, may process data outside the European Economic Area.</p>\n      <p>Where this happens, the transfers are governed by the mechanisms provided for by the GDPR, in particular an adequacy decision, standard contractual clauses or other appropriate safeguards.</p>\n\n      <h2>6. Retention periods</h2>\n      <p>Data is kept only for as long as necessary for its purpose:</p>\n      <ul>\n        <li>contact requests with no follow-up: no more than 12 months after the last exchange;</li>\n        <li>bookings and pre-contractual exchanges: no more than 12 months after the appointment or the last exchange;</li>\n        <li>programmes, questionnaires, check-ups and client follow-up: during the coaching, then no more than 12 months after it ends;</li>\n        <li>WhatsApp messages and e-mails linked to the coaching: during the client relationship, then no more than 12 months after it ends, unless a specific exchange needs to be kept;</li>\n        <li>health data: during the coaching, then no more than 12 months after it ends, unless consent is withdrawn earlier, or in the event of a dispute or a legal obligation;</li>\n        <li>photos and videos of execution or progress: for the time needed to analyse them and no more than 12 months after the end of the coaching;</li>\n        <li>accounting documents and invoices: 10 years in accordance with Belgian legal obligations;</li>\n        <li>data stored in the browser: until it is deleted by the user;</li>\n        <li>technical logs: for the time needed for the security and proper operation of the site, according to the hosting provider's settings.</li>\n      </ul>\n      <p>Once these periods have expired, the data is deleted or anonymised, except where longer retention is necessary to comply with a legal obligation or to defend a right in court.</p>\n\n      <h2>7. Rights of individuals</h2>\n      <p>Any person concerned has the following rights, under the conditions provided for by the GDPR:</p>\n      <ul>\n        <li>the right to obtain information about the processing;</li>\n        <li>the right to access their data;</li>\n        <li>the right to have inaccurate data corrected;</li>\n        <li>the right to request erasure;</li>\n        <li>the right to request the restriction of processing;</li>\n        <li>the right to object to certain processing;</li>\n        <li>the right to data portability;</li>\n        <li>the right to withdraw consent at any time.</li>\n      </ul>\n      <p>Withdrawing consent does not affect the lawfulness of the processing carried out before that withdrawal.</p>\n      <p>To exercise these rights, a request may be sent to: <a href=\"mailto:contact@coachtanguy.com\">contact@coachtanguy.com</a>. A reply is provided within one month. Proof of identity may be requested only in the event of reasonable doubt about the identity of the applicant.</p>\n\n      <h2>8. Security</h2>\n      <p>CoachTanguy takes reasonable technical and organisational measures to protect personal data, in particular:</p>\n      <ul>\n        <li>use of an HTTPS connection;</li>\n        <li>restricted access to the data;</li>\n        <li>use of protected accounts;</li>\n        <li>collection limited to the necessary information;</li>\n        <li>use of professional service providers;</li>\n        <li>deletion or archiving of data that has become unnecessary.</li>\n      </ul>\n      <p>Despite these measures, no computer system or service accessible over the internet can guarantee absolute security.</p>\n\n      <h2>9. Links and external platforms</h2>\n      <p>The website may contain links to external platforms such as Stripe, WhatsApp, FitPros, Zcal or social media.</p>\n      <p>CoachTanguy has no control over the processing carried out directly by these platforms. Users are invited to consult their own privacy policies before sending them any data.</p>\n\n      <h2>10. Complaint to the Belgian Data Protection Authority</h2>\n      <p>Any person who considers that their data is not being processed in accordance with the regulations may lodge a complaint with:</p>\n      <ul>\n        <li>Belgian Data Protection Authority</li>\n        <li>Rue de la Presse 35, 1000 Brussels</li>\n        <li>Phone: +32 (0)2 274 48 00</li>\n        <li>E-mail: <a href=\"mailto:contact@apd-gba.be\">contact@apd-gba.be</a></li>\n      </ul>\n\n      <h2>11. Changes to the policy</h2>\n      <p>This policy may be amended in order to take account of:</p>\n      <ul>\n        <li>a change to the website;</li>\n        <li>the addition or removal of a service provider;</li>\n        <li>a change to the services;</li>\n        <li>a change in the regulations.</li>\n      </ul>\n      <p>The date of the last update is shown at the top of the page.</p>\n\n      <p class=\"legal__back\"><a href=\"index.html\">← Back to home</a></p>"
    },
    "cookies": {
      "title": "Cookie policy — CoachTanguy",
      "desc": "CoachTanguy uses no tracking cookies. Details of the functional local storage used and your options.",
      "body": "<span class=\"eyebrow\">Cookies &amp; local storage</span>\n      <h1>Cookie policy</h1>\n      <p class=\"legal__update\">Last updated: June 2026</p>\n\n      <h2>1. No tracking cookies</h2>\n      <p><strong>coachtanguy.com</strong> uses <strong>no analytics, advertising or social-media cookies</strong>, and no third-party trackers. No consent banner is therefore required: in line with the recommendations of the Belgian Data Protection Authority, only storage strictly necessary for the operation of the site is used, which is exempt from consent.</p>\n\n      <h2>2. Functional local storage</h2>\n      <p>The site uses your browser's local storage (localStorage / sessionStorage / Cache Storage) solely for the following technical purposes:</p>\n      <ul>\n        <li><strong>\"Calculator\" app cache</strong> (Cache Storage, if you install the calculator as an app): keeps the files needed to work offline. Duration: until you uninstall the app or clear the cache.</li>\n        <li><strong>SITE_CONTENT_fr / _nl / _en</strong> and <strong>CALC_I18N_fr / _nl / _en</strong> (localStorage): content drafts, used only in preview mode by the site administrator. They are neither read nor created during a normal visit. Duration: until manually deleted.</li>\n        <li><strong>dash_ok</strong> (sessionStorage): keeps the administrator's session on the editing dashboard. Duration: closing the tab.</li>\n        <li><strong>cookie_consent</strong> (localStorage): would remember your choice if a consent banner were ever activated. <em>Not currently used.</em> Maximum duration: 6 months.</li>\n      </ul>\n      <p>This storage stays in your browser: it sends no information to third parties and cannot be used to track you.</p>\n\n      <h2>3. External services</h2>\n      <ul>\n        <li><strong>Fonts</strong>: hosted locally on the site, no request is made to Google Fonts.</li>\n        <li><strong>Stripe payments</strong>: the payment buttons are plain links to Stripe's secure pages; Stripe's cookies only apply on Stripe's site (see their <a href=\"https://stripe.com/en-be/privacy\" target=\"_blank\" rel=\"noopener\">privacy policy</a>).</li>\n        <li><strong>WhatsApp</strong>: the WhatsApp buttons are links; no Meta script is loaded on this site.</li>\n      </ul>\n\n      <h2>4. How to delete this data?</h2>\n      <p>You can clear your browser's local storage and cache at any time: Settings → Privacy → Clear browsing data (or equivalent depending on your browser). For the installed app, simply uninstall it.</p>\n\n      <h2>5. If trackers were ever added</h2>\n      <p>If non-essential cookies (statistics, marketing) were ever used, they would only be set <strong>after your prior, free and informed consent</strong>, collected through a banner where refusing is as easy as accepting, with no pre-ticked boxes, and your choice would be kept for a maximum of 6 months. This page would be updated accordingly.</p>\n\n      <p class=\"legal__back\"><a href=\"index.html\">← Back to home</a></p>"
    }
  },
  "collab": {
    "title": "Partner physiotherapist in Rhode-Saint-Genèse — ZOWE × CoachTanguy",
    "desc": "CoachTanguy partners with ZOWE, Zoé Grêde's physiotherapy practice in Rhode-Saint-Genèse: care and sports coaching go hand in hand.",
    "eyebrow": "Health partnership",
    "h1": "ZOWE Physio × CoachTanguy",
    "intro": "To support you from recovery to performance, I work with Zoé Grêde, certified physiotherapist (Master's in physiotherapy and rehabilitation, ULB) and BELTRA-method practitioner. Her practice ZOWE is based at Kinovea, Rue des Iris in Rhode-Saint-Genèse, right in my coaching area.",
    "f1h": "From care to training",
    "f1p": "Injury, pain, reduced mobility? Zoé restores movement; I take over to rebuild strength and endurance, safely.",
    "f2h": "Precise expertise",
    "f2p": "Morphostatic assessment, deep myofascial work, IASTM, cupping therapy, joint mobilisations: a targeted approach that treats the cause, not just the symptoms.",
    "f3h": "The same area",
    "f3p": "Practice in Rhode-Saint-Genèse and home visits in Linkebeek, Beersel, Lot, Braine-l'Alleud and Waterloo, exactly where I coach.",
    "cardEyebrow": "ZOWE, Physiotherapy",
    "cardTitle": "Need a physio's opinion?",
    "cardText": "Lower-back pain, neck pain, tendinitis, chronic pain or returning to sport after injury: discover Zoé's approach, \"The art of precision, the expertise of care\".",
    "chip1": "✓ BELTRA method",
    "chip2": "✓ Kinovea practice · Rhode-Saint-Genèse",
    "chip3": "✓ FR · NL · EN",
    "button": "Visit zowekine.com",
    "aboutEyebrow": "Who am I?",
    "aboutTitle": "Zoé Grêde, BELTRA physiotherapist",
    "aboutP1": "I designed Zowe with a clear vision: to turn the physiotherapy session into a high-precision experience.",
    "aboutP2": "My approach doesn't stop once the pain is gone, it aims for the lasting optimisation of your physical capital.",
    "tick1": "Université Libre de Bruxelles",
    "tick2": "Master's in physiotherapy and rehabilitation",
    "tick3": "Conventional physiotherapy too, via Kinovea",
    "aboutP3": "To reach that level of precision, I trained specifically in the Beltra method. This expertise allows me to bring advanced care protocols into my practice, focused on technical control and the deep re-harmonisation of the body.",
    "aboutP4": "As every patient is unique, I put my know-how and this specialisation at the service of tailor-made support, where scientific rigour meets the comfort of exclusive care."
  }
};
(window.SITE_CONTENT_ALL = window.SITE_CONTENT_ALL || {}).en = window.SITE_CONTENT;
