/* ===========================================================
   CONTENU FRANÇAIS — CoachTanguy
   Édité via dashboard.html. Ne pas casser la structure des clés.
   =========================================================== */
window.SITE_CONTENT = {
  "nav": {
    "accueil": "Accueil",
    "visio": "Coaching visio",
    "suivi": "Suivi en ligne",
    "calculateur": "Calculateur",
    "faq": "FAQ",
    "contact": "Contact",
    "cta": "Réserver un appel"
  },
  "calc": {
    "eyebrow": "Outil gratuit",
    "title": "Calculateur alimentaire",
    "subtitle": "Estimez vos besoins caloriques et la répartition de vos macros en quelques secondes, selon votre profil et vos objectifs."
  },
  "home": {
    "hero": {
      "eyebrow": "Coach sportif diplômé",
      "titleHtml": "Le sport facile,<br />partout et à tout moment.",
      "subtitle": "Coaching visio et suivi en ligne, adapté à votre niveau, vos objectifs et votre emploi du temps.",
      "ctaPrimary": "Coaching visio",
      "ctaSecondary": "Suivi en ligne",
      "pill1": "✓ Visioconférence",
      "pill2": "✓ Plans personnalisés",
      "pill3": "✓ Sans engagement"
    },
    "trust": {
      "v1": "500+",
      "l1": "heures de formation",
      "v2": "100%",
      "l2": "personnalisé",
      "v3": "7j/7",
      "l3": "accompagnement",
      "v4": "1ère",
      "l4": "séance offerte"
    },
    "services": {
      "eyebrow": "Services",
      "title": "Un accompagnement à votre rythme",
      "subtitle": "Deux formules pensées pour vous faire progresser, où que vous soyez.",
      "c1Title": "Coaching visio",
      "c1Text": "Profitez d'un accompagnement professionnel à distance via visioconférence, pour garder la motivation partout où vous êtes.",
      "c1Link": "Découvrir l'offre →",
      "c2Title": "Suivi en ligne",
      "c2Text": "Accédez à un suivi, des plans d'entraînement et conseils personnalisés via une application.",
      "c2Link": "Découvrir l'offre →"
    },
    "process": {
      "eyebrow": "Comment ça marche",
      "title": "Que ce soit avec le coaching visio ou le suivi en ligne, progressez en 3 étapes simples",
      "s1Title": "Échange découverte",
      "s1Text": "Un premier appel offert pour comprendre vos besoins, vos objectifs et tester la méthode ensemble.",
      "s2Title": "Plan sur-mesure",
      "s2Text": "Je construis un programme adapté à votre niveau, votre emploi du temps et votre matériel.",
      "s3Title": "Suivi & résultats",
      "s3Text": "On avance ensemble : séances, ajustements réguliers et motivation pour des résultats durables."
    },
    "about": {
      "eyebrow": "À propos",
      "title": "Tanguy, votre coach sportif",
      "p1": "Diplômé d'un Bachelier en Coaching Sportif, je m'appuie sur de solides connaissances en anatomie, physiologie, nutrition et science de l'entraînement pour vous accompagner en toute sécurité.",
      "p2": "J'ai travaillé avec des profils variés, des enfants aux seniors, et adapte chaque programme à vos besoins. Mon parcours, c'est plus de 500 heures de stage, 2 ans d'expérience en tant que coach personnel et plus de 10 ans de pratique personnelle de la musculation.",
      "s1v": "500+",
      "s1l": "heures de stage",
      "s2v": "2 ans",
      "s2l": "de coaching",
      "s3v": "10+ ans",
      "s3l": "de pratique",
      "cta": "Travailler avec moi"
    },
    "faq": {
      "eyebrow": "FAQ",
      "title": "Questions fréquemment posées.",
      "q1": "Pourquoi proposer des packs de séances ?",
      "a1": "Les packs permettent de simplifier l'organisation avec un seul paiement, tout en favorisant un engagement sur la durée. Ils aident également à rester régulier et motivé dans les séances, ce qui est essentiel pour progresser et obtenir des résultats concrets.",
      "q2": "Comment réserver une séance ?",
      "a2": "Toutes les 2 semaines, vous recevez un lien vers mon agenda électronique via WhatsApp pour réserver votre séance. Les réservations se font toutes les 2 semaines afin de garantir plus de flexibilité et de s'adapter à votre emploi du temps.",
      "q3": "Puis-je annuler ou reporter une séance ?",
      "a3": "Pas de panique, vous pouvez annuler une séance et la reporter à une autre date tant que votre pack est encore valide. Une fois la date de fin du pack dépassée, toute séance non utilisée est perdue.",
      "q4": "Quelle est la durée de validité d'un pack ?",
      "a4": "Les packs de 4 séances sont valables 5 semaines et les packs 8 séances sont valables 10 semaines à compter de la date de paiement. Cette durée permet de garantir une pratique régulière et d'optimiser les résultats. Passé ces délais, les séances non utilisées seront perdues. Le report d'une séance ne prolonge pas la durée de validité du pack.",
      "q5": "Quels moyens de paiement sont acceptés ?",
      "a5": "Les paiements peuvent être effectués par Visa, Mastercard, Revolut Pay, PayPal, Klarna, Bancontact, Apple Pay ou Google Pay. Le paiement s'effectue de manière sécurisée via Stripe.",
      "q6": "Et si je pars en vacances ?",
      "a6": "Aucun souci : votre pack ou votre suivi est simplement mis en pause et reprendra à votre retour.",
      "q7": "Puis-je payer en plusieurs fois ?",
      "a7": "Oui, le paiement via Klarna est disponible. Il peut vous permettre de payer votre pack sous 30 jours, selon votre éligibilité. Le paiement reste sécurisé et s'effectue directement via Stripe."
    },
    "cta": {
      "title": "Prêt à vous lancer ?",
      "text": "Contactez-moi pour discuter de vos objectifs et trouver la formule qui vous correspond. La première séance est offerte.",
      "button": "Me contacter"
    },
    "payments": {
      "title": "Paiement sécurisé via Stripe"
    },
    "calcTeaser": {
      "eyebrow": "Outil gratuit",
      "title": "Calculez vos besoins caloriques en 2 minutes",
      "text": "Métabolisme de base, calories cibles, répartition des macros et repères concrets pour composer vos repas : mon calculateur alimentaire gratuit vous donne une base claire pour démarrer — sans inscription.",
      "chip1": "✓ Calories & macros",
      "chip2": "✓ Méthode de l'assiette",
      "chip3": "✓ Idées de repas",
      "button": "Essayer le calculateur"
    }
  },
  "footer": {
    "tagline": "Le sport facile, partout et à tout moment.",
    "areas": "Coach sportif à Rhode-Saint-Genèse, Uccle, Waterloo, Beersel, Linkebeek et Braine-l'Alleud — à domicile ou en visio.",
    "lVisio": "Coaching visio",
    "lSuivi": "Suivi en ligne",
    "lFaq": "FAQ",
    "lContact": "Contact",
    "lMentions": "Mentions légales",
    "lCgv": "CGV",
    "copyright": "© 2026 CoachTanguy. Tous droits réservés."
  },
  "contact": {
    "eyebrow": "Contact",
    "title": "Contactez Tanguy",
    "subtitle": "Une question ? Envie de commencer ? Écrivez-moi, je vous réponds rapidement.",
    "asideTitle": "Une question ?",
    "asideText": "Le plus simple et le plus rapide : un message direct sur WhatsApp.",
    "waLabel": "WhatsApp",
    "waSub": "+32 472 76 16 39",
    "emailLabel": "Email",
    "emailSub": "tanguy_coaching@hotmail.com",
    "note": "✓ Première séance d'essai offerte",
    "formTitle": "Message rapide",
    "fName": "Nom",
    "phName": "Votre nom",
    "fEmail": "Email",
    "phEmail": "vous@email.com",
    "fSubject": "Sujet",
    "optVisio": "Coaching visio",
    "optSuivi": "Suivi en ligne",
    "optEssai": "Séance d'essai offerte",
    "optAutre": "Autre question",
    "fMessage": "Message",
    "phMessage": "Parlez-moi de vos objectifs...",
    "submit": "Envoyer le message",
    "consent": "En envoyant ce message, vous serez recontacté par Tanguy dans la journée."
  },
  "visio": {
    "heroEyebrow": "Coaching Visio",
    "heroTitleHtml": "Flexible, interactif,<br />efficace.",
    "heroSubtitle": "Profitez de séances individuelles de coaching sportif à distance, accessibles partout. Coaching personnalisé, conseils en temps réel et suivi sur-mesure par visioconférence.",
    "heroCta1": "Aller directement aux packs",
    "heroCta2": "Séance d'essai offerte",
    "f1Title": "Coaching sur-mesure",
    "f1Text": "Des séances adaptées à votre rythme, vos objectifs et votre espace, où que vous soyez.",
    "f2Title": "Packs de séances",
    "f2Text": "Des packs conçus selon votre fréquence d'entraînement pour garantir une vraie régularité.",
    "f3Title": "Séance d'essai offerte",
    "f3Text": "Un premier échange pour découvrir vos besoins, tester la méthode et définir ensemble vos objectifs.",
    "packsEyebrow": "Packs",
    "packsTitle": "Choisissez la formule qui vous convient",
    "packsSubtitle": "Adaptée et personnalisée · feedback après chaque séance · report possible en cas de vacances.",
    "p1Name": "Séance à l'unité",
    "p1Meta": "Séance de 30 à 40 min",
    "p1l1": "Séance adaptée et personnalisée",
    "p1l2": "Feedback après la séance",
    "p1l3": "Sans engagement",
    "p1Note": "💳 Paiement lors de la réservation",
    "p1Btn": "Réserver",
    "p2Ribbon": "Le plus choisi",
    "p2Name": "Pack 4 séances",
    "p2PriceSub": "soit 35€ / séance",
    "p2Meta": "Valable 5 semaines",
    "p2l1": "4 séances personnalisées",
    "p2l2": "Feedback après chaque séance",
    "p2l3": "Report possible en cas de vacances",
    "p2l4": "Idéal 1 séance / semaine",
    "p2Btn": "Choisir",
    "p3Name": "Pack 8 séances",
    "p3PriceSub": "soit 30€ / séance",
    "p3Meta": "Valable 10 semaines",
    "p3l1": "8 séances personnalisées",
    "p3l2": "Feedback après chaque séance",
    "p3l3": "Report possible en cas de vacances",
    "p3l4": "Le meilleur tarif / séance",
    "p3Btn": "Choisir",
    "ctaTitle": "Prêt à commencer ?",
    "ctaText": "Réservez votre séance d'essai offerte et lançons-nous ensemble.",
    "ctaBtn": "Contacter"
  },
  "suivi": {
    "heroEyebrow": "Suivi en Ligne",
    "heroTitleHtml": "Coaching sportif<br />à distance.",
    "heroSubtitle": "Un suivi à votre rythme, 100% personnalisé, où que vous soyez via l'application FitPros. Programme évolutif, conseils réguliers et accompagnement sur-mesure pour progresser efficacement.",
    "heroCta1": "Aller directement aux suivis",
    "heroCta2": "Poser une question",
    "appEyebrow": "FitPros",
    "appTitle": "Votre programme sur mesure dans votre poche.",
    "appText": "Un espace simple pour suivre votre progression et rester motivé au quotidien.",
    "appB1Title": "Un espace simple pour suivre votre progression.",
    "appB1Text": "Depuis l'application, vous retrouvez facilement vos entraînements en cours, votre progression de la semaine et les prochaines séances prévues. Tout est centralisé pour garder une vision claire de votre suivi et rester régulier dans votre pratique.",
    "appB2Title": "Des séances guidées étape par étape.",
    "appB2Text": "Chaque séance est organisée de manière claire avec les exercices, les séries, les répétitions, les consignes associées et les vidéos d'exécution. Vous pouvez lancer votre entraînement directement depuis l'application et suivre le programme à votre rythme, en toute autonomie.",
    "appT1": "Des séances guidées étape par étape",
    "appT2": "Suivi clair de votre progression",
    "appT3": "Conseils et ajustements réguliers",
    "appT4": "Communication directe via WhatsApp",
    "appBtn": "Voir les formules",
    "suivisEyebrow": "Suivis",
    "suivisTitle": "Un suivi expert, 100% personnalisé",
    "suivisSubtitle": "Programme sur-mesure, ajustements réguliers et accompagnement humain.",
    "flowLabel": "puis",
    "s1Ribbon": "Pour démarrer",
    "s1Name": "Accompagnement initial",
    "s1PriceSub": "pour 8 semaines",
    "s1l1": "Accompagnement personnalisé pendant 8 semaines",
    "s1l2": "Programme d'entraînement sur-mesure adapté à vos objectifs",
    "s1l3": "Accès via l'app FitPros",
    "s1l4": "Communication & suivi via WhatsApp",
    "s1l5": "Appel visio d'introduction (~30 min) offert",
    "s1l6": "Programme accessible sous 72h après l'appel",
    "s1l7": "Check-up toutes les 2 semaines via un formulaire",
    "s1l8": "Ajustements réguliers pour des résultats optimaux",
    "s1l9": "Mise en pause possible en cas de vacances",
    "s1Btn": "Choisir",
    "s2Name": "Suivi mensuel",
    "s2PriceSub": "par mois",
    "s2Meta": "Uniquement après l'accompagnement initial",
    "s2l1": "Programme d'entraînement sur-mesure",
    "s2l2": "Accès via l'app FitPros",
    "s2l3": "Communication & suivi via WhatsApp",
    "s2l4": "Check-up toutes les 2 semaines",
    "s2l5": "Ajustements réguliers",
    "s2l6": "Mise en pause possible en cas de vacances",
    "s2Btn": "Choisir",
    "ctaTitle": "Prêt à progresser ?",
    "ctaText": "Réservez votre appel d'introduction offert et construisons votre programme.",
    "ctaBtn": "Contacter"
  },
  "stripe": {
    "unite": "contact.html",
    "pack4": "https://buy.stripe.com/5kQ4gBdvB0Yz85A7Pa0RG0a",
    "pack8": "https://buy.stripe.com/8x2cN7fDJePpadI8Te0RG0b",
    "initial": "https://buy.stripe.com/8x214p8bh22D0D84CY0RG08",
    "mensuel": "https://buy.stripe.com/dRm8wR63922DdpUfhC0RG09"
  },
  "meta": {
    "index": {
      "title": "Coach sportif à Rhode-Saint-Genèse & Brabant — CoachTanguy",
      "desc": "Coach sportif à Rhode-Saint-Genèse : coaching à domicile, en visio et suivi en ligne. Aussi à Waterloo, Beersel, Linkebeek et Braine-l'Alleud. 1ère séance offerte."
    },
    "visio": {
      "title": "Coaching Visio — CoachTanguy",
      "desc": "Coaching sportif individuel à distance par visioconférence. Flexible, interactif et efficace. Première séance d'essai offerte."
    },
    "suivi": {
      "title": "Suivi en Ligne — CoachTanguy",
      "desc": "Suivi sportif 100% personnalisé via l'application FitPros : programme évolutif, conseils réguliers et accompagnement sur-mesure pour progresser efficacement."
    },
    "contact": {
      "title": "Contact — CoachTanguy",
      "desc": "Une question ? Contactez CoachTanguy via WhatsApp ou par message. Première séance d'essai offerte."
    },
    "calc": {
      "title": "Calculateur alimentaire — CoachTanguy",
      "desc": "Calculateur alimentaire gratuit : estimez vos besoins caloriques et la répartition de vos macros (protéines, glucides, lipides) selon votre profil et vos objectifs."
    }
  },
  "local": {
    "rhode": {
      "metaTitle": "Coach sportif à Rhode-Saint-Genèse | à domicile & visio — CoachTanguy",
      "metaDesc": "Coach sportif à Rhode-Saint-Genèse : séances à domicile ou en visio, programme et nutrition sur-mesure. Coach diplômé, 1ère séance offerte.",
      "heroEyebrow": "Coaching sportif · Rhode-Saint-Genèse",
      "h1": "Coach sportif à Rhode-Saint-Genèse",
      "heroLead": "Basé à Rhode-Saint-Genèse, je propose un coaching sportif sur-mesure directement chez vous ou en visioconférence. Du centre aux quartiers proches de la Forêt de Soignes, je m'adapte à votre niveau, vos objectifs et votre emploi du temps — que vous soyez débutant ou déjà sportif.",
      "btnEssai": "Séance d'essai offerte",
      "btnVisio": "Voir le coaching visio",
      "secEyebrow": "À Rhode-Saint-Genèse et alentours",
      "h2": "Votre coach sportif à domicile et en visio à Rhode-Saint-Genèse",
      "secIntro": "Pas besoin de salle ni de longs trajets : je viens chez vous, ou nous travaillons en visio avec un programme suivi entre les séances. Idéal si vous manquez de temps ou préférez un cadre privé et personnalisé.",
      "f1h": "À domicile à Rhode-Saint-Genèse",
      "f1p": "Je me déplace chez vous à Rhode-Saint-Genèse avec le matériel nécessaire. Vous vous entraînez dans un cadre familier, à l'horaire qui vous arrange.",
      "f2h": "Coaching en visio",
      "f2p": "Depuis Rhode-Saint-Genèse ou en déplacement, suivez vos séances en visioconférence, avec un programme mis à jour et des corrections en temps réel.",
      "f3h": "Programme & nutrition sur-mesure",
      "f3p": "Un plan adapté à votre niveau et vos objectifs, avec des repères nutrition simples et concrets — sans régime extrême.",
      "ctaH2": "Prêt à vous (re)mettre au sport à Rhode-Saint-Genèse ?",
      "ctaP": "Première séance d'essai offerte, sans engagement. À domicile ou en visio, on commence quand vous voulez.",
      "btnContact": "Me contacter"
    },
    "uccle": {
      "metaTitle": "Coach sportif à Uccle | à domicile & visio — CoachTanguy",
      "metaDesc": "Coach sportif à Uccle : séances à domicile ou en visio, programme et nutrition sur-mesure. Coach diplômé, 1ère séance offerte.",
      "heroEyebrow": "Coaching sportif · Uccle",
      "h1": "Coach sportif à Uccle",
      "heroLead": "Juste au nord de Rhode-Saint-Genèse, j'accompagne les habitants d'Uccle avec un coaching sportif personnalisé, à domicile ou en visioconférence. Du Fort-Jaco au Vivier d'Oie, je m'adapte à votre niveau, vos objectifs et votre emploi du temps.",
      "btnEssai": "Séance d'essai offerte",
      "btnVisio": "Voir le coaching visio",
      "secEyebrow": "À Uccle et alentours",
      "h2": "Votre coach sportif à domicile et en visio à Uccle",
      "secIntro": "Pas besoin de salle bondée : je viens chez vous, ou nous travaillons en visio avec un programme suivi entre les séances. Pratique pour les agendas chargés et les quartiers résidentiels d'Uccle.",
      "f1h": "À domicile à Uccle",
      "f1p": "Je me déplace chez vous à Uccle avec le matériel nécessaire. Vous vous entraînez dans un cadre familier, à l'horaire qui vous arrange.",
      "f2h": "Coaching en visio",
      "f2p": "Depuis Uccle ou en déplacement, suivez vos séances en visioconférence, avec un programme mis à jour et des corrections en temps réel.",
      "f3h": "Programme & nutrition sur-mesure",
      "f3p": "Un plan adapté à votre niveau et vos objectifs, avec des repères nutrition simples et concrets — sans régime extrême.",
      "ctaH2": "Prêt à vous (re)mettre au sport à Uccle ?",
      "ctaP": "Première séance d'essai offerte, sans engagement. À domicile ou en visio, on commence quand vous voulez.",
      "btnContact": "Me contacter"
    },
    "waterloo": {
      "metaTitle": "Coach sportif à Waterloo | à domicile & visio — CoachTanguy",
      "metaDesc": "Coach sportif à Waterloo : coaching personnalisé à domicile ou en visio, perte de poids, remise en forme, prise de muscle. 1ère séance offerte.",
      "heroEyebrow": "Coaching sportif · Waterloo",
      "h1": "Coach sportif à Waterloo",
      "heroLead": "À quelques minutes de Rhode-Saint-Genèse, j'accompagne les habitants de Waterloo avec un coaching sportif personnalisé, à domicile ou en visio. Perte de poids, remise en forme, prise de muscle ou préparation physique : on bâtit ensemble un programme réaliste et progressif.",
      "btnEssai": "Séance d'essai offerte",
      "btnVisio": "Voir le coaching visio",
      "secEyebrow": "À Waterloo et alentours",
      "h2": "Un coaching sportif sur-mesure à Waterloo",
      "secIntro": "Que vous soyez débutant ou sportif régulier, chaque séance est adaptée à votre forme du jour. Entre les rendez-vous, vous gardez un programme clair et des conseils pour progresser au quotidien, à votre rythme.",
      "f1h": "À domicile à Waterloo",
      "f1p": "Je me déplace chez vous à Waterloo avec le matériel nécessaire. Vous vous entraînez dans un cadre familier, à l'horaire qui vous arrange.",
      "f2h": "Coaching en visio",
      "f2p": "Depuis Waterloo ou en déplacement, suivez vos séances en visioconférence, avec un programme mis à jour et des corrections en temps réel.",
      "f3h": "Programme & nutrition sur-mesure",
      "f3p": "Un plan adapté à votre niveau et vos objectifs, avec des repères nutrition simples et concrets — sans régime extrême.",
      "ctaH2": "Prêt à vous (re)mettre au sport à Waterloo ?",
      "ctaP": "Première séance d'essai offerte, sans engagement. À domicile ou en visio, on commence quand vous voulez.",
      "btnContact": "Me contacter"
    },
    "beersel": {
      "metaTitle": "Coach sportif à Beersel | à domicile & visio — CoachTanguy",
      "metaDesc": "Coach sportif à Beersel (Alsemberg, Huizingen, Lot) : séances à domicile ou en visioconférence, programme et nutrition sur-mesure. 1ère séance offerte.",
      "heroEyebrow": "Coaching sportif · Beersel",
      "h1": "Coach sportif à Beersel",
      "heroLead": "Coaching sportif personnalisé à Beersel et ses villages (Alsemberg, Huizingen, Lot), à domicile ou par visioconférence. Un accompagnement professionnel et progressif pour atteindre vos objectifs, sans la contrainte de la salle de sport.",
      "btnEssai": "Séance d'essai offerte",
      "btnVisio": "Voir le coaching visio",
      "secEyebrow": "À Beersel et alentours",
      "h2": "Du sport encadré, près de chez vous à Beersel",
      "secIntro": "Le coaching à domicile vous fait gagner du temps et garde la motivation au plus haut. La visio permet de tenir le rythme même les semaines chargées ou en déplacement — c'est la régularité qui fait les résultats.",
      "f1h": "À domicile à Beersel",
      "f1p": "Je me déplace chez vous à Beersel avec le matériel nécessaire. Vous vous entraînez dans un cadre familier, à l'horaire qui vous arrange.",
      "f2h": "Coaching en visio",
      "f2p": "Depuis Beersel ou en déplacement, suivez vos séances en visioconférence, avec un programme mis à jour et des corrections en temps réel.",
      "f3h": "Programme & nutrition sur-mesure",
      "f3p": "Un plan adapté à votre niveau et vos objectifs, avec des repères nutrition simples et concrets — sans régime extrême.",
      "ctaH2": "Prêt à vous (re)mettre au sport à Beersel ?",
      "ctaP": "Première séance d'essai offerte, sans engagement. À domicile ou en visio, on commence quand vous voulez.",
      "btnContact": "Me contacter"
    },
    "linkebeek": {
      "metaTitle": "Coach sportif à Linkebeek & Holleken | à domicile & visio — CoachTanguy",
      "metaDesc": "Coach sportif à Linkebeek et au Holleken : coaching à domicile ou en visio, programme sur-mesure, conseils nutrition. Coach diplômé, 1ère séance offerte.",
      "heroEyebrow": "Coaching sportif · Linkebeek",
      "h1": "Coach sportif à Linkebeek",
      "heroLead": "Coach sportif pour les habitants de Linkebeek et du Holleken, juste à côté de Rhode-Saint-Genèse. Séances à domicile ou en visio, programme sur-mesure, conseils nutrition et suivi régulier pour des résultats durables.",
      "btnEssai": "Séance d'essai offerte",
      "btnVisio": "Voir le coaching visio",
      "secEyebrow": "À Linkebeek et alentours",
      "h2": "Coaching de proximité à Linkebeek",
      "secIntro": "Grâce à la proximité avec Rhode-Saint-Genèse, les séances à domicile sont faciles à organiser. La visio reste disponible pour ne jamais casser la régularité, la vraie clé des progrès sur le long terme.",
      "f1h": "À domicile à Linkebeek",
      "f1p": "Je me déplace chez vous à Linkebeek avec le matériel nécessaire. Vous vous entraînez dans un cadre familier, à l'horaire qui vous arrange.",
      "f2h": "Coaching en visio",
      "f2p": "Depuis Linkebeek ou en déplacement, suivez vos séances en visioconférence, avec un programme mis à jour et des corrections en temps réel.",
      "f3h": "Programme & nutrition sur-mesure",
      "f3p": "Un plan adapté à votre niveau et vos objectifs, avec des repères nutrition simples et concrets — sans régime extrême.",
      "ctaH2": "Prêt à vous (re)mettre au sport à Linkebeek ?",
      "ctaP": "Première séance d'essai offerte, sans engagement. À domicile ou en visio, on commence quand vous voulez.",
      "btnContact": "Me contacter"
    },
    "braine": {
      "metaTitle": "Coach sportif à Braine-l'Alleud | à domicile & visio — CoachTanguy",
      "metaDesc": "Coach sportif à Braine-l'Alleud : séances à domicile ou en visio, encadrées par un coach diplômé. Remise en forme, préparation physique. 1ère séance offerte.",
      "heroEyebrow": "Coaching sportif · Braine-l'Alleud",
      "h1": "Coach sportif à Braine-l'Alleud",
      "heroLead": "Coaching sportif à Braine-l'Alleud : des séances encadrées par un coach diplômé, à domicile ou en visioconférence. De la simple remise en forme à la préparation physique, je vous guide étape par étape, en toute sécurité.",
      "btnEssai": "Séance d'essai offerte",
      "btnVisio": "Voir le coaching visio",
      "secEyebrow": "À Braine-l'Alleud et alentours",
      "h2": "Reprenez le sport sereinement à Braine-l'Alleud",
      "secIntro": "On avance par étapes, avec des objectifs réalistes et un suivi régulier. L'idée n'est pas de tout révolutionner d'un coup, mais d'installer des habitudes qui tiennent dans le temps.",
      "f1h": "À domicile à Braine-l'Alleud",
      "f1p": "Je me déplace chez vous à Braine-l'Alleud avec le matériel nécessaire. Vous vous entraînez dans un cadre familier, à l'horaire qui vous arrange.",
      "f2h": "Coaching en visio",
      "f2p": "Depuis Braine-l'Alleud ou en déplacement, suivez vos séances en visioconférence, avec un programme mis à jour et des corrections en temps réel.",
      "f3h": "Programme & nutrition sur-mesure",
      "f3p": "Un plan adapté à votre niveau et vos objectifs, avec des repères nutrition simples et concrets — sans régime extrême.",
      "ctaH2": "Prêt à vous (re)mettre au sport à Braine-l'Alleud ?",
      "ctaP": "Première séance d'essai offerte, sans engagement. À domicile ou en visio, on commence quand vous voulez.",
      "btnContact": "Me contacter"
    }
  },
  "legal": {
    "mentions": {
      "title": "Mentions légales — CoachTanguy",
      "desc": "Mentions légales du site CoachTanguy.",
      "body": "<span class=\"eyebrow\">Informations légales</span>\n      <h1>Mentions légales</h1>\n      <p class=\"legal__update\">Dernière mise à jour : juin 2026</p>\n\n      <h2>1. Éditeur du site</h2>\n      <p>Le site <strong>coachtanguy.com</strong> est édité par Tanguy Witters, coach sportif indépendant.</p>\n      <ul>\n        <li>Adresse : Avenue de la Pépinière 11, 1640 Rhode-Saint-Genèse, Belgique</li>\n        <li>Numéro d'entreprise / TVA : BE1026048974</li>\n        <li>Email : tanguy_coaching@hotmail.com</li>\n      </ul>\n\n      <h2>2. Hébergement</h2>\n      <p>Le site est hébergé par Netlify, Inc., 512 2nd Street, Suite 200, San Francisco, CA 94107, États-Unis.</p>\n\n      <h2>3. Propriété intellectuelle</h2>\n      <p>L'ensemble des contenus présents sur ce site (textes, images, logo, éléments graphiques) est la propriété de CoachTanguy, sauf mention contraire. Toute reproduction, représentation ou diffusion, totale ou partielle, sans autorisation écrite préalable est interdite.</p>\n\n      <h2>4. Données personnelles</h2>\n      <p>Les informations collectées via le formulaire de contact sont utilisées uniquement pour répondre à vos demandes. Conformément au RGPD, vous disposez d'un droit d'accès, de rectification et de suppression de vos données en écrivant à tanguy_coaching@hotmail.com.</p>\n\n      <h2>5. Cookies</h2>\n      <p>Ce site peut utiliser des cookies à des fins de mesure d'audience et d'amélioration de l'expérience utilisateur. Vous pouvez configurer votre navigateur pour les refuser.</p>\n\n      <h2>6. Responsabilité</h2>\n      <p>Les conseils et programmes proposés ne se substituent pas à un avis médical. Il est recommandé de consulter un médecin avant de débuter toute activité physique.</p>\n\n      <p class=\"legal__back\"><a href=\"index.html\">← Retour à l'accueil</a></p>"
    },
    "cvg": {
      "title": "Conditions générales de vente — CoachTanguy",
      "desc": "Conditions générales de vente des prestations CoachTanguy.",
      "body": "<span class=\"eyebrow\">Conditions</span>\n      <h1>Conditions générales de vente</h1>\n      <p class=\"legal__update\">Dernière mise à jour : juin 2026</p>\n\n      <h2>1. Objet</h2>\n      <p>Les présentes conditions régissent la vente des prestations de coaching sportif proposées par CoachTanguy : séances de coaching visio et formules de suivi en ligne.</p>\n\n      <h2>2. Prix et paiement</h2>\n      <p>Les prix sont indiqués en euros, toutes taxes comprises. Le paiement s'effectue en ligne de manière sécurisée via Stripe (Visa, Mastercard, PayPal, Apple Pay, Google Pay…). Le paiement en plusieurs fois est possible via Klarna.</p>\n\n      <h2>3. Packs et validité</h2>\n      <ul>\n        <li>Pack 4 séances : valable 5 semaines à compter de la date d'achat.</li>\n        <li>Pack 8 séances : valable 10 semaines à compter de la date d'achat.</li>\n        <li>Les séances non utilisées à l'expiration du pack sont perdues.</li>\n      </ul>\n\n      <h2>4. Réservation, annulation et report</h2>\n      <p>Les séances sont réservées via le lien de calendrier transmis. Une séance peut être annulée ou reportée tant que le pack est valide. En cas de vacances, le pack ou le suivi peut être mis en pause et reprend au retour.</p>\n\n      <h2>5. Droit de rétractation</h2>\n      <p>Conformément à la législation en vigueur, vous disposez d'un délai légal de rétractation. Ce délai ne s'applique plus dès lors que la prestation a commencé avec votre accord.</p>\n\n      <h2>6. Santé et responsabilité</h2>\n      <p>Les programmes proposés ne remplacent pas un avis médical. Le client déclare être apte à la pratique sportive. CoachTanguy ne saurait être tenu responsable d'une utilisation inadaptée des programmes.</p>\n\n      <h2>7. Contact</h2>\n      <p>Pour toute question relative aux présentes conditions : tanguy_coaching@hotmail.com.</p>\n\n      <p class=\"legal__back\"><a href=\"index.html\">← Retour à l'accueil</a></p>"
    }
  },
  "confirm": {
    "title": "Message envoyé — CoachTanguy",
    "desc": "Votre message a bien été envoyé à CoachTanguy.",
    "h1": "Message bien envoyé !",
    "text": "Merci pour votre message. Je reviens vers vous très rapidement, généralement dans la journée. À très vite pour votre première séance offerte !"
  }
};
(window.SITE_CONTENT_ALL = window.SITE_CONTENT_ALL || {}).fr = window.SITE_CONTENT;
