/* ===========================================================
   CONTENU FRANÇAIS — CoachTanguy
   Édité via dashboard.html. Ne pas casser la structure des clés.
   =========================================================== */
window.SITE_CONTENT = {
  "nav": {
    "suivis": "Services",
    "avis": "Avis",
    "accueil": "Accueil",
    "calculateur": "Calculateur",
    "faq": "FAQ",
    "contact": "Contact",
    "cta": "Réserver un appel",
    "collab": "Collaboration"
  },
  "calc": {
    "eyebrow": "Outil gratuit",
    "title": "Calculateur alimentaire.",
    "subtitle": "Estimez vos besoins caloriques et la répartition de vos macros en quelques secondes, selon votre profil et vos objectifs."
  },
  "home": {
    "hero": {
      "eyebrow": "Coach sportif diplômé",
      "titleHtml": "Le sport facile,<br />partout et à tout moment.",
      "subtitle": "Coaching visio et suivi en ligne, adapté à votre niveau, vos objectifs et votre emploi du temps.",
      "ctaPrimary": "Coaching visio",
      "ctaSecondary": "Suivi en ligne",
      "pill1": "✓ Visioconférence",
      "pill2": "✓ Plans personnalisés",
      "pill3": "✓ Sans engagement"
    },
    "trust": {
      "v1": "500+",
      "l1": "heures de formation",
      "v2": "100%",
      "l2": "personnalisé",
      "v3": "7j/7",
      "l3": "accompagnement",
      "v4": "1ère",
      "l4": "séance offerte"
    },
    "services": {
      "eyebrow": "Services",
      "title": "Un accompagnement à votre rythme.",
      "subtitle": "Deux formules pensées pour vous faire progresser, où que vous soyez.",
      "c1Title": "Coaching visio",
      "c1Text": "Profitez d'un accompagnement professionnel à distance via visioconférence, pour garder la motivation partout où vous êtes.",
      "c1Link": "Découvrir l'offre",
      "c2Title": "Suivi en ligne",
      "c2Text": "Accédez à un suivi, des plans d'entraînement et conseils personnalisés via une application.",
      "c2Link": "Découvrir l'offre"
    },
    "process": {
      "eyebrow": "Comment ça marche",
      "title": "Avec le coaching visio ou le suivi en ligne, progressez simplement en 3 étapes.\n",
      "s1Title": "Échange découverte",
      "s1Text": "Un premier appel offert pour comprendre vos besoins, vos objectifs et tester la méthode ensemble.",
      "s2Title": "Plan sur-mesure",
      "s2Text": "Je construis un programme adapté à votre niveau, votre emploi du temps et votre matériel.",
      "s3Title": "Suivi & résultats",
      "s3Text": "On avance ensemble : séances, ajustements réguliers et motivation pour des résultats durables."
    },
    "about": {
      "eyebrow": "À propos",
      "title": "Tanguy, votre coach sportif.",
      "p1": "Diplômé d'un Bachelier en Coaching Sportif, je m'appuie sur de solides connaissances en anatomie, physiologie, nutrition et science de l'entraînement pour vous accompagner en toute sécurité.",
      "p2": "J'ai travaillé avec des profils variés, des enfants aux seniors, et adapte chaque programme à vos besoins. Mon parcours, c'est plus de 500 heures de stage, 2 ans d'expérience en tant que coach personnel et plus de 10 ans de pratique personnelle de la musculation.",
      "s1v": "500+",
      "s1l": "heures de stage",
      "s2v": "2 ans",
      "s2l": "de coaching",
      "s3v": "10+ ans",
      "s3l": "de pratique",
      "cta": "Travailler avec moi"
    },
    "faq": {
      "eyebrow": "FAQ",
      "title": "Questions fréquentes.",
      "q1": "Pourquoi proposer des packs de séances ?",
      "a1": "Les packs permettent de simplifier l'organisation avec un seul paiement, tout en favorisant un engagement sur la durée. Ils aident également à rester régulier et motivé dans les séances, ce qui est essentiel pour progresser et obtenir des résultats concrets.",
      "q2": "Comment réserver une séance ?",
      "a2": "Toutes les 2 semaines, vous recevez un lien vers mon agenda électronique via WhatsApp pour réserver votre séance. Les réservations se font toutes les 2 semaines afin de garantir plus de flexibilité et de s'adapter à votre emploi du temps.",
      "q3": "Puis-je annuler ou reporter une séance ?",
      "a3": "Pas de panique, vous pouvez annuler une séance et la reporter à une autre date tant que votre pack est encore valide. Une fois la date de fin du pack dépassée, toute séance non utilisée est perdue.",
      "q4": "Quelle est la durée de validité d'un pack ?",
      "a4": "Les packs de 4 séances sont valables 5 semaines et les packs 8 séances sont valables 10 semaines à compter de la date de paiement. Cette durée permet de garantir une pratique régulière et d'optimiser les résultats. Passé ces délais, les séances non utilisées seront perdues. Le report d'une séance ne prolonge pas la durée de validité du pack.",
      "q5": "Quels moyens de paiement sont acceptés ?",
      "a5": "Les paiements peuvent être effectués par Visa, Mastercard, Revolut Pay, PayPal, Klarna, Bancontact, Apple Pay ou Google Pay. Le paiement s'effectue de manière sécurisée via Stripe.",
      "q6": "Et si je pars en vacances ?",
      "a6": "Aucun souci : votre pack ou votre suivi est simplement mis en pause et reprendra à votre retour.",
      "q7": "Puis-je payer en plusieurs fois ?",
      "a7": "Oui, le paiement via Klarna est disponible. Il peut vous permettre de payer votre pack sous 30 jours, selon votre éligibilité. Le paiement reste sécurisé et s'effectue directement via Stripe."
    },
    "cta": {
      "title": "Prêt à vous lancer ?",
      "text": "Contactez-moi pour discuter de vos objectifs et trouver la formule qui vous correspond. La première séance est offerte.",
      "button": "Contacter"
    },
    "payments": {
      "title": "Paiement sécurisé via Stripe"
    },
    "calcTeaser": {
      "eyebrow": "Outil gratuit",
      "title": "Calculez vos besoins caloriques en 2 minutes.",
      "text": "Métabolisme de base, calories cibles, répartition des macros et repères concrets pour composer vos repas : mon calculateur alimentaire gratuit vous donne une base claire pour démarrer, sans inscription.",
      "chip1": "✓ Calories & macros",
      "chip3": "✓ Idées de repas",
      "button": "Essayer le calculateur"
    }
  },
  "avis": {
    "eyebrow": "Avis Google",
    "title": "Ils me font confiance.",
    "score": "5,0",
    "count": "17 avis Google",
    "cta1": "Laisser un avis",
    "cta2": "Voir tous les avis",
    "r1Name": "Laurence Bioul",
    "r1Text": "Super coach ! Il est très à l'écoute des besoins individuels, il adapte la séance en fonction de ma condition physique et des bobos du moment (migraines, douleur aux genoux etc.). Je recommande vivement !",
    "r2Name": "Sebastien Hayot",
    "r2Text": "Tanguy nous coache à domicile depuis près de deux ans, et nous sommes entièrement satisfaits de son accompagnement. Son approche est à la fois très professionnelle, bienveillante et parfaitement adaptée à nos besoins. Toujours à l'écoute, il sait motiver sans jamais mettre de pression, tout en restant humain et attentif à nos objectifs. Nous le recommandons sans la moindre hésitation.",
    "r3Name": "Didem Sengun",
    "r3Text": "Tanguy est très sympa et est un super coach qui sait me motiver ! Il a le peps et me donne envie de faire ma séance chaque séance.",
    "r4Name": "Maxime Lebg",
    "r4Text": "Super accompagnement ! J'ai apprécié le fait d'avoir un programme clair avec les exercices, les séries, les répétitions et les vidéos. On sait exactement quoi faire à chaque séance. Tanguy est sérieux, à l'écoute et très professionnel.",
    "r5Name": "Rosalie de Crombrugghe",
    "r5Text": "Tanguy m'a coachée à domicile pendant 1,5 an jusqu'à mes 6 mois de grossesse. J'adore son professionnalisme, ses coachings toujours différents, son écoute. De plus, il s'assure toujours que les mouvements soient bien faits. J'ai hâte de reprendre les coachings avec Tanguy !",
    "r6Name": "Tanguy R",
    "r6Text": "Je recommande vraiment le suivi en ligne avec Tanguy. C'est pratique, flexible et très bien organisé. Les exercices sont bien choisis et les consignes sont claires, ce qui permet de progresser sans devoir réfléchir à quoi faire.",
    "r7Name": "Caro Delvaux",
    "r7Text": "Super coach à domicile ! À l'écoute, professionnel, ponctuel, passionné. Adapte ses séances à l'évolution.",
    "r8Name": "Maggss115",
    "r8Text": "Tanguy est un coach très attentif et très à l'écoute. Il adapte le contenu des séances selon les besoins spécifiques du client et son niveau de fitness et le résultat est efficace, agréable et rapidement visible. Je le recommande vivement à quiconque veut se reprendre en main ou simplement rester en forme physique optimale.",
    "r9Name": "anne reynens",
    "r9Text": "Voilà 18 mois que Tanguy me suit. Il travaille mon physique et mon mental. Je le recommande.",
    "r10Name": "Laurence Henin",
    "r10Text": "Je recommande vivement le coach Tanguy. Jeune, dynamique et très professionnel, il sait parfaitement s'adapter aux besoins et aux objectifs de chacun. Son accompagnement est personnalisé, motivant et toujours réalisé avec bienveillance.",
    "r11Name": "Julien Rizk",
    "r11Text": "Très bon suivi en ligne. Le programme est clair, bien structuré et facile à suivre même quand on n'a pas énormément de temps. Tanguy est disponible, répond rapidement aux questions et adapte si besoin. Je recommande sans hésiter.",
    "r12Name": "Sonia B-Lila",
    "r12Text": "Je ne peux que conseiller Tanguy comme coach. Professionnel, à l'écoute, il sait adapter les entraînements en fonction des limites, points faibles et forts de chacun. Motivant, on se sent bien après ses séances malgré les challenges !",
    "r13Name": "Romain V.",
    "r13Text": "Très satisfait du suivi. Le programme était adapté à mes objectifs et à mon emploi du temps. J'ai surtout aimé le côté progressif, on ne se sent pas perdu et on voit qu'il y a une vraie logique derrière les séances.",
    "r14Name": "Estelle Bruyninckx",
    "r14Text": "Très satisfaite de mon suivi en ligne avec Tanguy. Le programme est clair, bien adapté à mon niveau et facile à suivre via l'application. L'accompagnement sur WhatsApp est un vrai plus : dès que j'ai une question sur un exercice, Tanguy me répond assez vite. Je recommande !"
  },
  "footer": {
    "tagline": "Le sport facile, partout et à tout moment.",
    "areas": "Coach sportif à Rhode-Saint-Genèse, Uccle, Waterloo, Beersel, Linkebeek et Braine-l'Alleud, à domicile ou en visio.",
    "lVisio": "Coaching visio",
    "lSuivi": "Suivi en ligne",
    "lFaq": "FAQ",
    "lContact": "Contact",
    "lMentions": "Mentions légales",
    "lCgv": "CGV",
    "copyright": "© 2026 CoachTanguy. Tous droits réservés.",
    "lPrivacy": "Confidentialité",
    "lCookies": "Cookies",
    "lCollab": "Kiné partenaire"
  },
  "contact": {
    "eyebrow": "Contact",
    "title": "Contactez Tanguy.",
    "subtitle": "Une question ? Envie de commencer ? Écrivez-moi, je vous réponds rapidement.",
    "asideTitle": "Une question ?",
    "asideText": "Le plus simple et le plus rapide : un message direct sur WhatsApp.",
    "waLabel": "WhatsApp",
    "waSub": "+32 472 76 16 39",
    "emailLabel": "Email",
    "emailSub": "contact@coachtanguy.com",
    "note": "✓ Première séance d'essai offerte",
    "formTitle": "Message rapide",
    "fName": "Nom",
    "phName": "Votre nom",
    "fEmail": "Email",
    "phEmail": "vous@email.com",
    "fSubject": "Sujet",
    "optVisio": "Coaching visio",
    "optSuivi": "Suivi en ligne",
    "optEssai": "Séance d'essai offerte",
    "optAutre": "Autre question",
    "fMessage": "Message",
    "phMessage": "Parlez-moi de vos objectifs...",
    "submit": "Envoyer le message",
    "consent": "En envoyant ce message, vous serez recontacté par Tanguy dans la journée.",
    "privacyText": "Vos données (nom, e-mail, message) servent uniquement à traiter votre demande.",
    "privacyLink": "Politique de confidentialité"
  },
  "visio": {
    "heroEyebrow": "Coaching Visio",
    "heroTitleHtml": "Flexible, interactif,<br />efficace.",
    "heroSubtitle": "Profitez de séances individuelles de coaching sportif à distance, accessibles partout. Coaching personnalisé, conseils en temps réel et suivi sur-mesure par visioconférence.",
    "heroCta1": "Aller directement aux packs",
    "heroCta2": "Séance d'essai offerte",
    "f1Title": "Coaching sur-mesure",
    "f1Text": "Des séances adaptées à votre rythme, vos objectifs et votre espace, où que vous soyez.",
    "f2Title": "Packs de séances",
    "f2Text": "Des packs conçus selon votre fréquence d'entraînement pour garantir une vraie régularité.",
    "f3Title": "Séance d'essai offerte",
    "f3Text": "Un premier échange pour découvrir vos besoins, tester la méthode et définir ensemble vos objectifs.",
    "packsEyebrow": "Packs",
    "packsTitle": "Choisissez la formule qui vous convient.",
    "packsSubtitle": "Adaptée et personnalisée · feedback après chaque séance · report possible en cas de vacances.",
    "p1Name": "Séance à l'unité",
    "p1Price": "35€",
    "p1Meta": "Séance de 30 à 40 min",
    "p1l1": "Séance adaptée et personnalisée",
    "p1l2": "Feedback après la séance",
    "p1l3": "Sans engagement",
    "p1Note": "💳 Paiement lors de la réservation",
    "p1lCalc": "Calculateur alimentaire personnalisé",
    "p1Btn": "Réserver",
    "p2Ribbon": "Le plus choisi",
    "p2Name": "Pack 4 séances",
    "p2Price": "120€",
    "p2PriceSub": "soit 30€ / séance",
    "p2Meta": "1 séance par semaine",
    "p2l1": "Valable 5 semaines",
    "p2l2": "4 séances personnalisées",
    "p2l3": "Feedback après chaque séance",
    "p2l4": "Report possible en cas de vacances",
    "p2lCalc": "Calculateur alimentaire personnalisé",
    "p2Btn": "Choisir",
    "p3Name": "Pack 8 séances",
    "p3Price": "200€",
    "p3PriceSub": "soit 25€ / séance",
    "p3Meta": "2+ séances par semaine",
    "p3l1": "Valable 5 semaines",
    "p3l2": "8 séances personnalisées",
    "p3l3": "Feedback après chaque séance",
    "p3l4": "Report possible en cas de vacances",
    "p3lCalc": "Calculateur alimentaire personnalisé",
    "p3Btn": "Choisir",
    "ctaTitle": "Prêt à commencer ?",
    "ctaText": "Réservez votre séance d'essai offerte et lançons-nous ensemble.",
    "ctaBtn": "Contacter"
  },
  "suivi": {
    "heroEyebrow": "Suivi en Ligne",
    "heroTitleHtml": "Coaching sportif<br />à distance.",
    "heroSubtitle": "Un suivi à votre rythme, 100% personnalisé, où que vous soyez via l'application FitPros. Programme évolutif, conseils réguliers et accompagnement sur-mesure pour progresser efficacement.",
    "heroCta1": "Aller directement aux suivis",
    "heroCta2": "Poser une question",
    "appEyebrow": "FitPros",
    "appTitle": "Votre programme sur mesure dans votre poche.",
    "appText": "Un espace simple pour suivre votre progression et rester motivé au quotidien.",
    "appB1Title": "Un espace simple pour suivre votre progression.",
    "appB1Text": "Depuis l'application, vous retrouvez facilement vos entraînements en cours, votre progression de la semaine et les prochaines séances prévues. Tout est centralisé pour garder une vision claire de votre suivi et rester régulier dans votre pratique.",
    "appB2Title": "Des séances guidées étape par étape.",
    "appB2Text": "Chaque séance est organisée de manière claire avec les exercices, les séries, les répétitions, les consignes associées et les vidéos d'exécution. Vous pouvez lancer votre entraînement directement depuis l'application et suivre le programme à votre rythme, en toute autonomie.",
    "appT1": "Des séances guidées étape par étape",
    "appT2": "Suivi clair de votre progression",
    "appT3": "Conseils et ajustements réguliers",
    "appT4": "Communication directe via WhatsApp",
    "appBtn": "Voir les formules",
    "suivisEyebrow": "Suivis",
    "suivisTitle": "Un suivi expert, 100% personnalisé.",
    "suivisSubtitle": "Programme sur-mesure, ajustements réguliers et accompagnement humain.",
    "flowLabel": "puis",
    "s1Ribbon": "Pour démarrer",
    "s1Name": "Accompagnement initial",
    "s1Price": "299€",
    "s1PriceSub": "pour 8 semaines",
    "s1l1": "Accompagnement personnalisé pendant 8 semaines",
    "s1l2": "Programme d'entraînement sur-mesure adapté à vos objectifs",
    "s1l3": "Accès via l'app FitPros",
    "s1l4": "Communication & suivi via WhatsApp",
    "s1l5": "Appel visio d'introduction (~30 min) offert",
    "s1l6": "Programme accessible sous 72h après l'appel",
    "s1l8": "Ajustements réguliers pour des résultats optimaux",
    "s1l9": "Mise en pause possible en cas de vacances",
    "s1lCalc": "Calculateur alimentaire personnalisé",
    "s1Btn": "Choisir",
    "s2Name": "Suivi mensuel",
    "s2Price": "139€",
    "s2PriceSub": "toutes les 4 semaines",
    "s2Meta": "Uniquement après l'accompagnement initial",
    "s2l1": "Programme d'entraînement sur-mesure",
    "s2l2": "Accès via l'app FitPros",
    "s2l3": "Communication & suivi via WhatsApp",
    "s2l5": "Ajustements réguliers",
    "s2l6": "Mise en pause possible en cas de vacances",
    "s2lCalc": "Calculateur alimentaire personnalisé",
    "s2Btn": "Choisir",
    "ctaTitle": "Prêt à progresser ?",
    "ctaText": "Réservez votre appel d'introduction offert et construisons votre programme.",
    "ctaBtn": "Contacter"
  },
  "stripe": {
    "unite": "contact.html",
    "pack4": "https://buy.stripe.com/4gM28tezF9v53Pkb1m0RG0h",
    "pack8": "https://buy.stripe.com/dRmbJ3639cHh1Hc1qM0RG0i",
    "initial": "https://buy.stripe.com/6oU3cx9fl6iTadIb1m0RG0c",
    "mensuel": "https://buy.stripe.com/6oU14p77d4aLadIglG0RG0g"
  },
  "meta": {
    "index": {
      "title": "Coach sportif à Rhode-Saint-Genèse & Brabant — CoachTanguy",
      "desc": "Coach sportif à Rhode-Saint-Genèse : coaching à domicile, en visio et suivi en ligne. Aussi à Waterloo, Beersel, Linkebeek et Braine-l'Alleud. 1ère séance offerte."
    },
    "visio": {
      "title": "Coaching Visio — CoachTanguy",
      "desc": "Coaching sportif individuel à distance par visioconférence. Flexible, interactif et efficace. Première séance d'essai offerte."
    },
    "suivi": {
      "title": "Suivi en Ligne — CoachTanguy",
      "desc": "Suivi sportif 100% personnalisé via l'application FitPros : programme évolutif, conseils réguliers et accompagnement sur-mesure pour progresser efficacement."
    },
    "contact": {
      "title": "Contact — CoachTanguy",
      "desc": "Une question ? Contactez CoachTanguy via WhatsApp ou par message. Première séance d'essai offerte."
    },
    "calc": {
      "title": "Calculateur alimentaire — CoachTanguy",
      "desc": "Calculateur alimentaire gratuit : estimez vos besoins caloriques et la répartition de vos macros (protéines, glucides, lipides) selon votre profil et vos objectifs."
    }
  },
  "local": {
    "rhode": {
      "metaTitle": "Coach sportif à Rhode-Saint-Genèse | à domicile & visio — CoachTanguy",
      "metaDesc": "Coach sportif à Rhode-Saint-Genèse : séances à domicile ou en visio, programme et nutrition sur-mesure. Coach diplômé, 1ère séance offerte.",
      "heroEyebrow": "Coaching sportif · Rhode-Saint-Genèse",
      "h1": "Coach sportif à Rhode-Saint-Genèse",
      "heroLead": "Basé à Rhode-Saint-Genèse, je propose un coaching sportif sur-mesure directement chez vous ou en visioconférence. Du centre aux quartiers proches de la Forêt de Soignes, je m'adapte à votre niveau, vos objectifs et votre emploi du temps, que vous soyez débutant ou déjà sportif.",
      "btnEssai": "Séance d'essai offerte",
      "btnVisio": "Voir le coaching visio",
      "secEyebrow": "À Rhode-Saint-Genèse et alentours",
      "h2": "Votre coach sportif à domicile et en visio à Rhode-Saint-Genèse",
      "secIntro": "Pas besoin de salle ni de longs trajets : je viens chez vous, ou nous travaillons en visio avec un programme suivi entre les séances. Idéal si vous manquez de temps ou préférez un cadre privé et personnalisé.",
      "f1h": "À domicile à Rhode-Saint-Genèse",
      "f1p": "Je me déplace chez vous à Rhode-Saint-Genèse avec le matériel nécessaire. Vous vous entraînez dans un cadre familier, à l'horaire qui vous arrange.",
      "f2h": "Coaching en visio",
      "f2p": "Depuis Rhode-Saint-Genèse ou en déplacement, suivez vos séances en visioconférence, avec un programme mis à jour et des corrections en temps réel.",
      "f3h": "Programme & nutrition sur-mesure",
      "f3p": "Un plan adapté à votre niveau et vos objectifs, avec des repères nutrition simples et concrets, sans régime extrême.",
      "ctaH2": "Prêt à vous (re)mettre au sport à Rhode-Saint-Genèse ?",
      "ctaP": "Première séance d'essai offerte, sans engagement. À domicile ou en visio, on commence quand vous voulez.",
      "btnContact": "Me contacter"
    },
    "uccle": {
      "metaTitle": "Coach sportif à Uccle | à domicile & visio — CoachTanguy",
      "metaDesc": "Coach sportif à Uccle : séances à domicile ou en visio, programme et nutrition sur-mesure. Coach diplômé, 1ère séance offerte.",
      "heroEyebrow": "Coaching sportif · Uccle",
      "h1": "Coach sportif à Uccle",
      "heroLead": "Juste au nord de Rhode-Saint-Genèse, j'accompagne les habitants d'Uccle avec un coaching sportif personnalisé, à domicile ou en visioconférence. Du Fort-Jaco au Vivier d'Oie, je m'adapte à votre niveau, vos objectifs et votre emploi du temps.",
      "btnEssai": "Séance d'essai offerte",
      "btnVisio": "Voir le coaching visio",
      "secEyebrow": "À Uccle et alentours",
      "h2": "Votre coach sportif à domicile et en visio à Uccle",
      "secIntro": "Pas besoin de salle bondée : je viens chez vous, ou nous travaillons en visio avec un programme suivi entre les séances. Pratique pour les agendas chargés et les quartiers résidentiels d'Uccle.",
      "f1h": "À domicile à Uccle",
      "f1p": "Je me déplace chez vous à Uccle avec le matériel nécessaire. Vous vous entraînez dans un cadre familier, à l'horaire qui vous arrange.",
      "f2h": "Coaching en visio",
      "f2p": "Depuis Uccle ou en déplacement, suivez vos séances en visioconférence, avec un programme mis à jour et des corrections en temps réel.",
      "f3h": "Programme & nutrition sur-mesure",
      "f3p": "Un plan adapté à votre niveau et vos objectifs, avec des repères nutrition simples et concrets, sans régime extrême.",
      "ctaH2": "Prêt à vous (re)mettre au sport à Uccle ?",
      "ctaP": "Première séance d'essai offerte, sans engagement. À domicile ou en visio, on commence quand vous voulez.",
      "btnContact": "Me contacter"
    },
    "waterloo": {
      "metaTitle": "Coach sportif à Waterloo | à domicile & visio — CoachTanguy",
      "metaDesc": "Coach sportif à Waterloo : coaching personnalisé à domicile ou en visio, perte de poids, remise en forme, prise de muscle. 1ère séance offerte.",
      "heroEyebrow": "Coaching sportif · Waterloo",
      "h1": "Coach sportif à Waterloo",
      "heroLead": "À quelques minutes de Rhode-Saint-Genèse, j'accompagne les habitants de Waterloo avec un coaching sportif personnalisé, à domicile ou en visio. Perte de poids, remise en forme, prise de muscle ou préparation physique : on bâtit ensemble un programme réaliste et progressif.",
      "btnEssai": "Séance d'essai offerte",
      "btnVisio": "Voir le coaching visio",
      "secEyebrow": "À Waterloo et alentours",
      "h2": "Un coaching sportif sur-mesure à Waterloo",
      "secIntro": "Que vous soyez débutant ou sportif régulier, chaque séance est adaptée à votre forme du jour. Entre les rendez-vous, vous gardez un programme clair et des conseils pour progresser au quotidien, à votre rythme.",
      "f1h": "À domicile à Waterloo",
      "f1p": "Je me déplace chez vous à Waterloo avec le matériel nécessaire. Vous vous entraînez dans un cadre familier, à l'horaire qui vous arrange.",
      "f2h": "Coaching en visio",
      "f2p": "Depuis Waterloo ou en déplacement, suivez vos séances en visioconférence, avec un programme mis à jour et des corrections en temps réel.",
      "f3h": "Programme & nutrition sur-mesure",
      "f3p": "Un plan adapté à votre niveau et vos objectifs, avec des repères nutrition simples et concrets, sans régime extrême.",
      "ctaH2": "Prêt à vous (re)mettre au sport à Waterloo ?",
      "ctaP": "Première séance d'essai offerte, sans engagement. À domicile ou en visio, on commence quand vous voulez.",
      "btnContact": "Me contacter"
    },
    "beersel": {
      "metaTitle": "Coach sportif à Beersel | à domicile & visio — CoachTanguy",
      "metaDesc": "Coach sportif à Beersel (Alsemberg, Huizingen, Lot) : séances à domicile ou en visioconférence, programme et nutrition sur-mesure. 1ère séance offerte.",
      "heroEyebrow": "Coaching sportif · Beersel",
      "h1": "Coach sportif à Beersel",
      "heroLead": "Coaching sportif personnalisé à Beersel et ses villages (Alsemberg, Huizingen, Lot), à domicile ou par visioconférence. Un accompagnement professionnel et progressif pour atteindre vos objectifs, sans la contrainte de la salle de sport.",
      "btnEssai": "Séance d'essai offerte",
      "btnVisio": "Voir le coaching visio",
      "secEyebrow": "À Beersel et alentours",
      "h2": "Du sport encadré, près de chez vous à Beersel",
      "secIntro": "Le coaching à domicile vous fait gagner du temps et garde la motivation au plus haut. La visio permet de tenir le rythme même les semaines chargées ou en déplacement, c'est la régularité qui fait les résultats.",
      "f1h": "À domicile à Beersel",
      "f1p": "Je me déplace chez vous à Beersel avec le matériel nécessaire. Vous vous entraînez dans un cadre familier, à l'horaire qui vous arrange.",
      "f2h": "Coaching en visio",
      "f2p": "Depuis Beersel ou en déplacement, suivez vos séances en visioconférence, avec un programme mis à jour et des corrections en temps réel.",
      "f3h": "Programme & nutrition sur-mesure",
      "f3p": "Un plan adapté à votre niveau et vos objectifs, avec des repères nutrition simples et concrets, sans régime extrême.",
      "ctaH2": "Prêt à vous (re)mettre au sport à Beersel ?",
      "ctaP": "Première séance d'essai offerte, sans engagement. À domicile ou en visio, on commence quand vous voulez.",
      "btnContact": "Me contacter"
    },
    "linkebeek": {
      "metaTitle": "Coach sportif à Linkebeek & Holleken | à domicile & visio — CoachTanguy",
      "metaDesc": "Coach sportif à Linkebeek et au Holleken : coaching à domicile ou en visio, programme sur-mesure, conseils nutrition. Coach diplômé, 1ère séance offerte.",
      "heroEyebrow": "Coaching sportif · Linkebeek",
      "h1": "Coach sportif à Linkebeek",
      "heroLead": "Coach sportif pour les habitants de Linkebeek et du Holleken, juste à côté de Rhode-Saint-Genèse. Séances à domicile ou en visio, programme sur-mesure, conseils nutrition et suivi régulier pour des résultats durables.",
      "btnEssai": "Séance d'essai offerte",
      "btnVisio": "Voir le coaching visio",
      "secEyebrow": "À Linkebeek et alentours",
      "h2": "Coaching de proximité à Linkebeek",
      "secIntro": "Grâce à la proximité avec Rhode-Saint-Genèse, les séances à domicile sont faciles à organiser. La visio reste disponible pour ne jamais casser la régularité, la vraie clé des progrès sur le long terme.",
      "f1h": "À domicile à Linkebeek",
      "f1p": "Je me déplace chez vous à Linkebeek avec le matériel nécessaire. Vous vous entraînez dans un cadre familier, à l'horaire qui vous arrange.",
      "f2h": "Coaching en visio",
      "f2p": "Depuis Linkebeek ou en déplacement, suivez vos séances en visioconférence, avec un programme mis à jour et des corrections en temps réel.",
      "f3h": "Programme & nutrition sur-mesure",
      "f3p": "Un plan adapté à votre niveau et vos objectifs, avec des repères nutrition simples et concrets, sans régime extrême.",
      "ctaH2": "Prêt à vous (re)mettre au sport à Linkebeek ?",
      "ctaP": "Première séance d'essai offerte, sans engagement. À domicile ou en visio, on commence quand vous voulez.",
      "btnContact": "Me contacter"
    },
    "braine": {
      "metaTitle": "Coach sportif à Braine-l'Alleud | à domicile & visio — CoachTanguy",
      "metaDesc": "Coach sportif à Braine-l'Alleud : séances à domicile ou en visio, encadrées par un coach diplômé. Remise en forme, préparation physique. 1ère séance offerte.",
      "heroEyebrow": "Coaching sportif · Braine-l'Alleud",
      "h1": "Coach sportif à Braine-l'Alleud",
      "heroLead": "Coaching sportif à Braine-l'Alleud : des séances encadrées par un coach diplômé, à domicile ou en visioconférence. De la simple remise en forme à la préparation physique, je vous guide étape par étape, en toute sécurité.",
      "btnEssai": "Séance d'essai offerte",
      "btnVisio": "Voir le coaching visio",
      "secEyebrow": "À Braine-l'Alleud et alentours",
      "h2": "Reprenez le sport sereinement à Braine-l'Alleud",
      "secIntro": "On avance par étapes, avec des objectifs réalistes et un suivi régulier. L'idée n'est pas de tout révolutionner d'un coup, mais d'installer des habitudes qui tiennent dans le temps.",
      "f1h": "À domicile à Braine-l'Alleud",
      "f1p": "Je me déplace chez vous à Braine-l'Alleud avec le matériel nécessaire. Vous vous entraînez dans un cadre familier, à l'horaire qui vous arrange.",
      "f2h": "Coaching en visio",
      "f2p": "Depuis Braine-l'Alleud ou en déplacement, suivez vos séances en visioconférence, avec un programme mis à jour et des corrections en temps réel.",
      "f3h": "Programme & nutrition sur-mesure",
      "f3p": "Un plan adapté à votre niveau et vos objectifs, avec des repères nutrition simples et concrets, sans régime extrême.",
      "ctaH2": "Prêt à vous (re)mettre au sport à Braine-l'Alleud ?",
      "ctaP": "Première séance d'essai offerte, sans engagement. À domicile ou en visio, on commence quand vous voulez.",
      "btnContact": "Me contacter"
    }
  },
  "legal": {
    "mentions": {
      "title": "Mentions légales — CoachTanguy",
      "desc": "Mentions légales du site CoachTanguy.",
      "body": "      <span class=\"eyebrow\">Informations légales</span>\n      <h1>Mentions légales</h1>\n      <p class=\"legal__update\">Dernière mise à jour : 29 juillet 2026</p>\n\n      <h2>1. Éditeur du site</h2>\n      <p>Le site <strong>coachtanguy.com</strong> est édité par :</p>\n      <ul>\n        <li>Tanguy Witters, CoachTanguy</li>\n        <li>Coach sportif indépendant exerçant en personne physique</li>\n        <li>Adresse : Avenue de la Pépinière 11, 1640 Rhode-Saint-Genèse, Belgique</li>\n        <li>Numéro d'entreprise BCE : 1026.048.974</li>\n        <li>Numéro de TVA : BE1026048974</li>\n        <li>E-mail : <a href=\"mailto:contact@coachtanguy.com\">contact@coachtanguy.com</a></li>\n        <li>Téléphone : +32 472 76 16 39</li>\n      </ul>\n      <p>Le responsable de la publication est Tanguy Witters.</p>\n\n      <h2>2. Hébergement</h2>\n      <p>Le site est hébergé par :</p>\n      <ul>\n        <li>Netlify, Inc.</li>\n        <li>101 2nd Street, San Francisco, CA 94105, États-Unis</li>\n      </ul>\n\n      <h2>3. Propriété intellectuelle</h2>\n      <p>Sauf mention contraire, l'ensemble des éléments présents sur le site, notamment les textes, photographies, vidéos, programmes, calculateurs, illustrations, logos, éléments graphiques et structure du site, est la propriété de CoachTanguy ou est utilisé avec l'autorisation de son titulaire.</p>\n      <p>Toute reproduction, représentation, adaptation, publication, transmission ou exploitation, totale ou partielle, sans autorisation écrite préalable est interdite, sauf dans les limites autorisées par la loi.</p>\n\n      <h2>4. Informations publiées sur le site</h2>\n      <p>CoachTanguy veille à fournir des informations aussi exactes et actualisées que possible.</p>\n      <p>Les informations présentes sur le site ont une portée générale et informative. Elles ne remplacent pas un avis médical, un diagnostic, un traitement, une prise en charge kinésithérapeutique ou un suivi diététique clinique.</p>\n      <p>Les conditions applicables aux prestations de coaching visio et de suivi en ligne sont précisées dans les <a href=\"cvg.html\">Conditions générales de vente</a> accessibles sur le site.</p>\n\n      <h2>5. Responsabilité technique</h2>\n      <p>CoachTanguy met en œuvre des moyens raisonnables afin d'assurer l'accessibilité et le bon fonctionnement du site.</p>\n      <p>Il ne peut toutefois garantir l'absence totale d'erreur, d'interruption, de panne, de virus ou de problème résultant du réseau internet, du navigateur utilisé ou d'un service fourni par un prestataire externe.</p>\n      <p>CoachTanguy ne peut être tenu responsable d'un dommage résultant d'une utilisation du site contraire aux présentes mentions, aux consignes communiquées ou à la législation applicable.</p>\n      <p>Aucune disposition du présent article n'a pour effet d'exclure une responsabilité qui ne pourrait légalement être limitée ou exclue.</p>\n\n      <h2>6. Liens externes</h2>\n      <p>Le site peut contenir des liens vers des sites ou services exploités par des tiers, notamment Stripe, WhatsApp, FitPros ou d'autres prestataires.</p>\n      <p>CoachTanguy ne contrôle pas le contenu, la disponibilité ni les pratiques de ces services externes. L'utilisateur est invité à consulter leurs propres conditions d'utilisation et politiques de confidentialité.</p>\n\n      <h2>7. Données personnelles</h2>\n      <p>Le traitement des données personnelles collectées au moyen du site ou dans le cadre des prestations est expliqué dans la <a href=\"politique-confidentialite.html\">Politique de confidentialité</a> accessible sur le site.</p>\n      <p>Toute demande relative aux données personnelles peut être adressée à : <a href=\"mailto:contact@coachtanguy.com\">contact@coachtanguy.com</a></p>\n\n      <h2>8. Cookies et stockage local</h2>\n      <p>Les informations relatives aux cookies, aux traceurs et au stockage local utilisé par le site sont présentées dans la <a href=\"cookies.html\">Politique de cookies</a> accessible sur le site.</p>\n      <p>Le site n'utilise actuellement aucun cookie publicitaire, de réseaux sociaux ou de mesure d'audience.</p>\n\n      <h2>9. Droit applicable</h2>\n      <p>Les présentes mentions légales sont soumises au droit belge.</p>\n      <p>Toute difficulté relative au site doit être signalée en priorité à CoachTanguy à l'adresse : <a href=\"mailto:contact@coachtanguy.com\">contact@coachtanguy.com</a></p>\n      <p>Les parties chercheront, dans la mesure du possible, une solution amiable avant toute autre démarche.</p>\n\n      <p class=\"legal__back\"><a href=\"index.html\">← Retour à l'accueil</a></p>"
    },
    "cvg": {
      "title": "Conditions générales de vente — CoachTanguy",
      "desc": "Conditions générales de vente des prestations CoachTanguy.",
      "body": "      <span class=\"eyebrow\">Conditions</span>\n      <h1>Conditions générales de vente</h1>\n      <p class=\"legal__update\">Dernière mise à jour : 29 juillet 2026</p>\n\n      <h2>1. Identité du prestataire</h2>\n      <p>Les présentes Conditions générales de vente, ci-après les « CGV », sont proposées par :</p>\n      <ul>\n        <li>Tanguy Witters, CoachTanguy</li>\n        <li>Coach sportif indépendant</li>\n        <li>Adresse : Avenue de la Pépinière 11, 1640 Rhode-Saint-Genèse, Belgique</li>\n        <li>Numéro d'entreprise : 1026.048.974</li>\n        <li>Numéro de TVA : BE1026048974</li>\n        <li>E-mail : <a href=\"mailto:contact@coachtanguy.com\">contact@coachtanguy.com</a></li>\n        <li>Téléphone : +32 472 76 16 39</li>\n      </ul>\n      <p>Les présentes CGV s'appliquent aux prestations de coaching visio et de suivi sportif en ligne proposées par CoachTanguy.</p>\n\n      <h2>2. Acceptation des CGV</h2>\n      <p>Le Client reconnaît avoir pu consulter les présentes CGV avant de confirmer sa commande.</p>\n      <p>Lors du paiement via Stripe, il doit cocher une case obligatoire, non présélectionnée, contenant un lien direct vers les CGV.</p>\n      <p>La validation de cette case, suivie du paiement, matérialise l'acceptation des CGV et la conclusion du contrat entre le Client et CoachTanguy.</p>\n      <p>Les CGV applicables sont celles acceptées à la date de la commande. Le Client est invité à en conserver une copie.</p>\n\n      <h2>3. Coaching visio</h2>\n      <p>Le coaching visio consiste en des séances sportives individuelles réalisées à distance, en direct avec CoachTanguy, d'une durée habituelle de 30 à 40 minutes.</p>\n      <ul>\n        <li>Séance à l'unité : 35 €</li>\n        <li>Pack de 4 séances : 120 €, valable 5 semaines</li>\n        <li>Pack de 8 séances : 200 €, valable 5 semaines</li>\n      </ul>\n      <p>La période de validité commence à la date du paiement, sauf accord différent communiqué au Client. Les séances doivent être réservées et réalisées pendant la durée de validité du pack.</p>\n      <p>Le Client doit disposer d'une connexion internet suffisamment stable, d'un appareil équipé d'une caméra et d'un espace adapté et sécurisé pour pratiquer.</p>\n\n      <h2>4. Réservation, annulation et report</h2>\n      <p>Les séances visio sont réservées au moyen du calendrier transmis par CoachTanguy ou directement d'un commun accord.</p>\n      <p>Toute demande d'annulation ou de report doit être communiquée au minimum 24 heures avant la séance.</p>\n      <p>En cas d'annulation moins de 24 heures avant la séance ou d'absence non justifiée, la séance peut être considérée comme utilisée. Une exception peut être accordée en cas de maladie soudaine, d'accident, de force majeure ou de circonstance grave.</p>\n      <p>Lorsqu'une séance est annulée par CoachTanguy, elle est reportée sans frais.</p>\n      <p>Les séances non utilisées à l'expiration du pack sont perdues, sauf accord écrit, incapacité médicale, force majeure ou indisponibilité de CoachTanguy.</p>\n      <p>En cas de vacances annoncées et convenues à l'avance, la durée de validité du pack peut être prolongée.</p>\n\n      <h2>5. Suivi en ligne initial</h2>\n      <p>Le suivi en ligne initial est proposé au prix de 299 € pour 8 semaines. Il comprend notamment :</p>\n      <ul>\n        <li>un appel visio d'introduction ;</li>\n        <li>un programme sportif personnalisé ;</li>\n        <li>l'accès au programme sur l'application FitPros ;</li>\n        <li>les exercices, séries, répétitions, temps de repos et vidéos d'exécution ;</li>\n        <li>un accompagnement régulier via WhatsApp ;</li>\n        <li>les adaptations nécessaires du programme ;</li>\n        <li>l'accès au calculateur alimentaire personnalisé.</li>\n      </ul>\n      <p>Le programme est normalement mis à disposition dans les 72 heures suivant l'appel d'introduction et la réception de toutes les informations nécessaires.</p>\n      <p>L'accompagnement prend automatiquement fin après 8 semaines et ne fait l'objet d'aucun renouvellement automatique.</p>\n\n      <h2>6. Poursuite pendant 4 semaines</h2>\n      <p>Après le suivi initial de 8 semaines, le Client peut choisir de poursuivre son accompagnement au prix de 139 € pour 4 semaines. Cette formule comprend notamment :</p>\n      <ul>\n        <li>la poursuite du programme personnalisé sur FitPros ;</li>\n        <li>les adaptations du programme ;</li>\n        <li>l'accompagnement via WhatsApp ;</li>\n        <li>l'accès au calculateur alimentaire personnalisé.</li>\n      </ul>\n      <p>La poursuite est facultative et ne fait l'objet d'aucun renouvellement automatique. À la fin de chaque période de 4 semaines, le Client choisit manuellement de commander ou non une nouvelle période.</p>\n      <p>Chaque nouveau paiement constitue une nouvelle commande soumise aux CGV en vigueur au moment de celle-ci.</p>\n\n      <h2>7. Paiement</h2>\n      <p>Le paiement est effectué en ligne de manière sécurisée par l'intermédiaire de Stripe. Les moyens de paiement disponibles sont ceux affichés sur la page de paiement. La commande est confirmée lorsque le paiement est accepté.</p>\n      <p>CoachTanguy ne conserve pas directement les données bancaires complètes du Client.</p>\n      <p>Les prix sont indiqués en euros, toutes taxes comprises. CoachTanguy peut modifier ses tarifs pour les commandes futures. Une modification de prix n'affecte pas une prestation déjà commandée et payée.</p>\n      <p>Les promotions, réductions et codes promotionnels sont valables selon les conditions et pendant la période annoncées.</p>\n\n      <h2>8. FitPros et WhatsApp</h2>\n      <p>Les accès à FitPros et les programmes transmis sont strictement personnels. Le Client ne peut pas partager ses identifiants, transmettre son programme, copier les contenus, les publier ou les revendre. L'accès à FitPros peut prendre fin au terme de l'accompagnement.</p>\n      <p>CoachTanguy ne garantit pas l'absence totale de panne ou d'interruption provenant de FitPros, Stripe, WhatsApp ou d'un autre prestataire externe. En cas de problème technique important, une solution raisonnable est proposée au Client, notamment la transmission temporaire des informations essentielles par un autre moyen.</p>\n      <p>Le suivi WhatsApp permet au Client de poser des questions concernant son programme, ses exercices et sa progression. Il ne constitue pas une disponibilité permanente, un service médical ou un service d'urgence. CoachTanguy répond dans un délai raisonnable en fonction de ses disponibilités.</p>\n\n      <h2>9. Santé et obligations du Client</h2>\n      <p>Le Client s'engage à communiquer honnêtement les informations utiles concernant sa santé, ses douleurs, ses blessures, ses traitements et ses éventuelles contre-indications. Il doit notamment :</p>\n      <ul>\n        <li>respecter les consignes communiquées ;</li>\n        <li>utiliser du matériel adapté et en bon état ;</li>\n        <li>pratiquer dans un espace sécurisé ;</li>\n        <li>interrompre immédiatement un exercice en cas de douleur inhabituelle, de malaise ou de vertige ;</li>\n        <li>consulter un professionnel de santé en cas de doute sur son aptitude à pratiquer.</li>\n      </ul>\n      <p>Les prestations proposées sont des prestations de coaching sportif. Elles ne remplacent pas un diagnostic, un traitement médical, une séance de kinésithérapie ou un suivi diététique clinique.</p>\n      <p>CoachTanguy peut demander un avis médical ou refuser un exercice lorsqu'il estime que la situation du Client présente un risque.</p>\n\n      <h2>10. Calculateur alimentaire</h2>\n      <p>Le calculateur alimentaire fournit des estimations et des conseils généraux en fonction des informations communiquées et de l'objectif sportif du Client. Il ne constitue pas une prescription médicale ou un suivi diététique clinique.</p>\n      <p>En cas de pathologie, de grossesse, d'allaitement, d'allergie importante, de trouble du comportement alimentaire ou de traitement médical, le Client doit consulter un médecin ou un diététicien compétent.</p>\n      <p>Les résultats obtenus à l'aide du calculateur restent des estimations et peuvent différer des besoins réels du Client.</p>\n\n      <h2>11. Résultats et responsabilité</h2>\n      <p>CoachTanguy s'engage à fournir un accompagnement professionnel et adapté aux informations communiquées par le Client. Il est tenu à une obligation de moyens et ne garantit aucun résultat précis en matière de perte de poids, de prise de masse musculaire, de performance ou de transformation physique.</p>\n      <p>Les résultats dépendent notamment de l'assiduité, de l'implication, de l'alimentation, du sommeil, de la récupération et de la situation personnelle du Client.</p>\n      <p>CoachTanguy reste responsable de ses fautes professionnelles. Sa responsabilité ne peut toutefois pas être engagée lorsque le dommage résulte notamment :</p>\n      <ul>\n        <li>d'une information importante non communiquée ou incorrecte ;</li>\n        <li>du non-respect des consignes ;</li>\n        <li>d'un exercice modifié ou ajouté sans validation ;</li>\n        <li>d'un matériel défectueux ou inadapté ;</li>\n        <li>de la poursuite d'un exercice malgré une douleur ou un malaise ;</li>\n        <li>d'un problème technique indépendant de CoachTanguy.</li>\n      </ul>\n      <p>Aucune disposition des présentes CGV ne limite une responsabilité qui ne pourrait légalement être exclue.</p>\n\n      <h2>12. Droit de rétractation</h2>\n      <p>Pour une commande conclue à distance, le Client consommateur dispose en principe d'un délai de 14 jours calendrier à compter de la conclusion du contrat pour se rétracter sans devoir justifier sa décision. La demande doit être envoyée à : <a href=\"mailto:contact@coachtanguy.com\">contact@coachtanguy.com</a></p>\n      <p>Lorsque le Client demande expressément que l'accompagnement commence avant la fin des 14 jours, il conserve son droit de rétractation, mais doit payer la partie du service déjà exécutée jusqu'au moment de sa demande. Les prestations déjà exécutées peuvent notamment comprendre :</p>\n      <ul>\n        <li>l'appel initial ;</li>\n        <li>l'analyse du questionnaire ;</li>\n        <li>la création et la mise en ligne du programme ;</li>\n        <li>une séance visio déjà réalisée ;</li>\n        <li>les adaptations ou le suivi déjà fournis.</li>\n      </ul>\n      <p>Le simple commencement de l'accompagnement ne supprime pas automatiquement le droit de rétractation. La demande suivante doit être recueillie séparément lorsque le Client souhaite commencer avant la fin du délai :</p>\n      <blockquote>\n        <p>« Je demande expressément que mon accompagnement commence avant la fin du délai légal de rétractation de 14 jours. Je reconnais que les prestations déjà exécutées pourront rester dues proportionnellement si je me rétracte. »</p>\n      </blockquote>\n\n      <h2>13. Suspension, arrêt et remboursement</h2>\n      <p>Une suspension ou une prolongation peut être accordée en cas de vacances convenues à l'avance, de blessure, de maladie ou de circonstance exceptionnelle.</p>\n      <p>En dehors du droit de rétractation, aucun remboursement n'est automatiquement dû lorsque le Client :</p>\n      <ul>\n        <li>change d'avis ;</li>\n        <li>ne réalise pas son programme ;</li>\n        <li>n'utilise pas FitPros ;</li>\n        <li>ne réserve pas ses séances ;</li>\n        <li>ou cesse de répondre aux messages.</li>\n      </ul>\n      <p>Une solution proportionnée peut néanmoins être recherchée en cas d'incapacité médicale durable, de force majeure ou d'impossibilité pour CoachTanguy d'exécuter la prestation.</p>\n      <p>Toute prestation payée mais définitivement non exécutée pour une raison imputable à CoachTanguy est remboursée proportionnellement.</p>\n\n      <h2>14. Propriété intellectuelle</h2>\n      <p>Les programmes, vidéos, textes, documents, calculateurs et autres supports transmis sont protégés par les droits de propriété intellectuelle. Ils sont réservés à l'usage personnel du Client.</p>\n      <p>Il est interdit de les partager, reproduire, publier, revendre ou utiliser pour accompagner une autre personne sans l'autorisation écrite préalable de CoachTanguy.</p>\n\n      <h2>15. Données personnelles</h2>\n      <p>Les données personnelles sont traitées conformément à la <a href=\"politique-confidentialite.html\">Politique de confidentialité</a> disponible sur le site de CoachTanguy. Les données nécessaires à la commande et à l'accompagnement peuvent notamment être utilisées pour :</p>\n      <ul>\n        <li>gérer le paiement et la facturation ;</li>\n        <li>communiquer avec le Client ;</li>\n        <li>personnaliser son programme ;</li>\n        <li>organiser les séances ;</li>\n        <li>lui donner accès à FitPros.</li>\n      </ul>\n      <p>Les informations relatives aux blessures, douleurs, pathologies et traitements sont des données de santé sensibles. Leur traitement nécessite un consentement explicite distinct de l'acceptation des présentes CGV. La case suivante peut être ajoutée au questionnaire initial :</p>\n      <blockquote>\n        <p>« Je consens explicitement à ce que les informations relatives à ma santé que je communique soient utilisées uniquement afin d'adapter et de sécuriser mon accompagnement sportif. »</p>\n      </blockquote>\n      <p>Le Client peut exercer ses droits en écrivant à <a href=\"mailto:contact@coachtanguy.com\">contact@coachtanguy.com</a>.</p>\n\n      <h2>16. Réclamations et droit applicable</h2>\n      <p>Toute réclamation doit être envoyée en priorité à : <a href=\"mailto:contact@coachtanguy.com\">contact@coachtanguy.com</a>. Les parties chercheront d'abord une solution amiable.</p>\n      <p>À défaut d'accord, le Client peut s'adresser au Service de Médiation pour le Consommateur ou aux juridictions compétentes.</p>\n      <p>Les présentes CGV sont soumises au droit belge. Si une clause est déclarée nulle ou inapplicable, les autres clauses restent applicables.</p>\n      <p>CoachTanguy peut modifier les présentes CGV pour les commandes futures. La version applicable reste celle acceptée par le Client au moment de sa commande.</p>\n\n      <h2>Formulaire type de rétractation</h2>\n      <p>À utiliser uniquement si le Client souhaite exercer son droit de rétractation.</p>\n      <div class=\"legal__form\">\n        <p><strong>À l'attention de CoachTanguy, Tanguy Witters</strong><br />E-mail : <a href=\"mailto:contact@coachtanguy.com\">contact@coachtanguy.com</a></p>\n        <p>Je vous informe de ma décision de me rétracter du contrat portant sur la prestation suivante :</p>\n        <p>Prestation concernée :</p><span class=\"fill\"></span>\n        <p>Date de la commande :</p><span class=\"fill\"></span>\n        <p>Nom et prénom :</p><span class=\"fill\"></span>\n        <p>Adresse e-mail utilisée lors de la commande :</p><span class=\"fill\"></span>\n        <p>Date :</p><span class=\"fill\"></span>\n        <p>Signature, uniquement en cas d'envoi sur papier :</p><span class=\"fill\"></span>\n      </div>\n\n      <p class=\"legal__back\"><a href=\"index.html\">← Retour à l'accueil</a></p>"
    },
    "privacy": {
      "title": "Politique de confidentialité — CoachTanguy",
      "desc": "Comment CoachTanguy traite vos données personnelles : finalités, bases légales, durées de conservation et vos droits (RGPD).",
      "body": "      <span class=\"eyebrow\">Confidentialité</span>\n      <h1>Politique de confidentialité</h1>\n      <p class=\"legal__update\">Dernière mise à jour : 29 juillet 2026</p>\n\n      <h2>1. Responsable du traitement</h2>\n      <p>Le responsable du traitement des données personnelles est :</p>\n      <ul>\n        <li>Tanguy Witters, CoachTanguy</li>\n        <li>Coach sportif indépendant</li>\n        <li>Adresse : Avenue de la Pépinière 11, 1640 Rhode-Saint-Genèse, Belgique</li>\n        <li>Numéro d'entreprise BCE : 1026.048.974</li>\n        <li>Numéro de TVA : BE1026048974</li>\n        <li>E-mail : <a href=\"mailto:contact@coachtanguy.com\">contact@coachtanguy.com</a></li>\n        <li>Téléphone : +32 472 76 16 39</li>\n      </ul>\n      <p>La présente politique explique comment les données personnelles sont collectées et utilisées au moyen du site coachtanguy.com et dans le cadre des prestations de coaching sportif.</p>\n\n      <h2>2. Données collectées, finalités et bases légales</h2>\n\n      <h3>Demandes de contact</h3>\n      <p>Lorsque vous utilisez le formulaire de contact ou contactez directement CoachTanguy par e-mail, téléphone ou WhatsApp, les données suivantes peuvent être traitées :</p>\n      <ul>\n        <li>nom et prénom ;</li>\n        <li>adresse e-mail ;</li>\n        <li>numéro de téléphone ;</li>\n        <li>contenu des messages ;</li>\n        <li>informations relatives à votre demande.</li>\n      </ul>\n      <p>Ces données sont utilisées afin de répondre à votre demande, organiser un appel et vous fournir les informations nécessaires avant une éventuelle commande. La base légale est l'exécution de mesures précontractuelles prises à votre demande et l'intérêt légitime de CoachTanguy à répondre aux personnes qui le contactent.</p>\n\n      <h3>Organisation de l'accompagnement</h3>\n      <p>Lorsque vous devenez Client, les données suivantes peuvent notamment être traitées :</p>\n      <ul>\n        <li>identité et coordonnées ;</li>\n        <li>objectifs sportifs ;</li>\n        <li>niveau et expérience ;</li>\n        <li>disponibilités et organisation ;</li>\n        <li>matériel disponible ;</li>\n        <li>historique des séances ;</li>\n        <li>performances, progression et retours ;</li>\n        <li>programmes d'entraînement ;</li>\n        <li>réponses aux questionnaires et check-ups ;</li>\n        <li>échanges par e-mail ou WhatsApp.</li>\n      </ul>\n      <p>Ces données sont nécessaires afin de créer, organiser, personnaliser et assurer le suivi de votre accompagnement. La base légale est l'exécution du contrat conclu avec le Client.</p>\n\n      <h3>Données relatives à la santé</h3>\n      <p>Pour adapter les exercices et assurer la sécurité du Client, CoachTanguy peut recueillir des informations concernant notamment :</p>\n      <ul>\n        <li>les douleurs ;</li>\n        <li>les blessures ;</li>\n        <li>les pathologies ;</li>\n        <li>les limitations physiques ;</li>\n        <li>les traitements ayant une incidence sur la pratique sportive ;</li>\n        <li>la grossesse ou l'allaitement lorsque cela est pertinent ;</li>\n        <li>les antécédents utiles à l'accompagnement.</li>\n      </ul>\n      <p>Les données de santé sont des données sensibles. Elles ne sont traitées qu'avec le consentement explicite et distinct du Client et uniquement dans la mesure nécessaire pour adapter et sécuriser l'accompagnement. Le consentement peut notamment être recueilli au moyen de la case suivante dans le questionnaire initial :</p>\n      <blockquote>\n        <p>Je consens explicitement à ce que les informations relatives à ma santé que je communique soient utilisées par CoachTanguy uniquement afin d'adapter et de sécuriser mon accompagnement sportif.</p>\n      </blockquote>\n      <p>Le Client peut retirer son consentement à tout moment. Lorsque certaines informations sont indispensables à sa sécurité, leur retrait peut empêcher la poursuite de certains exercices ou d'un accompagnement personnalisé.</p>\n\n      <h3>Photos et vidéos</h3>\n      <p>Le Client peut volontairement transmettre des photos ou vidéos afin de permettre :</p>\n      <ul>\n        <li>une correction technique ;</li>\n        <li>l'analyse d'un exercice ;</li>\n        <li>le suivi de sa progression.</li>\n      </ul>\n      <p>Ces contenus ne sont pas publiés et ne sont pas utilisés à des fins publicitaires sans un accord préalable, distinct et explicite du Client.</p>\n\n      <h3>Réservations</h3>\n      <p>Lorsqu'un outil de réservation tel que Zcal est utilisé, les informations nécessaires à la réservation peuvent être traitées :</p>\n      <ul>\n        <li>nom ;</li>\n        <li>adresse e-mail ;</li>\n        <li>date et heure du rendez-vous ;</li>\n        <li>informations communiquées lors de la réservation.</li>\n      </ul>\n      <p>Ces données sont utilisées pour organiser et confirmer les rendez-vous.</p>\n\n      <h3>Paiements et facturation</h3>\n      <p>Les paiements sont traités au moyen de Stripe et des moyens de paiement disponibles sur sa page sécurisée. CoachTanguy ne collecte et ne conserve pas directement les données bancaires complètes du Client.</p>\n      <p>Les données nécessaires à la facturation et à la comptabilité peuvent être transmises à l'outil Accountable ou à un conseiller comptable. Elles sont traitées afin d'exécuter la commande et de respecter les obligations fiscales et comptables.</p>\n\n      <h3>Calculateur alimentaire</h3>\n      <p>Les données saisies dans le calculateur alimentaire gratuit, notamment l'âge, le sexe, la taille, le poids, l'activité et l'objectif, sont traitées directement dans le navigateur de l'utilisateur. Elles ne sont pas transmises à CoachTanguy et ne sont pas stockées sur un serveur, sauf évolution future clairement annoncée du fonctionnement du calculateur.</p>\n\n      <h3>Données techniques</h3>\n      <p>Lors de la consultation du site, l'hébergeur peut traiter certaines données techniques nécessaires au fonctionnement et à la sécurité du site, notamment :</p>\n      <ul>\n        <li>adresse IP ;</li>\n        <li>type de navigateur et d'appareil ;</li>\n        <li>date et heure de connexion ;</li>\n        <li>journaux techniques et informations de sécurité.</li>\n      </ul>\n      <p>Les informations relatives aux cookies et au stockage local sont précisées dans la <a href=\"cookies.html\">Politique de cookies</a>.</p>\n\n      <h3>Absence de profilage</h3>\n      <p>CoachTanguy n'utilise actuellement les données personnelles pour aucune décision automatisée produisant des effets juridiques, aucun profilage automatisé et aucune prospection commerciale automatisée.</p>\n\n      <h2>3. Caractère obligatoire ou facultatif des données</h2>\n      <p>Les informations indiquées comme obligatoires sont nécessaires pour :</p>\n      <ul>\n        <li>répondre à une demande ;</li>\n        <li>effectuer une réservation ;</li>\n        <li>établir une facture ;</li>\n        <li>créer un programme ;</li>\n        <li>assurer la sécurité et le suivi du Client.</li>\n      </ul>\n      <p>Le refus de fournir certaines données peut empêcher CoachTanguy de répondre à la demande, de conclure la commande ou de proposer un accompagnement suffisamment adapté. Les informations facultatives sont clairement présentées comme telles.</p>\n      <p>Les données sont principalement obtenues directement auprès de la personne concernée. Pour un Client mineur, certaines informations peuvent être communiquées par son représentant légal.</p>\n\n      <h2>4. Destinataires des données</h2>\n      <p>Les données personnelles ne sont jamais vendues. Elles sont accessibles uniquement à CoachTanguy et, lorsque cela est nécessaire, aux prestataires suivants :</p>\n      <ul>\n        <li>Netlify, pour l'hébergement du site et le formulaire de contact ;</li>\n        <li>le fournisseur de la messagerie électronique utilisée par CoachTanguy ;</li>\n        <li>WhatsApp et Meta, pour les communications effectuées par WhatsApp ;</li>\n        <li>FitPros, pour la création, l'hébergement et le suivi des programmes sportifs ;</li>\n        <li>Zcal, pour la réservation des rendez-vous ;</li>\n        <li>l'outil utilisé pour les questionnaires et check-ups, notamment Google Forms lorsqu'il est utilisé ;</li>\n        <li>Stripe et les prestataires de paiement choisis par le Client ;</li>\n        <li>Accountable ou le conseiller comptable, pour la facturation et la comptabilité ;</li>\n        <li>les autorités administratives ou judiciaires lorsque la loi l'exige.</li>\n      </ul>\n      <p>Chaque prestataire ne reçoit que les données nécessaires à sa mission. Lorsque le Client utilise une plateforme externe, l'utilisation de celle-ci est également soumise à la politique de confidentialité du prestataire concerné.</p>\n\n      <h2>5. Transferts hors de l'Espace économique européen</h2>\n      <p>Certains prestataires techniques, notamment Netlify, Meta, Stripe ou Google, peuvent traiter des données en dehors de l'Espace économique européen.</p>\n      <p>Lorsque cela se produit, les transferts sont encadrés par les mécanismes prévus par le RGPD, notamment une décision d'adéquation, des clauses contractuelles types ou d'autres garanties appropriées.</p>\n\n      <h2>6. Durées de conservation</h2>\n      <p>Les données sont conservées uniquement pendant la durée nécessaire à leur finalité :</p>\n      <ul>\n        <li>demandes de contact sans suite : au maximum 12 mois après le dernier échange ;</li>\n        <li>réservations et échanges précontractuels : au maximum 12 mois après le rendez-vous ou le dernier échange ;</li>\n        <li>programmes, questionnaires, check-ups et suivi client : pendant l'accompagnement, puis au maximum 12 mois après sa fin ;</li>\n        <li>messages WhatsApp et e-mails liés à l'accompagnement : pendant la relation client, puis au maximum 12 mois après sa fin, sauf nécessité de conserver un échange précis ;</li>\n        <li>données de santé : pendant l'accompagnement, puis au maximum 12 mois après sa fin, sauf retrait anticipé du consentement, litige ou obligation légale ;</li>\n        <li>photos et vidéos d'exécution ou de progression : pendant le temps nécessaire à leur analyse et au maximum 12 mois après la fin de l'accompagnement ;</li>\n        <li>documents comptables et factures : 10 ans conformément aux obligations légales belges ;</li>\n        <li>données stockées dans le navigateur : jusqu'à leur suppression par l'utilisateur ;</li>\n        <li>journaux techniques : pendant la durée nécessaire à la sécurité et au bon fonctionnement du site, selon les paramètres de l'hébergeur.</li>\n      </ul>\n      <p>À l'expiration de ces délais, les données sont supprimées ou anonymisées, sauf lorsqu'une conservation plus longue est nécessaire pour respecter une obligation légale ou défendre un droit en justice.</p>\n\n      <h2>7. Droits des personnes</h2>\n      <p>Toute personne concernée dispose, dans les conditions prévues par le RGPD, des droits suivants :</p>\n      <ul>\n        <li>droit d'obtenir des informations sur le traitement ;</li>\n        <li>droit d'accéder à ses données ;</li>\n        <li>droit de rectifier des données inexactes ;</li>\n        <li>droit de demander l'effacement ;</li>\n        <li>droit de demander la limitation du traitement ;</li>\n        <li>droit de s'opposer à certains traitements ;</li>\n        <li>droit à la portabilité des données ;</li>\n        <li>droit de retirer son consentement à tout moment.</li>\n      </ul>\n      <p>Le retrait du consentement ne remet pas en cause la licéité des traitements réalisés avant ce retrait.</p>\n      <p>Pour exercer ces droits, une demande peut être envoyée à : <a href=\"mailto:contact@coachtanguy.com\">contact@coachtanguy.com</a>. Une réponse est apportée dans un délai d'un mois. Une preuve d'identité peut être demandée uniquement en cas de doute raisonnable sur l'identité du demandeur.</p>\n\n      <h2>8. Sécurité</h2>\n      <p>CoachTanguy prend des mesures techniques et organisationnelles raisonnables afin de protéger les données personnelles, notamment :</p>\n      <ul>\n        <li>utilisation d'une connexion HTTPS ;</li>\n        <li>limitation de l'accès aux données ;</li>\n        <li>utilisation de comptes protégés ;</li>\n        <li>collecte limitée aux informations nécessaires ;</li>\n        <li>recours à des prestataires professionnels ;</li>\n        <li>suppression ou archivage des données devenues inutiles.</li>\n      </ul>\n      <p>Malgré ces mesures, aucun système informatique ou service accessible par internet ne peut garantir une sécurité absolue.</p>\n\n      <h2>9. Liens et plateformes externes</h2>\n      <p>Le site peut contenir des liens vers des plateformes externes telles que Stripe, WhatsApp, FitPros, Zcal ou les réseaux sociaux.</p>\n      <p>CoachTanguy ne contrôle pas les traitements réalisés directement par ces plateformes. L'utilisateur est invité à consulter leurs propres politiques de confidentialité avant de leur transmettre des données.</p>\n\n      <h2>10. Réclamation auprès de l'Autorité de protection des données</h2>\n      <p>Toute personne estimant que ses données ne sont pas traitées conformément à la réglementation peut introduire une réclamation auprès de :</p>\n      <ul>\n        <li>Autorité de protection des données</li>\n        <li>Rue de la Presse 35, 1000 Bruxelles</li>\n        <li>Téléphone : +32 (0)2 274 48 00</li>\n        <li>E-mail : <a href=\"mailto:contact@apd-gba.be\">contact@apd-gba.be</a></li>\n      </ul>\n\n      <h2>11. Modification de la politique</h2>\n      <p>La présente politique peut être modifiée afin de tenir compte :</p>\n      <ul>\n        <li>d'une évolution du site ;</li>\n        <li>de l'ajout ou du retrait d'un prestataire ;</li>\n        <li>d'une modification des services ;</li>\n        <li>d'une évolution de la réglementation.</li>\n      </ul>\n      <p>La date de la dernière mise à jour est indiquée en haut de la page.</p>\n\n      <p class=\"legal__back\"><a href=\"index.html\">← Retour à l'accueil</a></p>"
    },
    "cookies": {
      "title": "Politique de cookies — CoachTanguy",
      "desc": "Le site CoachTanguy n'utilise aucun cookie de suivi. Détail du stockage local fonctionnel utilisé et de vos options.",
      "body": "<span class=\"eyebrow\">Cookies &amp; stockage local</span>\n      <h1>Politique de cookies</h1>\n      <p class=\"legal__update\">Dernière mise à jour : juin 2026</p>\n\n      <h2>1. Pas de cookies de suivi</h2>\n      <p>Le site <strong>coachtanguy.com</strong> n'utilise <strong>aucun cookie de mesure d'audience, de publicité ou de réseaux sociaux</strong>, et aucun traceur tiers. Aucune bannière de consentement n'est donc nécessaire : conformément aux recommandations de l'Autorité de protection des données (APD), seuls des stockages strictement nécessaires au fonctionnement du site sont utilisés, lesquels sont exemptés de consentement.</p>\n\n      <h2>2. Stockage local fonctionnel</h2>\n      <p>Le site utilise le stockage local de votre navigateur (localStorage / sessionStorage / Cache Storage) pour les seules finalités techniques suivantes :</p>\n      <ul>\n        <li><strong>Cache de l'application « Calculateur »</strong> (Cache Storage, si vous installez le calculateur comme application) : conserve les fichiers nécessaires au fonctionnement hors-ligne. Durée : jusqu'à désinstallation de l'application ou vidage du cache.</li>\n        <li><strong>SITE_CONTENT_fr / _nl / _en</strong> et <strong>CALC_I18N_fr / _nl / _en</strong> (localStorage) : brouillons d'édition du contenu, utilisés uniquement en mode prévisualisation par l'administrateur du site. Ils ne sont ni lus ni créés lors d'une visite normale. Durée : jusqu'à suppression manuelle.</li>\n        <li><strong>dash_ok</strong> (sessionStorage) : maintient la session de l'administrateur sur le tableau de bord d'édition. Durée : fermeture de l'onglet.</li>\n        <li><strong>cookie_consent</strong> (localStorage) : mémoriserait votre choix si une bannière de consentement devait être activée à l'avenir. <em>Non utilisé actuellement.</em> Durée maximale : 6 mois.</li>\n      </ul>\n      <p>Ces stockages restent dans votre navigateur : ils ne transmettent aucune information à des tiers et ne permettent pas de vous suivre.</p>\n\n      <h2>3. Services externes</h2>\n      <ul>\n        <li><strong>Polices de caractères</strong> : hébergées localement sur le site, aucune requête vers Google Fonts.</li>\n        <li><strong>Paiements Stripe</strong> : les boutons de paiement sont de simples liens vers les pages sécurisées de Stripe ; les cookies de Stripe ne s'appliquent que sur le site de Stripe (voir leur <a href=\"https://stripe.com/fr-be/privacy\" target=\"_blank\" rel=\"noopener\">politique de confidentialité</a>).</li>\n        <li><strong>WhatsApp</strong> : les boutons WhatsApp sont des liens ; aucun script de Meta n'est chargé sur ce site.</li>\n      </ul>\n\n      <h2>4. Comment supprimer ces données ?</h2>\n      <p>Vous pouvez à tout moment vider le stockage local et le cache de votre navigateur : Paramètres → Confidentialité → Effacer les données de navigation (ou équivalent selon votre navigateur). Pour l'application installée, désinstallez-la simplement.</p>\n\n      <h2>5. Si des traceurs devaient être ajoutés</h2>\n      <p>Si des cookies non essentiels (statistiques, marketing) devaient un jour être utilisés, ils ne seraient déposés qu'<strong>après votre consentement préalable, libre et éclairé</strong>, recueilli via une bannière permettant de refuser aussi simplement que d'accepter, sans cases pré-cochées, et votre choix serait conservé 6 mois maximum. Cette page serait mise à jour en conséquence.</p>\n\n      <p class=\"legal__back\"><a href=\"index.html\">← Retour à l'accueil</a></p>"
    }
  },
  "confirm": {
    "title": "Message envoyé — CoachTanguy",
    "desc": "Votre message a bien été envoyé à CoachTanguy.",
    "h1": "Message bien envoyé !",
    "text": "Merci pour votre message. Je reviens vers vous très rapidement, généralement dans la journée. À très vite pour votre première séance offerte !"
  },
  "collab": {
    "title": "Kiné partenaire à Rhode-Saint-Genèse — ZOWE × CoachTanguy",
    "desc": "CoachTanguy collabore avec ZOWE, le cabinet de kinésithérapie de Zoé Grêde à Rhode-Saint-Genèse : le soin et le coaching sportif avancent main dans la main.",
    "eyebrow": "Partenariat santé",
    "h1": "ZOWE Kiné × CoachTanguy",
    "intro": "Pour vous accompagner du soin jusqu'à la performance, je collabore avec Zoé Grêde, kinésithérapeute diplômée (Master en kinésithérapie et réadaptation, ULB) et praticienne de la méthode BELTRA. Son cabinet ZOWE est installé chez Kinovea, Rue des Iris à Rhode-Saint-Genèse, au cœur de ma zone de coaching.",
    "f1h": "Du soin à l'entraînement",
    "f1p": "Blessure, douleur, perte de mobilité ? Zoé restaure le mouvement ; je prends le relais pour reconstruire force et endurance, en toute sécurité.",
    "f2h": "Une expertise précise",
    "f2p": "Diagnostic morphostatique, travail myofascial profond, IASTM, vacuothérapie, mobilisations : une approche ciblée qui traite la cause, pas seulement les symptômes.",
    "f3h": "La même région",
    "f3p": "Cabinet à Rhode-Saint-Genèse et visites à domicile à Linkebeek, Beersel, Lot, Braine-l'Alleud et Waterloo, exactement là où je coache.",
    "cardEyebrow": "ZOWE, Kinésithérapie",
    "cardTitle": "Besoin d'un avis kiné ?",
    "cardText": "Lombalgies, cervicalgies, tendinites, douleurs chroniques ou retour au sport après blessure : découvrez l'approche de Zoé, « L'art de la justesse, l'expertise du soin ».",
    "chip1": "✓ Méthode BELTRA",
    "chip2": "✓ Cabinet Kinovea · Rhode-Saint-Genèse",
    "chip3": "✓ FR · NL · EN",
    "button": "Visiter zowekine.com",
    "aboutEyebrow": "Qui suis-je ?",
    "aboutTitle": "Zoé Grêde, kinésithérapeute BELTRA.",
    "aboutP1": "J'ai conçu Zowe avec une vision précise : transformer la séance de kinésithérapie en une expérience de haute précision.",
    "aboutP2": "Mon approche ne s'arrête pas à la disparition de la douleur, elle vise l'optimisation durable de votre capital physique.",
    "tick1": "Université Libre de Bruxelles",
    "tick2": "Master en kinésithérapie et réadaptation",
    "tick3": "Kinésithérapie conventionnelle également, via Kinovea",
    "aboutP3": "Pour atteindre ce niveau d'exigence, je me suis spécifiquement formée à la méthode Beltra. Cette expertise me permet d'intégrer à ma pratique des protocoles de soin avancés, axés sur le contrôle technique et la réharmonisation profonde du corps.",
    "aboutP4": "Chaque patient étant unique, je mets mon savoir-faire et cette spécialisation au service d'un accompagnement sur mesure, où la rigueur scientifique rencontre le confort d'une prise en charge exclusive."
  }
};
(window.SITE_CONTENT_ALL = window.SITE_CONTENT_ALL || {}).fr = window.SITE_CONTENT;
