/* ===========================================================
   INHOUD NEDERLANDS — CoachTanguy (bewerkt via dashboard.html)
   =========================================================== */
window.SITE_CONTENT = {
  "nav": {
    "accueil": "Home",
    "visio": "Videocoaching",
    "suivi": "Online opvolging",
    "calculateur": "Calculator",
    "faq": "FAQ",
    "contact": "Contact",
    "cta": "Plan een gesprek",
    "collab": "Samenwerking"
  },
  "calc": {
    "eyebrow": "Gratis tool",
    "title": "Voedingscalculator",
    "subtitle": "Schat je caloriebehoefte en macroverdeling in enkele seconden, op basis van je profiel en doelen."
  },
  "home": {
    "hero": {
      "eyebrow": "Gediplomeerd sportcoach",
      "titleHtml": "Sporten wordt makkelijk,<br />overal en altijd.",
      "subtitle": "Videocoaching en online opvolging, afgestemd op jouw niveau, je doelen en je agenda.",
      "ctaPrimary": "Videocoaching",
      "ctaSecondary": "Online opvolging",
      "pill1": "✓ Videogesprek",
      "pill2": "✓ Schema's op maat",
      "pill3": "✓ Zonder verbintenis"
    },
    "trust": {
      "v1": "500+",
      "l1": "uren opleiding",
      "v2": "100%",
      "l2": "op maat",
      "v3": "7/7",
      "l3": "begeleiding",
      "v4": "1e",
      "l4": "sessie gratis"
    },
    "services": {
      "eyebrow": "Diensten",
      "title": "Begeleiding op jouw tempo",
      "subtitle": "Twee formules om je vooruit te helpen, waar je ook bent.",
      "c1Title": "Videocoaching",
      "c1Text": "Geniet van professionele begeleiding op afstand via videogesprek, om overal gemotiveerd te blijven.",
      "c1Link": "Ontdek de formule",
      "c2Title": "Online opvolging",
      "c2Text": "Krijg persoonlijke opvolging, trainingsschema's en advies via een app.",
      "c2Link": "Ontdek de formule"
    },
    "process": {
      "eyebrow": "Hoe het werkt",
      "title": "Of het nu met videocoaching of online opvolging is: vorder in 3 eenvoudige stappen",
      "s1Title": "Kennismakingsgesprek",
      "s1Text": "Een eerste gratis gesprek om je behoeften en doelen te begrijpen en samen de methode te testen.",
      "s2Title": "Schema op maat",
      "s2Text": "Ik stel een programma op, afgestemd op jouw niveau, je agenda en je materiaal.",
      "s3Title": "Opvolging & resultaten",
      "s3Text": "We gaan samen vooruit: sessies, regelmatige bijsturing en motivatie voor blijvende resultaten."
    },
    "about": {
      "eyebrow": "Over mij",
      "title": "Tanguy, jouw sportcoach",
      "p1": "Afgestudeerd met een Bachelier en Coaching Sportif steun ik op een stevige kennis van anatomie, fysiologie, voeding en trainingswetenschap om je in alle veiligheid te begeleiden.",
      "p2": "Ik werkte met uiteenlopende profielen, van kinderen tot senioren, en pas elk programma aan jouw behoeften aan. Mijn parcours: meer dan 500 stage-uren, 2 jaar ervaring als personal coach en meer dan 10 jaar eigen krachttraining.",
      "s1v": "500+",
      "s1l": "stage-uren",
      "s2v": "2 jaar",
      "s2l": "coaching",
      "s3v": "10+ jaar",
      "s3l": "praktijk",
      "cta": "Werk met mij"
    },
    "faq": {
      "eyebrow": "FAQ",
      "title": "Veelgestelde vragen.",
      "q1": "Waarom sessiepakketten aanbieden?",
      "a1": "Met de pakketten regel je alles met één betaling en moedig je een engagement op langere termijn aan. Ze helpen je ook om regelmatig en gemotiveerd te blijven trainen — essentieel om vooruitgang te boeken en concrete resultaten te behalen.",
      "q2": "Hoe boek ik een sessie?",
      "a2": "Om de 2 weken ontvang je via WhatsApp een link naar mijn elektronische agenda om je sessie te reserveren. De reserveringen gebeuren om de 2 weken om meer flexibiliteit te garanderen en zich aan jouw agenda aan te passen.",
      "q3": "Kan ik een sessie annuleren of verplaatsen?",
      "a3": "Geen paniek: je kan een sessie annuleren en naar een andere datum verplaatsen zolang je pakket nog geldig is. Eens de einddatum van het pakket verstreken is, gaat elke ongebruikte sessie verloren.",
      "q4": "Hoe lang is een pakket geldig?",
      "a4": "De pakketten van 4 sessies zijn 5 weken geldig en de pakketten van 8 sessies 10 weken vanaf de betaaldatum. Die looptijd garandeert een regelmatige training en optimale resultaten. Na die termijn gaan ongebruikte sessies verloren. Het verplaatsen van een sessie verlengt de geldigheidsduur van het pakket niet.",
      "q5": "Welke betaalmethodes worden aanvaard?",
      "a5": "Betalingen kunnen met Visa, Mastercard, Revolut Pay, PayPal, Klarna, Bancontact, Apple Pay of Google Pay. De betaling verloopt veilig via Stripe.",
      "q6": "En als ik op vakantie ga?",
      "a6": "Geen probleem: je pakket of je opvolging wordt gewoon gepauzeerd en gaat verder bij je terugkeer.",
      "q7": "Kan ik in schijven betalen?",
      "a7": "Ja, betalen via Klarna is mogelijk. Daarmee kan je je pakket binnen 30 dagen betalen, afhankelijk van je geschiktheid. De betaling blijft veilig en verloopt rechtstreeks via Stripe."
    },
    "cta": {
      "title": "Klaar om te starten?",
      "text": "Neem contact op om je doelen te bespreken en de juiste formule te vinden. De eerste sessie is gratis.",
      "button": "Contacteer mij"
    },
    "payments": {
      "title": "Beveiligde betaling via Stripe"
    },
    "calcTeaser": {
      "eyebrow": "Gratis tool",
      "title": "Bereken je caloriebehoefte in 2 minuten",
      "text": "Basaal metabolisme, doelcalorieën, verdeling van je macro's en concrete richtlijnen om je maaltijden samen te stellen: mijn gratis voedingscalculator geeft je een duidelijke basis om te starten — zonder registratie.",
      "chip1": "✓ Calorieën & macro's",
      "chip2": "✓ Bordmethode",
      "chip3": "✓ Maaltijdideeën",
      "button": "Probeer de calculator"
    }
  },
  "footer": {
    "tagline": "Sporten wordt makkelijk, overal en altijd.",
    "areas": "Sportcoach in Sint-Genesius-Rode, Ukkel, Waterloo, Beersel, Linkebeek en Eigenbrakel — aan huis of via video.",
    "lVisio": "Videocoaching",
    "lSuivi": "Online opvolging",
    "lFaq": "FAQ",
    "lContact": "Contact",
    "lMentions": "Juridische info",
    "lCgv": "Voorwaarden",
    "copyright": "© 2026 CoachTanguy. Alle rechten voorbehouden.",
    "lPrivacy": "Privacy",
    "lCookies": "Cookies",
    "lCollab": "Partner-kine"
  },
  "contact": {
    "eyebrow": "Contact",
    "title": "Contacteer Tanguy",
    "subtitle": "Een vraag? Klaar om te starten? Stuur me een bericht, ik antwoord snel.",
    "asideTitle": "Een vraag?",
    "asideText": "Het eenvoudigst en snelst: een direct bericht via WhatsApp.",
    "waLabel": "WhatsApp",
    "waSub": "+32 472 76 16 39",
    "emailLabel": "E-mail",
    "emailSub": "contact@coachtanguy.com",
    "note": "✓ Eerste proefsessie gratis",
    "formTitle": "Snel bericht",
    "fName": "Naam",
    "phName": "Je naam",
    "fEmail": "E-mail",
    "phEmail": "jij@email.com",
    "fSubject": "Onderwerp",
    "optVisio": "Videocoaching",
    "optSuivi": "Online opvolging",
    "optEssai": "Gratis proefsessie",
    "optAutre": "Andere vraag",
    "fMessage": "Bericht",
    "phMessage": "Vertel me over je doelen...",
    "submit": "Bericht versturen",
    "consent": "Na het versturen van dit bericht neemt Tanguy nog dezelfde dag contact met u op.",
    "privacyText": "Uw gegevens (naam, e-mail, bericht) worden enkel gebruikt om uw vraag te behandelen.",
    "privacyLink": "Privacybeleid"
  },
  "visio": {
    "heroEyebrow": "Videocoaching",
    "heroTitleHtml": "Flexibel, interactief,<br />efficiënt.",
    "heroSubtitle": "Geniet van individuele sportcoachingsessies op afstand, overal toegankelijk. Persoonlijke coaching, advies in realtime en opvolging op maat via videogesprek.",
    "heroCta1": "Direct naar de pakketten",
    "heroCta2": "Gratis proefsessie",
    "f1Title": "Coaching op maat",
    "f1Text": "Sessies afgestemd op jouw tempo, je doelen en je ruimte, waar je ook bent.",
    "f2Title": "Sessiepakketten",
    "f2Text": "Pakketten afgestemd op je trainingsfrequentie voor échte regelmaat.",
    "f3Title": "Gratis proefsessie",
    "f3Text": "Een eerste gesprek om je behoeften te ontdekken, de methode te testen en samen je doelen te bepalen.",
    "packsEyebrow": "Pakketten",
    "packsTitle": "Kies de formule die bij je past",
    "packsSubtitle": "Aangepast en persoonlijk · feedback na elke sessie · uitstel mogelijk bij vakantie.",
    "p1Name": "Losse sessie",
    "p1Price": "40€",
    "p1Meta": "Sessie van 30 tot 40 min",
    "p1l1": "Aangepaste en persoonlijke sessie",
    "p1l2": "Feedback na de sessie",
    "p1l3": "Zonder verbintenis",
    "p1Note": "💳 Betaling bij de reservering",
    "p1Btn": "Reserveren",
    "p2Ribbon": "Meest gekozen",
    "p2Name": "Pakket 4 sessies",
    "p2Price": "140€",
    "p2PriceSub": "ofwel 35€ / sessie",
    "p2Meta": "Geldig 5 weken",
    "p2l1": "4 persoonlijke sessies",
    "p2l2": "Feedback na elke sessie",
    "p2l3": "Uitstel mogelijk bij vakantie",
    "p2l4": "Ideaal 1 sessie / week",
    "p2Btn": "Kiezen",
    "p3Name": "Pakket 8 sessies",
    "p3Price": "240€",
    "p3PriceSub": "ofwel 30€ / sessie",
    "p3Meta": "Geldig 10 weken",
    "p3l1": "8 persoonlijke sessies",
    "p3l2": "Feedback na elke sessie",
    "p3l3": "Uitstel mogelijk bij vakantie",
    "p3l4": "Beste tarief / sessie",
    "p3Btn": "Kiezen",
    "ctaTitle": "Klaar om te starten?",
    "ctaText": "Reserveer je gratis proefsessie en we beginnen samen.",
    "ctaBtn": "Contacteren"
  },
  "suivi": {
    "heroEyebrow": "Online Opvolging",
    "heroTitleHtml": "Sportcoaching<br />op afstand.",
    "heroSubtitle": "Opvolging op jouw tempo, 100% persoonlijk, waar je ook bent via de FitPros-app. Evoluerend programma, regelmatig advies en begeleiding op maat om efficiënt vooruit te gaan.",
    "heroCta1": "Direct naar de formules",
    "heroCta2": "Een vraag stellen",
    "appEyebrow": "FitPros",
    "appTitle": "Jouw programma op maat in je broekzak.",
    "appText": "Een eenvoudige ruimte om je vooruitgang te volgen en gemotiveerd te blijven.",
    "appB1Title": "Een eenvoudige ruimte om je vooruitgang te volgen.",
    "appB1Text": "In de app vind je makkelijk je lopende trainingen, je vooruitgang van de week en je volgende geplande sessies terug. Alles staat gecentraliseerd zodat je een helder overzicht houdt en regelmatig blijft trainen.",
    "appB2Title": "Stap-voor-stap begeleide sessies.",
    "appB2Text": "Elke sessie is helder opgebouwd met de oefeningen, de reeksen, de herhalingen, de bijhorende richtlijnen en uitvoeringsvideo's. Je start je training rechtstreeks vanuit de app en volgt het programma op jouw tempo, volledig zelfstandig.",
    "appT1": "Stap-voor-stap begeleide sessies",
    "appT2": "Duidelijke opvolging van je vooruitgang",
    "appT3": "Regelmatig advies en bijsturing",
    "appT4": "Rechtstreekse communicatie via WhatsApp",
    "appBtn": "Bekijk de formules",
    "suivisEyebrow": "Formules",
    "suivisTitle": "Deskundige opvolging, 100% persoonlijk",
    "suivisSubtitle": "Programma op maat, regelmatige bijsturing en menselijke begeleiding.",
    "flowLabel": "daarna",
    "s1Ribbon": "Om te starten",
    "s1Name": "Initiële begeleiding",
    "s1Price": "299€",
    "s1PriceSub": "voor 8 weken",
    "s1l1": "Persoonlijke begeleiding gedurende 8 weken",
    "s1l2": "Trainingsprogramma op maat afgestemd op je doelen",
    "s1l3": "Toegang via de FitPros-app",
    "s1l4": "Communicatie & opvolging via WhatsApp",
    "s1l5": "Introductiegesprek via video (~30 min) gratis",
    "s1l6": "Programma beschikbaar binnen 72u na het gesprek",
    "s1l7": "Check-up om de 2 weken via een formulier",
    "s1l8": "Regelmatige bijsturing voor optimale resultaten",
    "s1l9": "Pauze mogelijk bij vakantie",
    "s1Btn": "Kiezen",
    "s2Name": "Maandelijkse opvolging",
    "s2Price": "139€",
    "s2PriceSub": "per maand",
    "s2Meta": "Enkel na de initiële begeleiding",
    "s2l1": "Trainingsprogramma op maat",
    "s2l2": "Toegang via de FitPros-app",
    "s2l3": "Communicatie & opvolging via WhatsApp",
    "s2l4": "Check-up om de 2 weken",
    "s2l5": "Regelmatige bijsturing",
    "s2l6": "Pauze mogelijk bij vakantie",
    "s2Btn": "Kiezen",
    "ctaTitle": "Klaar om vooruit te gaan?",
    "ctaText": "Reserveer je gratis introductiegesprek en we bouwen je programma.",
    "ctaBtn": "Contacteren"
  },
  "stripe": {
    "unite": "contact.html",
    "pack4": "https://buy.stripe.com/5kQ4gBdvB0Yz85A7Pa0RG0a",
    "pack8": "https://buy.stripe.com/8x2cN7fDJePpadI8Te0RG0b",
    "initial": "https://buy.stripe.com/6oU3cx9fl6iTadIb1m0RG0c",
    "mensuel": "https://buy.stripe.com/dRm8wR63922DdpUfhC0RG09"
  },
  "meta": {
    "index": {
      "title": "Sportcoach in Sint-Genesius-Rode & Brabant — CoachTanguy",
      "desc": "Sportcoach in Sint-Genesius-Rode: coaching aan huis, via video en online opvolging. Ook in Waterloo, Beersel, Linkebeek en Eigenbrakel. 1e sessie gratis."
    },
    "visio": {
      "title": "Videocoaching — CoachTanguy",
      "desc": "Individuele sportcoaching op afstand via videogesprek. Flexibel, interactief en doeltreffend. Eerste proefsessie gratis."
    },
    "suivi": {
      "title": "Online opvolging — CoachTanguy",
      "desc": "100% gepersonaliseerde sportopvolging via de FitPros-app: evoluerend programma, regelmatig advies en begeleiding op maat om efficiënt vooruit te gaan."
    },
    "contact": {
      "title": "Contact — CoachTanguy",
      "desc": "Een vraag? Neem contact op met CoachTanguy via WhatsApp of bericht. Eerste proefsessie gratis."
    },
    "calc": {
      "title": "Voedingscalculator — CoachTanguy",
      "desc": "Gratis voedingscalculator: bereken je caloriebehoefte en de verdeling van je macro's (eiwitten, koolhydraten, vetten) volgens je profiel en doelen."
    }
  },
  "local": {
    "rhode": {
      "metaTitle": "Sportcoach in Sint-Genesius-Rode | aan huis & video — CoachTanguy",
      "metaDesc": "Sportcoach in Sint-Genesius-Rode: sessies aan huis of via video, programma en voeding op maat. Gediplomeerd coach, 1e proefsessie gratis.",
      "heroEyebrow": "Sportcoaching · Sint-Genesius-Rode",
      "h1": "Sportcoach in Sint-Genesius-Rode",
      "heroLead": "Gevestigd in Sint-Genesius-Rode bied ik persoonlijke sportcoaching aan, rechtstreeks bij je thuis of via videogesprek. Van het centrum tot de wijken bij het Zoniënwoud pas ik me aan jouw niveau, je doelen en je agenda aan — beginner of gevorderd.",
      "btnEssai": "Gratis proefsessie",
      "btnVisio": "Bekijk videocoaching",
      "secEyebrow": "In Sint-Genesius-Rode en omgeving",
      "h2": "Je sportcoach aan huis en via video in Sint-Genesius-Rode",
      "secIntro": "Geen sportzaal of lange verplaatsingen nodig: ik kom bij je thuis, of we werken via video met een programma tussen de sessies. Ideaal als je weinig tijd hebt of een privé en persoonlijke aanpak verkiest.",
      "f1h": "Aan huis in Sint-Genesius-Rode",
      "f1p": "Ik kom bij je langs in Sint-Genesius-Rode met het nodige materiaal. Je traint in een vertrouwde omgeving, op het uur dat jou uitkomt.",
      "f2h": "Coaching via video",
      "f2p": "Vanuit Sint-Genesius-Rode of onderweg volg je je sessies via videogesprek, met een bijgewerkt programma en correcties in realtime.",
      "f3h": "Programma & voeding op maat",
      "f3p": "Een plan afgestemd op je niveau en je doelen, met eenvoudige en concrete voedingsrichtlijnen — zonder extreem dieet.",
      "ctaH2": "Klaar om (opnieuw) te sporten in Sint-Genesius-Rode?",
      "ctaP": "Eerste proefsessie gratis, zonder verbintenis. Aan huis of via video, we starten wanneer je wil.",
      "btnContact": "Contacteer mij"
    },
    "uccle": {
      "metaTitle": "Sportcoach in Ukkel | aan huis & video — CoachTanguy",
      "metaDesc": "Sportcoach in Ukkel: sessies aan huis of via video, programma en voeding op maat. Gediplomeerd coach, 1e proefsessie gratis.",
      "heroEyebrow": "Sportcoaching · Ukkel",
      "h1": "Sportcoach in Ukkel",
      "heroLead": "Net ten noorden van Sint-Genesius-Rode begeleid ik de inwoners van Ukkel met persoonlijke sportcoaching, aan huis of via videogesprek. Van Fort-Jaco tot Diesdelle pas ik me aan jouw niveau, je doelen en je agenda aan.",
      "btnEssai": "Gratis proefsessie",
      "btnVisio": "Bekijk videocoaching",
      "secEyebrow": "In Ukkel en omgeving",
      "h2": "Je sportcoach aan huis en via video in Ukkel",
      "secIntro": "Geen drukke sportzaal nodig: ik kom bij je thuis, of we werken via video met een programma tussen de sessies. Handig voor drukke agenda's en de residentiële wijken van Ukkel.",
      "f1h": "Aan huis in Ukkel",
      "f1p": "Ik kom bij je langs in Ukkel met het nodige materiaal. Je traint in een vertrouwde omgeving, op het uur dat jou uitkomt.",
      "f2h": "Coaching via video",
      "f2p": "Vanuit Ukkel of onderweg volg je je sessies via videogesprek, met een bijgewerkt programma en correcties in realtime.",
      "f3h": "Programma & voeding op maat",
      "f3p": "Een plan afgestemd op je niveau en je doelen, met eenvoudige en concrete voedingsrichtlijnen — zonder extreem dieet.",
      "ctaH2": "Klaar om (opnieuw) te sporten in Ukkel?",
      "ctaP": "Eerste proefsessie gratis, zonder verbintenis. Aan huis of via video, we starten wanneer je wil.",
      "btnContact": "Contacteer mij"
    },
    "waterloo": {
      "metaTitle": "Sportcoach in Waterloo | aan huis & video — CoachTanguy",
      "metaDesc": "Sportcoach in Waterloo: persoonlijke coaching aan huis of via video — gewichtsverlies, fit worden, spieropbouw. 1e proefsessie gratis.",
      "heroEyebrow": "Sportcoaching · Waterloo",
      "h1": "Sportcoach in Waterloo",
      "heroLead": "Op enkele minuten van Sint-Genesius-Rode begeleid ik de inwoners van Waterloo met persoonlijke sportcoaching, aan huis of via video. Gewichtsverlies, fit worden, spieropbouw of fysieke voorbereiding: we bouwen samen een realistisch en progressief programma.",
      "btnEssai": "Gratis proefsessie",
      "btnVisio": "Bekijk videocoaching",
      "secEyebrow": "In Waterloo en omgeving",
      "h2": "Sportcoaching op maat in Waterloo",
      "secIntro": "Of je nu beginner of regelmatige sporter bent, elke sessie is aangepast aan je vorm van de dag. Tussen de afspraken houd je een duidelijk programma en advies om dagelijks vooruit te gaan, op jouw tempo.",
      "f1h": "Aan huis in Waterloo",
      "f1p": "Ik kom bij je langs in Waterloo met het nodige materiaal. Je traint in een vertrouwde omgeving, op het uur dat jou uitkomt.",
      "f2h": "Coaching via video",
      "f2p": "Vanuit Waterloo of onderweg volg je je sessies via videogesprek, met een bijgewerkt programma en correcties in realtime.",
      "f3h": "Programma & voeding op maat",
      "f3p": "Een plan afgestemd op je niveau en je doelen, met eenvoudige en concrete voedingsrichtlijnen — zonder extreem dieet.",
      "ctaH2": "Klaar om (opnieuw) te sporten in Waterloo?",
      "ctaP": "Eerste proefsessie gratis, zonder verbintenis. Aan huis of via video, we starten wanneer je wil.",
      "btnContact": "Contacteer mij"
    },
    "beersel": {
      "metaTitle": "Sportcoach in Beersel | aan huis & video — CoachTanguy",
      "metaDesc": "Sportcoach in Beersel (Alsemberg, Huizingen, Lot): sessies aan huis of via video, programma en voeding op maat. 1e proefsessie gratis.",
      "heroEyebrow": "Sportcoaching · Beersel",
      "h1": "Sportcoach in Beersel",
      "heroLead": "Persoonlijke sportcoaching in Beersel en zijn dorpen (Alsemberg, Huizingen, Lot), aan huis of via videogesprek. Een professionele en progressieve begeleiding om je doelen te bereiken, zonder de drempel van de sportzaal.",
      "btnEssai": "Gratis proefsessie",
      "btnVisio": "Bekijk videocoaching",
      "secEyebrow": "In Beersel en omgeving",
      "h2": "Begeleide sport, dicht bij huis in Beersel",
      "secIntro": "Coaching aan huis bespaart je tijd en houdt de motivatie hoog. Video laat je het ritme aanhouden, ook in drukke weken of onderweg — het is de regelmaat die resultaten oplevert.",
      "f1h": "Aan huis in Beersel",
      "f1p": "Ik kom bij je langs in Beersel met het nodige materiaal. Je traint in een vertrouwde omgeving, op het uur dat jou uitkomt.",
      "f2h": "Coaching via video",
      "f2p": "Vanuit Beersel of onderweg volg je je sessies via videogesprek, met een bijgewerkt programma en correcties in realtime.",
      "f3h": "Programma & voeding op maat",
      "f3p": "Een plan afgestemd op je niveau en je doelen, met eenvoudige en concrete voedingsrichtlijnen — zonder extreem dieet.",
      "ctaH2": "Klaar om (opnieuw) te sporten in Beersel?",
      "ctaP": "Eerste proefsessie gratis, zonder verbintenis. Aan huis of via video, we starten wanneer je wil.",
      "btnContact": "Contacteer mij"
    },
    "linkebeek": {
      "metaTitle": "Sportcoach in Linkebeek & Holleken | aan huis & video — CoachTanguy",
      "metaDesc": "Sportcoach in Linkebeek en Holleken: coaching aan huis of via video, programma op maat, voedingsadvies. Gediplomeerd coach, 1e proefsessie gratis.",
      "heroEyebrow": "Sportcoaching · Linkebeek",
      "h1": "Sportcoach in Linkebeek",
      "heroLead": "Sportcoach voor de inwoners van Linkebeek en Holleken, vlak naast Sint-Genesius-Rode. Sessies aan huis of via video, programma op maat, voedingsadvies en regelmatige opvolging voor blijvende resultaten.",
      "btnEssai": "Gratis proefsessie",
      "btnVisio": "Bekijk videocoaching",
      "secEyebrow": "In Linkebeek en omgeving",
      "h2": "Coaching dichtbij in Linkebeek",
      "secIntro": "Dankzij de nabijheid van Sint-Genesius-Rode zijn sessies aan huis makkelijk te plannen. Video blijft beschikbaar om de regelmaat nooit te breken, dé sleutel tot vooruitgang op lange termijn.",
      "f1h": "Aan huis in Linkebeek",
      "f1p": "Ik kom bij je langs in Linkebeek met het nodige materiaal. Je traint in een vertrouwde omgeving, op het uur dat jou uitkomt.",
      "f2h": "Coaching via video",
      "f2p": "Vanuit Linkebeek of onderweg volg je je sessies via videogesprek, met een bijgewerkt programma en correcties in realtime.",
      "f3h": "Programma & voeding op maat",
      "f3p": "Een plan afgestemd op je niveau en je doelen, met eenvoudige en concrete voedingsrichtlijnen — zonder extreem dieet.",
      "ctaH2": "Klaar om (opnieuw) te sporten in Linkebeek?",
      "ctaP": "Eerste proefsessie gratis, zonder verbintenis. Aan huis of via video, we starten wanneer je wil.",
      "btnContact": "Contacteer mij"
    },
    "braine": {
      "metaTitle": "Sportcoach in Eigenbrakel | aan huis & video — CoachTanguy",
      "metaDesc": "Sportcoach in Eigenbrakel: sessies aan huis of via video, begeleid door een gediplomeerd coach. Fit worden, fysieke voorbereiding. 1e proefsessie gratis.",
      "heroEyebrow": "Sportcoaching · Eigenbrakel",
      "h1": "Sportcoach in Eigenbrakel",
      "heroLead": "Sportcoaching in Eigenbrakel: sessies begeleid door een gediplomeerd coach, aan huis of via videogesprek. Van eenvoudige conditieopbouw tot fysieke voorbereiding, ik begeleid je stap voor stap, in alle veiligheid.",
      "btnEssai": "Gratis proefsessie",
      "btnVisio": "Bekijk videocoaching",
      "secEyebrow": "In Eigenbrakel en omgeving",
      "h2": "Begin rustig (opnieuw) met sporten in Eigenbrakel",
      "secIntro": "We gaan stap voor stap vooruit, met realistische doelen en regelmatige opvolging. Het idee is niet om alles in één keer om te gooien, maar om gewoonten te installeren die blijven duren.",
      "f1h": "Aan huis in Eigenbrakel",
      "f1p": "Ik kom bij je langs in Eigenbrakel met het nodige materiaal. Je traint in een vertrouwde omgeving, op het uur dat jou uitkomt.",
      "f2h": "Coaching via video",
      "f2p": "Vanuit Eigenbrakel of onderweg volg je je sessies via videogesprek, met een bijgewerkt programma en correcties in realtime.",
      "f3h": "Programma & voeding op maat",
      "f3p": "Een plan afgestemd op je niveau en je doelen, met eenvoudige en concrete voedingsrichtlijnen — zonder extreem dieet.",
      "ctaH2": "Klaar om (opnieuw) te sporten in Eigenbrakel?",
      "ctaP": "Eerste proefsessie gratis, zonder verbintenis. Aan huis of via video, we starten wanneer je wil.",
      "btnContact": "Contacteer mij"
    }
  },
  "legal": {
    "privacy": {
      "title": "Privacybeleid — CoachTanguy",
      "desc": "Hoe CoachTanguy uw persoonsgegevens verwerkt: doeleinden, rechtsgronden, bewaartermijnen en uw rechten (AVG).",
      "body": "<span class=\"eyebrow\">Privacy</span>\n      <h1>Privacybeleid</h1>\n      <p class=\"legal__update\">Laatste update: juni 2026</p>\n\n      <h2>1. Verwerkingsverantwoordelijke</h2>\n      <p>De verwerkingsverantwoordelijke voor de gegevens die via <strong>coachtanguy.com</strong> worden verzameld is:</p>\n      <ul>\n        <li>Tanguy Witters (CoachTanguy), zelfstandig sportcoach</li>\n        <li>Avenue de la Pépinière 11, 1640 Sint-Genesius-Rode, België</li>\n        <li>Ondernemingsnummer (KBO): 1026.048.974 — btw: BE1026048974</li>\n        <li>E-mail: contact@coachtanguy.com — Telefoon: +32 472 76 16 39</li>\n      </ul>\n\n      <h2>2. Verwerkte gegevens, doeleinden en rechtsgronden</h2>\n      <p><strong>Contactformulier</strong> (naam, e-mail, onderwerp, bericht): uitsluitend gebruikt om uw vraag te beantwoorden en onze uitwisseling op te volgen. Rechtsgrond: precontractuele maatregelen op uw verzoek (art. 6.1.b AVG) en gerechtvaardigd belang om te antwoorden (art. 6.1.f).</p>\n      <p><strong>Rechtstreeks contact</strong> (e-mail, WhatsApp, telefoon): zelfde doeleinden en rechtsgronden. Het gebruik van WhatsApp valt onder het privacybeleid van WhatsApp (Meta).</p>\n      <p><strong>Klantenrelatie</strong> (als u klant wordt): gegevens die nodig zijn voor de organisatie en opvolging van de coaching. Rechtsgrond: uitvoering van de overeenkomst (art. 6.1.b). Eventuele gegevens over uw gezondheid of fysieke conditie worden enkel verwerkt met uw uitdrukkelijke toestemming (art. 9.2.a), die u op elk moment kan intrekken.</p>\n      <p><strong>Betalingen</strong>: verwerkt door Stripe (en desgevallend PayPal/Klarna) op hun eigen beveiligde pagina's. De site verzamelt of bewaart geen bankgegevens.</p>\n      <p><strong>Voedingscalculator</strong>: de ingevoerde gegevens (geslacht, leeftijd, lengte, gewicht, doel) worden uitsluitend in uw browser verwerkt. Ze worden niet doorgestuurd en niet op een server opgeslagen.</p>\n      <p>De site doet niet aan geautomatiseerde prospectie, profilering of geautomatiseerde besluitvorming.</p>\n\n      <h2>3. Ontvangers</h2>\n      <p>Uw gegevens worden nooit verkocht. Ze zijn enkel toegankelijk voor de verwerkingsverantwoordelijke en zijn strikt noodzakelijke technische verwerkers:</p>\n      <ul>\n        <li><strong>Netlify, Inc.</strong> (hosting van de site en ontvangst van de berichten van het contactformulier)</li>\n        <li><strong>Stripe</strong> (betalingsverwerking, op de pagina's van Stripe)</li>\n        <li>De e-mailprovider die wordt gebruikt om u te antwoorden</li>\n      </ul>\n\n      <h2>4. Doorgiften buiten de Europese Unie</h2>\n      <p>Onze host Netlify, Inc. is gevestigd in de Verenigde Staten: berichten via het formulier kunnen dus buiten de EU worden verwerkt. Deze doorgifte is omkaderd door de waarborgen van hoofdstuk V van de AVG (adequaatheidsbesluit EU–VS \"Data Privacy Framework\" en/of standaardcontractbepalingen). Hetzelfde geldt voor Stripe bij een betaling.</p>\n\n      <h2>5. Bewaartermijnen</h2>\n      <ul>\n        <li>Contactberichten zonder gevolg: verwijderd uiterlijk 12 maanden na de laatste uitwisseling.</li>\n        <li>Klantgegevens: duur van de contractuele relatie, daarna beperkte archivering volgens de wettelijke verplichtingen (boekhoudkundige stukken: 7 jaar).</li>\n        <li>Lokale opslag in uw browser: zie het <a href=\"cookies.html\">cookiebeleid</a>.</li>\n      </ul>\n\n      <h2>6. Uw rechten</h2>\n      <p>Overeenkomstig artikelen 15 tot 22 van de AVG heeft u recht op <strong>inzage</strong>, <strong>rectificatie</strong>, <strong>wissing</strong>, <strong>beperking</strong> van de verwerking, <strong>bezwaar</strong> (met name tegen verwerkingen op basis van gerechtvaardigd belang), <strong>overdraagbaarheid</strong>, en <strong>intrekking van uw toestemming</strong> op elk moment wanneer de verwerking daarop berust.</p>\n      <p>Om deze rechten uit te oefenen, schrijf naar <a href=\"mailto:contact@coachtanguy.com\">contact@coachtanguy.com</a>. U ontvangt een antwoord binnen één maand. Bij redelijke twijfel kan een identiteitsbewijs worden gevraagd.</p>\n\n      <h2>7. Klacht bij de toezichthoudende autoriteit</h2>\n      <p>Als u meent dat uw rechten niet worden gerespecteerd, kan u een klacht indienen bij de <strong>Gegevensbeschermingsautoriteit</strong> (GBA):</p>\n      <ul>\n        <li>Drukpersstraat 35, 1000 Brussel</li>\n        <li>Telefoon: +32 (0)2 274 48 00</li>\n        <li>E-mail: contact@apd-gba.be</li>\n        <li>Website: <a href=\"https://www.gegevensbeschermingsautoriteit.be\" target=\"_blank\" rel=\"noopener\">www.gegevensbeschermingsautoriteit.be</a></li>\n      </ul>\n\n      <h2>8. Beveiliging</h2>\n      <p>De site wordt uitsluitend via HTTPS aangeboden. Enkel de strikt noodzakelijke gegevens worden verzameld (minimalisatie), en de lettertypen worden lokaal gehost zodat er geen gegevens (waaronder uw IP-adres) naar Google worden gestuurd bij het bezoeken van de site.</p>\n\n      <h2>9. Wijzigingen</h2>\n      <p>Dit beleid kan worden bijgewerkt, onder meer bij wijzigingen aan de site of de regelgeving. De datum van de laatste update staat bovenaan deze pagina.</p>\n\n      <p class=\"legal__back\"><a href=\"index.html\">← Terug naar de startpagina</a></p>"
    },
    "cookies": {
      "title": "Cookiebeleid — CoachTanguy",
      "desc": "CoachTanguy gebruikt geen enkele trackingcookie. Overzicht van de functionele lokale opslag en uw opties.",
      "body": "<span class=\"eyebrow\">Cookies &amp; lokale opslag</span>\n      <h1>Cookiebeleid</h1>\n      <p class=\"legal__update\">Laatste update: juni 2026</p>\n\n      <h2>1. Geen trackingcookies</h2>\n      <p>De site <strong>coachtanguy.com</strong> gebruikt <strong>geen enkele cookie voor statistieken, reclame of sociale media</strong>, en geen trackers van derden. Een toestemmingsbanner is dus niet nodig: overeenkomstig de aanbevelingen van de Gegevensbeschermingsautoriteit (GBA) wordt enkel opslag gebruikt die strikt noodzakelijk is voor de werking van de site, en die is vrijgesteld van toestemming.</p>\n\n      <h2>2. Functionele lokale opslag</h2>\n      <p>De site gebruikt de lokale opslag van uw browser (localStorage / sessionStorage / Cache Storage) uitsluitend voor de volgende technische doeleinden:</p>\n      <ul>\n        <li><strong>Cache van de app \"Calculator\"</strong> (Cache Storage, als u de calculator als app installeert): bewaart de bestanden die nodig zijn om offline te werken. Duur: tot u de app verwijdert of de cache wist.</li>\n        <li><strong>SITE_CONTENT_fr / _nl / _en</strong> en <strong>CALC_I18N_fr / _nl / _en</strong> (localStorage): conceptversies van de inhoud, enkel gebruikt in voorbeeldmodus door de beheerder van de site. Ze worden niet gelezen of aangemaakt bij een gewoon bezoek. Duur: tot handmatige verwijdering.</li>\n        <li><strong>dash_ok</strong> (sessionStorage): houdt de sessie van de beheerder op het bewerkingsdashboard actief. Duur: sluiten van het tabblad.</li>\n        <li><strong>cookie_consent</strong> (localStorage): zou uw keuze onthouden indien ooit een toestemmingsbanner wordt geactiveerd. <em>Momenteel niet in gebruik.</em> Maximale duur: 6 maanden.</li>\n      </ul>\n      <p>Deze opslag blijft in uw browser: er wordt geen informatie naar derden gestuurd en u kan er niet mee worden gevolgd.</p>\n\n      <h2>3. Externe diensten</h2>\n      <ul>\n        <li><strong>Lettertypen</strong>: lokaal gehost op de site — geen enkele aanvraag naar Google Fonts.</li>\n        <li><strong>Stripe-betalingen</strong>: de betaalknoppen zijn gewone links naar de beveiligde pagina's van Stripe; de cookies van Stripe gelden enkel op de site van Stripe (zie hun <a href=\"https://stripe.com/nl-be/privacy\" target=\"_blank\" rel=\"noopener\">privacybeleid</a>).</li>\n        <li><strong>WhatsApp</strong>: de WhatsApp-knoppen zijn links; er wordt geen script van Meta op deze site geladen.</li>\n      </ul>\n\n      <h2>4. Hoe deze gegevens verwijderen?</h2>\n      <p>U kan op elk moment de lokale opslag en de cache van uw browser wissen: Instellingen → Privacy → Browsegegevens wissen (of gelijkaardig volgens uw browser). Voor de geïnstalleerde app: verwijder ze gewoon.</p>\n\n      <h2>5. Als er ooit trackers worden toegevoegd</h2>\n      <p>Indien ooit niet-essentiële cookies (statistieken, marketing) zouden worden gebruikt, worden die enkel geplaatst <strong>na uw voorafgaande, vrije en geïnformeerde toestemming</strong>, via een banner waarmee weigeren even eenvoudig is als aanvaarden, zonder vooraf aangevinkte vakjes, en uw keuze wordt maximaal 6 maanden bewaard. Deze pagina zou dan worden bijgewerkt.</p>\n\n      <p class=\"legal__back\"><a href=\"index.html\">← Terug naar de startpagina</a></p>"
    }
  },
  "collab": {
    "title": "Partner-kinesitherapeut in Sint-Genesius-Rode — ZOWE × CoachTanguy",
    "desc": "CoachTanguy werkt samen met ZOWE, de kinesitherapiepraktijk van Zoé Grêde in Sint-Genesius-Rode: zorg en sportcoaching gaan hand in hand.",
    "eyebrow": "Gezondheidspartnerschap",
    "h1": "ZOWE Kine × CoachTanguy",
    "intro": "Om je van herstel tot prestatie te begeleiden, werk ik samen met Zoé Grêde, gediplomeerd kinesitherapeute (Master in de kinesitherapie en revalidatie, ULB) en beoefenaar van de BELTRA-methode. Haar praktijk ZOWE is gevestigd bij Kinovea, Rue des Iris in Sint-Genesius-Rode — midden in mijn coachingzone.",
    "f1h": "Van zorg naar training",
    "f1p": "Blessure, pijn, verminderde mobiliteit? Zoé herstelt de beweging; ik neem het over om kracht en uithouding veilig weer op te bouwen.",
    "f2h": "Precieze expertise",
    "f2p": "Morfostatische diagnose, diep myofasciaal werk, IASTM, vacuümtherapie, mobilisaties: een gerichte aanpak die de oorzaak behandelt, niet alleen de symptomen.",
    "f3h": "Dezelfde regio",
    "f3p": "Praktijk in Sint-Genesius-Rode en huisbezoeken in Linkebeek, Beersel, Lot, Eigenbrakel en Waterloo — precies waar ik coach.",
    "cardEyebrow": "ZOWE — Kinesitherapie",
    "cardTitle": "Nood aan kine-advies?",
    "cardText": "Lage rugpijn, nekpijn, tendinitis, chronische pijn of terugkeer naar sport na een blessure: ontdek de aanpak van Zoé — \"L'art de la justesse, l'expertise du soin\".",
    "chip1": "✓ BELTRA-methode",
    "chip2": "✓ Praktijk Kinovea · Sint-Genesius-Rode",
    "chip3": "✓ FR · NL · EN",
    "button": "Bezoek zowekine.com",
    "aboutEyebrow": "Wie ben ik?",
    "aboutTitle": "Zoé Grêde, BELTRA-kinesitherapeute",
    "aboutP1": "Ik heb Zowe ontworpen met een duidelijke visie: de kinesitherapiesessie omvormen tot een ervaring van hoge precisie.",
    "aboutP2": "Mijn aanpak stopt niet bij het verdwijnen van de pijn, maar mikt op de duurzame optimalisatie van uw fysieke kapitaal.",
    "tick1": "Université Libre de Bruxelles",
    "tick2": "Master in de kinesitherapie en revalidatie",
    "tick3": "Ook conventionele kinesitherapie, via Kinovea",
    "aboutP3": "Om dat niveau van precisie te bereiken, heb ik mij specifiek gevormd in de Beltra-methode. Die expertise laat mij toe geavanceerde zorgprotocollen in mijn praktijk te integreren, gericht op technische controle en een diepe herharmonisatie van het lichaam.",
    "aboutP4": "Omdat elke patiënt uniek is, stel ik mijn vakkennis en deze specialisatie ten dienste van een begeleiding op maat, waar wetenschappelijke nauwkeurigheid het comfort van een exclusieve aanpak ontmoet."
  }
};
(window.SITE_CONTENT_ALL = window.SITE_CONTENT_ALL || {}).nl = window.SITE_CONTENT;
