/* ===========================================================
   INHOUD NEDERLANDS — CoachTanguy (bewerkt via dashboard.html)
   =========================================================== */
window.SITE_CONTENT = {
  "nav": {
    "suivis": "Diensten",
    "avis": "Reviews",
    "accueil": "Home",
    "calculateur": "Calculator",
    "faq": "FAQ",
    "contact": "Contact",
    "cta": "Plan een gesprek",
    "collab": "Samenwerking"
  },
  "calc": {
    "eyebrow": "Gratis tool",
    "title": "Voedingscalculator",
    "subtitle": "Schat je caloriebehoefte en macroverdeling in enkele seconden, op basis van je profiel en doelen."
  },
  "home": {
    "hero": {
      "eyebrow": "Gediplomeerd sportcoach",
      "titleHtml": "Sporten wordt makkelijk,<br />overal en altijd.",
      "subtitle": "Videocoaching en online opvolging, afgestemd op jouw niveau, je doelen en je agenda.",
      "ctaPrimary": "Videocoaching",
      "ctaSecondary": "Online opvolging",
      "pill1": "✓ Videogesprek",
      "pill2": "✓ Schema's op maat",
      "pill3": "✓ Zonder verbintenis"
    },
    "trust": {
      "v1": "500+",
      "l1": "uren opleiding",
      "v2": "100%",
      "l2": "op maat",
      "v3": "7/7",
      "l3": "begeleiding",
      "v4": "1e",
      "l4": "sessie gratis"
    },
    "services": {
      "eyebrow": "Diensten",
      "title": "Begeleiding op jouw tempo",
      "subtitle": "Twee formules om je vooruit te helpen, waar je ook bent.",
      "c1Title": "Videocoaching",
      "c1Text": "Geniet van professionele begeleiding op afstand via videogesprek, om overal gemotiveerd te blijven.",
      "c1Link": "Ontdek de formule",
      "c2Title": "Online opvolging",
      "c2Text": "Krijg persoonlijke opvolging, trainingsschema's en advies via een app.",
      "c2Link": "Ontdek de formule"
    },
    "process": {
      "eyebrow": "Hoe het werkt",
      "title": "Of het nu met videocoaching of online opvolging is: vorder in 3 eenvoudige stappen",
      "s1Title": "Kennismakingsgesprek",
      "s1Text": "Een eerste gratis gesprek om je behoeften en doelen te begrijpen en samen de methode te testen.",
      "s2Title": "Schema op maat",
      "s2Text": "Ik stel een programma op, afgestemd op jouw niveau, je agenda en je materiaal.",
      "s3Title": "Opvolging & resultaten",
      "s3Text": "We gaan samen vooruit: sessies, regelmatige bijsturing en motivatie voor blijvende resultaten."
    },
    "about": {
      "eyebrow": "Over mij",
      "title": "Tanguy, jouw sportcoach",
      "p1": "Afgestudeerd met een Bachelier en Coaching Sportif steun ik op een stevige kennis van anatomie, fysiologie, voeding en trainingswetenschap om je in alle veiligheid te begeleiden.",
      "p2": "Ik werkte met uiteenlopende profielen, van kinderen tot senioren, en pas elk programma aan jouw behoeften aan. Mijn parcours: meer dan 500 stage-uren, 2 jaar ervaring als personal coach en meer dan 10 jaar eigen krachttraining.",
      "s1v": "500+",
      "s1l": "stage-uren",
      "s2v": "2 jaar",
      "s2l": "coaching",
      "s3v": "10+ jaar",
      "s3l": "praktijk",
      "cta": "Werk met mij"
    },
    "faq": {
      "eyebrow": "FAQ",
      "title": "Veelgestelde vragen.",
      "q1": "Waarom sessiepakketten aanbieden?",
      "a1": "Met de pakketten regel je alles met één betaling en moedig je een engagement op langere termijn aan. Ze helpen je ook om regelmatig en gemotiveerd te blijven trainen, essentieel om vooruitgang te boeken en concrete resultaten te behalen.",
      "q2": "Hoe boek ik een sessie?",
      "a2": "Om de 2 weken ontvang je via WhatsApp een link naar mijn elektronische agenda om je sessie te reserveren. De reserveringen gebeuren om de 2 weken om meer flexibiliteit te garanderen en zich aan jouw agenda aan te passen.",
      "q3": "Kan ik een sessie annuleren of verplaatsen?",
      "a3": "Geen paniek: je kan een sessie annuleren en naar een andere datum verplaatsen zolang je pakket nog geldig is. Eens de einddatum van het pakket verstreken is, gaat elke ongebruikte sessie verloren.",
      "q4": "Hoe lang is een pakket geldig?",
      "a4": "De pakketten van 4 sessies zijn 5 weken geldig en de pakketten van 8 sessies 10 weken vanaf de betaaldatum. Die looptijd garandeert een regelmatige training en optimale resultaten. Na die termijn gaan ongebruikte sessies verloren. Het verplaatsen van een sessie verlengt de geldigheidsduur van het pakket niet.",
      "q5": "Welke betaalmethodes worden aanvaard?",
      "a5": "Betalingen kunnen met Visa, Mastercard, Revolut Pay, PayPal, Klarna, Bancontact, Apple Pay of Google Pay. De betaling verloopt veilig via Stripe.",
      "q6": "En als ik op vakantie ga?",
      "a6": "Geen probleem: je pakket of je opvolging wordt gewoon gepauzeerd en gaat verder bij je terugkeer.",
      "q7": "Kan ik in schijven betalen?",
      "a7": "Ja, betalen via Klarna is mogelijk. Daarmee kan je je pakket binnen 30 dagen betalen, afhankelijk van je geschiktheid. De betaling blijft veilig en verloopt rechtstreeks via Stripe."
    },
    "cta": {
      "title": "Klaar om te starten?",
      "text": "Neem contact op om je doelen te bespreken en de juiste formule te vinden. De eerste sessie is gratis.",
      "button": "Contacteer mij"
    },
    "payments": {
      "title": "Beveiligde betaling via Stripe"
    },
    "calcTeaser": {
      "eyebrow": "Gratis tool",
      "title": "Bereken je caloriebehoefte in 2 minuten",
      "text": "Basaal metabolisme, doelcalorieën, verdeling van je macro's en concrete richtlijnen om je maaltijden samen te stellen: mijn gratis voedingscalculator geeft je een duidelijke basis om te starten, zonder registratie.",
      "chip1": "✓ Calorieën & macro's",
      "chip3": "✓ Maaltijdideeën",
      "button": "Probeer de calculator"
    }
  },
  "avis": {
    "eyebrow": "Google reviews",
    "title": "Zij vertrouwen op mij.",
    "score": "5,0",
    "count": "16 Google-reviews",
    "cta1": "Laat een review achter",
    "cta2": "Bekijk alle reviews",
    "r1Name": "Laurence Bioul",
    "r1Text": "Super coach ! Il est très à l'écoute des besoins individuels, il adapte la séance en fonction de ma condition physique et des bobos du moment (migraines, douleur aux genoux etc.). Je recommande vivement !",
    "r2Name": "Sebastien Hayot",
    "r2Text": "Tanguy nous coache à domicile depuis près de deux ans, et nous sommes entièrement satisfaits de son accompagnement. Son approche est à la fois très professionnelle, bienveillante et parfaitement adaptée à nos besoins. Toujours à l'écoute, il sait motiver sans jamais mettre de pression, tout en restant humain et attentif à nos objectifs. Nous le recommandons sans la moindre hésitation.",
    "r3Name": "Didem Sengun",
    "r3Text": "Tanguy est très sympa et est un super coach qui sait me motiver ! Il a le peps et me donne envie de faire ma séance chaque séance.",
    "r4Name": "Maxime Lebg",
    "r4Text": "Super accompagnement ! J'ai apprécié le fait d'avoir un programme clair avec les exercices, les séries, les répétitions et les vidéos. On sait exactement quoi faire à chaque séance. Tanguy est sérieux, à l'écoute et très professionnel.",
    "r5Name": "Rosalie de Crombrugghe",
    "r5Text": "Tanguy m'a coachée à domicile pendant 1,5 an jusqu'à mes 6 mois de grossesse. J'adore son professionnalisme, ses coachings toujours différents, son écoute. De plus, il s'assure toujours que les mouvements soient bien faits. J'ai hâte de reprendre les coachings avec Tanguy !",
    "r6Name": "Tanguy R",
    "r6Text": "Je recommande vraiment le suivi en ligne avec Tanguy. C'est pratique, flexible et très bien organisé. Les exercices sont bien choisis et les consignes sont claires, ce qui permet de progresser sans devoir réfléchir à quoi faire.",
    "r7Name": "Caro Delvaux",
    "r7Text": "Super coach à domicile ! À l'écoute, professionnel, ponctuel, passionné. Adapte ses séances à l'évolution.",
    "r8Name": "Maggss115",
    "r8Text": "Tanguy est un coach très attentif et très à l'écoute. Il adapte le contenu des séances selon les besoins spécifiques du client et son niveau de fitness et le résultat est efficace, agréable et rapidement visible. Je le recommande vivement à quiconque veut se reprendre en main ou simplement rester en forme physique optimale.",
    "r9Name": "anne reynens",
    "r9Text": "Voilà 18 mois que Tanguy me suit. Il travaille mon physique et mon mental. Je le recommande.",
    "r10Name": "Laurence Henin",
    "r10Text": "Je recommande vivement le coach Tanguy. Jeune, dynamique et très professionnel, il sait parfaitement s'adapter aux besoins et aux objectifs de chacun. Son accompagnement est personnalisé, motivant et toujours réalisé avec bienveillance.",
    "r11Name": "Julien Rizk",
    "r11Text": "Très bon suivi en ligne. Le programme est clair, bien structuré et facile à suivre même quand on n'a pas énormément de temps. Tanguy est disponible, répond rapidement aux questions et adapte si besoin. Je recommande sans hésiter.",
    "r12Name": "Sonia B-Lila",
    "r12Text": "Je ne peux que conseiller Tanguy comme coach. Professionnel, à l'écoute, il sait adapter les entraînements en fonction des limites, points faibles et forts de chacun. Motivant, on se sent bien après ses séances malgré les challenges !",
    "r13Name": "Romain V.",
    "r13Text": "Très satisfait du suivi. Le programme était adapté à mes objectifs et à mon emploi du temps. J'ai surtout aimé le côté progressif, on ne se sent pas perdu et on voit qu'il y a une vraie logique derrière les séances.",
    "r14Name": "Estelle Bruyninckx",
    "r14Text": "Très satisfaite de mon suivi en ligne avec Tanguy. Le programme est clair, bien adapté à mon niveau et facile à suivre via l'application. L'accompagnement sur WhatsApp est un vrai plus : dès que j'ai une question sur un exercice, Tanguy me répond assez vite. Je recommande !"
  },
  "footer": {
    "tagline": "Sporten wordt makkelijk, overal en altijd.",
    "areas": "Sportcoach in Sint-Genesius-Rode, Ukkel, Waterloo, Beersel, Linkebeek en Eigenbrakel, aan huis of via video.",
    "lVisio": "Videocoaching",
    "lSuivi": "Online opvolging",
    "lFaq": "FAQ",
    "lContact": "Contact",
    "lMentions": "Juridische info",
    "lCgv": "Voorwaarden",
    "copyright": "© 2026 CoachTanguy. Alle rechten voorbehouden.",
    "lPrivacy": "Privacy",
    "lCookies": "Cookies",
    "lCollab": "Partner-kine"
  },
  "contact": {
    "eyebrow": "Contact",
    "title": "Contacteer Tanguy",
    "subtitle": "Een vraag? Klaar om te starten? Stuur me een bericht, ik antwoord snel.",
    "asideTitle": "Een vraag?",
    "asideText": "Het eenvoudigst en snelst: een direct bericht via WhatsApp.",
    "waLabel": "WhatsApp",
    "waSub": "+32 472 76 16 39",
    "emailLabel": "E-mail",
    "emailSub": "contact@coachtanguy.com",
    "note": "✓ Eerste proefsessie gratis",
    "formTitle": "Snel bericht",
    "fName": "Naam",
    "phName": "Je naam",
    "fEmail": "E-mail",
    "phEmail": "jij@email.com",
    "fSubject": "Onderwerp",
    "optVisio": "Videocoaching",
    "optSuivi": "Online opvolging",
    "optEssai": "Gratis proefsessie",
    "optAutre": "Andere vraag",
    "fMessage": "Bericht",
    "phMessage": "Vertel me over je doelen...",
    "submit": "Bericht versturen",
    "consent": "Na het versturen van dit bericht neemt Tanguy nog dezelfde dag contact met u op.",
    "privacyText": "Uw gegevens (naam, e-mail, bericht) worden enkel gebruikt om uw vraag te behandelen.",
    "privacyLink": "Privacybeleid"
  },
  "visio": {
    "heroEyebrow": "Videocoaching",
    "heroTitleHtml": "Flexibel, interactief,<br />efficiënt.",
    "heroSubtitle": "Geniet van individuele sportcoachingsessies op afstand, overal toegankelijk. Persoonlijke coaching, advies in realtime en opvolging op maat via videogesprek.",
    "heroCta1": "Direct naar de pakketten",
    "heroCta2": "Gratis proefsessie",
    "f1Title": "Coaching op maat",
    "f1Text": "Sessies afgestemd op jouw tempo, je doelen en je ruimte, waar je ook bent.",
    "f2Title": "Sessiepakketten",
    "f2Text": "Pakketten afgestemd op je trainingsfrequentie voor échte regelmaat.",
    "f3Title": "Gratis proefsessie",
    "f3Text": "Een eerste gesprek om je behoeften te ontdekken, de methode te testen en samen je doelen te bepalen.",
    "packsEyebrow": "Pakketten",
    "packsTitle": "Kies de formule die bij je past",
    "packsSubtitle": "Aangepast en persoonlijk · feedback na elke sessie · uitstel mogelijk bij vakantie.",
    "p1Name": "Losse sessie",
    "p1Price": "40€",
    "p1Meta": "Sessie van 30 tot 40 min",
    "p1l1": "Aangepaste en persoonlijke sessie",
    "p1l2": "Feedback na de sessie",
    "p1l3": "Zonder verbintenis",
    "p1Note": "💳 Betaling bij de reservering",
    "p1lCalc": "Persoonlijke voedingscalculator",
    "p1Btn": "Reserveren",
    "p2Ribbon": "Meest gekozen",
    "p2Name": "Pakket 4 sessies",
    "p2Price": "140€",
    "p2PriceSub": "ofwel 35€ / sessie",
    "p2Meta": "Geldig 5 weken",
    "p2l1": "4 persoonlijke sessies",
    "p2l2": "Feedback na elke sessie",
    "p2l3": "Uitstel mogelijk bij vakantie",
    "p2l4": "Ideaal 1 sessie / week",
    "p2lCalc": "Persoonlijke voedingscalculator",
    "p2Btn": "Kiezen",
    "p3Name": "Pakket 8 sessies",
    "p3Price": "240€",
    "p3PriceSub": "ofwel 30€ / sessie",
    "p3Meta": "Geldig 10 weken",
    "p3l1": "8 persoonlijke sessies",
    "p3l2": "Feedback na elke sessie",
    "p3l3": "Uitstel mogelijk bij vakantie",
    "p3l4": "Beste tarief / sessie",
    "p3lCalc": "Persoonlijke voedingscalculator",
    "p3Btn": "Kiezen",
    "ctaTitle": "Klaar om te starten?",
    "ctaText": "Reserveer je gratis proefsessie en we beginnen samen.",
    "ctaBtn": "Contacteren"
  },
  "suivi": {
    "heroEyebrow": "Online Opvolging",
    "heroTitleHtml": "Sportcoaching<br />op afstand.",
    "heroSubtitle": "Opvolging op jouw tempo, 100% persoonlijk, waar je ook bent via de FitPros-app. Evoluerend programma, regelmatig advies en begeleiding op maat om efficiënt vooruit te gaan.",
    "heroCta1": "Direct naar de formules",
    "heroCta2": "Een vraag stellen",
    "appEyebrow": "FitPros",
    "appTitle": "Jouw programma op maat in je broekzak.",
    "appText": "Een eenvoudige ruimte om je vooruitgang te volgen en gemotiveerd te blijven.",
    "appB1Title": "Een eenvoudige ruimte om je vooruitgang te volgen.",
    "appB1Text": "In de app vind je makkelijk je lopende trainingen, je vooruitgang van de week en je volgende geplande sessies terug. Alles staat gecentraliseerd zodat je een helder overzicht houdt en regelmatig blijft trainen.",
    "appB2Title": "Stap-voor-stap begeleide sessies.",
    "appB2Text": "Elke sessie is helder opgebouwd met de oefeningen, de reeksen, de herhalingen, de bijhorende richtlijnen en uitvoeringsvideo's. Je start je training rechtstreeks vanuit de app en volgt het programma op jouw tempo, volledig zelfstandig.",
    "appT1": "Stap-voor-stap begeleide sessies",
    "appT2": "Duidelijke opvolging van je vooruitgang",
    "appT3": "Regelmatig advies en bijsturing",
    "appT4": "Rechtstreekse communicatie via WhatsApp",
    "appBtn": "Bekijk de formules",
    "suivisEyebrow": "Formules",
    "suivisTitle": "Deskundige opvolging, 100% persoonlijk",
    "suivisSubtitle": "Programma op maat, regelmatige bijsturing en menselijke begeleiding.",
    "flowLabel": "daarna",
    "s1Ribbon": "Om te starten",
    "s1Name": "Initiële begeleiding",
    "s1Price": "299€",
    "s1PriceSub": "voor 8 weken",
    "s1l1": "Persoonlijke begeleiding gedurende 8 weken",
    "s1l2": "Trainingsprogramma op maat afgestemd op je doelen",
    "s1l3": "Toegang via de FitPros-app",
    "s1l4": "Communicatie & opvolging via WhatsApp",
    "s1l5": "Introductiegesprek via video (~30 min) gratis",
    "s1l6": "Programma beschikbaar binnen 72u na het gesprek",
    "s1l8": "Regelmatige bijsturing voor optimale resultaten",
    "s1l9": "Pauze mogelijk bij vakantie",
    "s1lCalc": "Persoonlijke voedingscalculator",
    "s1Btn": "Kiezen",
    "s2Name": "Maandelijkse opvolging",
    "s2Price": "139€",
    "s2PriceSub": "per maand",
    "s2Meta": "Enkel na de initiële begeleiding",
    "s2l1": "Trainingsprogramma op maat",
    "s2l2": "Toegang via de FitPros-app",
    "s2l3": "Communicatie & opvolging via WhatsApp",
    "s2l5": "Regelmatige bijsturing",
    "s2l6": "Pauze mogelijk bij vakantie",
    "s2lCalc": "Persoonlijke voedingscalculator",
    "s2Btn": "Kiezen",
    "ctaTitle": "Klaar om vooruit te gaan?",
    "ctaText": "Reserveer je gratis introductiegesprek en we bouwen je programma.",
    "ctaBtn": "Contacteren"
  },
  "stripe": {
    "unite": "contact.html",
    "pack4": "https://buy.stripe.com/5kQ4gBdvB0Yz85A7Pa0RG0a",
    "pack8": "https://buy.stripe.com/8x2cN7fDJePpadI8Te0RG0b",
    "initial": "https://buy.stripe.com/6oU3cx9fl6iTadIb1m0RG0c",
    "mensuel": "https://buy.stripe.com/6oU14p77d4aLadIglG0RG0g"
  },
  "meta": {
    "index": {
      "title": "Sportcoach in Sint-Genesius-Rode & Brabant — CoachTanguy",
      "desc": "Sportcoach in Sint-Genesius-Rode: coaching aan huis, via video en online opvolging. Ook in Waterloo, Beersel, Linkebeek en Eigenbrakel. 1e sessie gratis."
    },
    "visio": {
      "title": "Videocoaching — CoachTanguy",
      "desc": "Individuele sportcoaching op afstand via videogesprek. Flexibel, interactief en doeltreffend. Eerste proefsessie gratis."
    },
    "suivi": {
      "title": "Online opvolging — CoachTanguy",
      "desc": "100% gepersonaliseerde sportopvolging via de FitPros-app: evoluerend programma, regelmatig advies en begeleiding op maat om efficiënt vooruit te gaan."
    },
    "contact": {
      "title": "Contact — CoachTanguy",
      "desc": "Een vraag? Neem contact op met CoachTanguy via WhatsApp of bericht. Eerste proefsessie gratis."
    },
    "calc": {
      "title": "Voedingscalculator — CoachTanguy",
      "desc": "Gratis voedingscalculator: bereken je caloriebehoefte en de verdeling van je macro's (eiwitten, koolhydraten, vetten) volgens je profiel en doelen."
    }
  },
  "local": {
    "rhode": {
      "metaTitle": "Sportcoach in Sint-Genesius-Rode | aan huis & video — CoachTanguy",
      "metaDesc": "Sportcoach in Sint-Genesius-Rode: sessies aan huis of via video, programma en voeding op maat. Gediplomeerd coach, 1e proefsessie gratis.",
      "heroEyebrow": "Sportcoaching · Sint-Genesius-Rode",
      "h1": "Sportcoach in Sint-Genesius-Rode",
      "heroLead": "Gevestigd in Sint-Genesius-Rode bied ik persoonlijke sportcoaching aan, rechtstreeks bij je thuis of via videogesprek. Van het centrum tot de wijken bij het Zoniënwoud pas ik me aan jouw niveau, je doelen en je agenda aan, beginner of gevorderd.",
      "btnEssai": "Gratis proefsessie",
      "btnVisio": "Bekijk videocoaching",
      "secEyebrow": "In Sint-Genesius-Rode en omgeving",
      "h2": "Je sportcoach aan huis en via video in Sint-Genesius-Rode",
      "secIntro": "Geen sportzaal of lange verplaatsingen nodig: ik kom bij je thuis, of we werken via video met een programma tussen de sessies. Ideaal als je weinig tijd hebt of een privé en persoonlijke aanpak verkiest.",
      "f1h": "Aan huis in Sint-Genesius-Rode",
      "f1p": "Ik kom bij je langs in Sint-Genesius-Rode met het nodige materiaal. Je traint in een vertrouwde omgeving, op het uur dat jou uitkomt.",
      "f2h": "Coaching via video",
      "f2p": "Vanuit Sint-Genesius-Rode of onderweg volg je je sessies via videogesprek, met een bijgewerkt programma en correcties in realtime.",
      "f3h": "Programma & voeding op maat",
      "f3p": "Een plan afgestemd op je niveau en je doelen, met eenvoudige en concrete voedingsrichtlijnen, zonder extreem dieet.",
      "ctaH2": "Klaar om (opnieuw) te sporten in Sint-Genesius-Rode?",
      "ctaP": "Eerste proefsessie gratis, zonder verbintenis. Aan huis of via video, we starten wanneer je wil.",
      "btnContact": "Contacteer mij"
    },
    "uccle": {
      "metaTitle": "Sportcoach in Ukkel | aan huis & video — CoachTanguy",
      "metaDesc": "Sportcoach in Ukkel: sessies aan huis of via video, programma en voeding op maat. Gediplomeerd coach, 1e proefsessie gratis.",
      "heroEyebrow": "Sportcoaching · Ukkel",
      "h1": "Sportcoach in Ukkel",
      "heroLead": "Net ten noorden van Sint-Genesius-Rode begeleid ik de inwoners van Ukkel met persoonlijke sportcoaching, aan huis of via videogesprek. Van Fort-Jaco tot Diesdelle pas ik me aan jouw niveau, je doelen en je agenda aan.",
      "btnEssai": "Gratis proefsessie",
      "btnVisio": "Bekijk videocoaching",
      "secEyebrow": "In Ukkel en omgeving",
      "h2": "Je sportcoach aan huis en via video in Ukkel",
      "secIntro": "Geen drukke sportzaal nodig: ik kom bij je thuis, of we werken via video met een programma tussen de sessies. Handig voor drukke agenda's en de residentiële wijken van Ukkel.",
      "f1h": "Aan huis in Ukkel",
      "f1p": "Ik kom bij je langs in Ukkel met het nodige materiaal. Je traint in een vertrouwde omgeving, op het uur dat jou uitkomt.",
      "f2h": "Coaching via video",
      "f2p": "Vanuit Ukkel of onderweg volg je je sessies via videogesprek, met een bijgewerkt programma en correcties in realtime.",
      "f3h": "Programma & voeding op maat",
      "f3p": "Een plan afgestemd op je niveau en je doelen, met eenvoudige en concrete voedingsrichtlijnen, zonder extreem dieet.",
      "ctaH2": "Klaar om (opnieuw) te sporten in Ukkel?",
      "ctaP": "Eerste proefsessie gratis, zonder verbintenis. Aan huis of via video, we starten wanneer je wil.",
      "btnContact": "Contacteer mij"
    },
    "waterloo": {
      "metaTitle": "Sportcoach in Waterloo | aan huis & video — CoachTanguy",
      "metaDesc": "Sportcoach in Waterloo: persoonlijke coaching aan huis of via video — gewichtsverlies, fit worden, spieropbouw. 1e proefsessie gratis.",
      "heroEyebrow": "Sportcoaching · Waterloo",
      "h1": "Sportcoach in Waterloo",
      "heroLead": "Op enkele minuten van Sint-Genesius-Rode begeleid ik de inwoners van Waterloo met persoonlijke sportcoaching, aan huis of via video. Gewichtsverlies, fit worden, spieropbouw of fysieke voorbereiding: we bouwen samen een realistisch en progressief programma.",
      "btnEssai": "Gratis proefsessie",
      "btnVisio": "Bekijk videocoaching",
      "secEyebrow": "In Waterloo en omgeving",
      "h2": "Sportcoaching op maat in Waterloo",
      "secIntro": "Of je nu beginner of regelmatige sporter bent, elke sessie is aangepast aan je vorm van de dag. Tussen de afspraken houd je een duidelijk programma en advies om dagelijks vooruit te gaan, op jouw tempo.",
      "f1h": "Aan huis in Waterloo",
      "f1p": "Ik kom bij je langs in Waterloo met het nodige materiaal. Je traint in een vertrouwde omgeving, op het uur dat jou uitkomt.",
      "f2h": "Coaching via video",
      "f2p": "Vanuit Waterloo of onderweg volg je je sessies via videogesprek, met een bijgewerkt programma en correcties in realtime.",
      "f3h": "Programma & voeding op maat",
      "f3p": "Een plan afgestemd op je niveau en je doelen, met eenvoudige en concrete voedingsrichtlijnen, zonder extreem dieet.",
      "ctaH2": "Klaar om (opnieuw) te sporten in Waterloo?",
      "ctaP": "Eerste proefsessie gratis, zonder verbintenis. Aan huis of via video, we starten wanneer je wil.",
      "btnContact": "Contacteer mij"
    },
    "beersel": {
      "metaTitle": "Sportcoach in Beersel | aan huis & video — CoachTanguy",
      "metaDesc": "Sportcoach in Beersel (Alsemberg, Huizingen, Lot): sessies aan huis of via video, programma en voeding op maat. 1e proefsessie gratis.",
      "heroEyebrow": "Sportcoaching · Beersel",
      "h1": "Sportcoach in Beersel",
      "heroLead": "Persoonlijke sportcoaching in Beersel en zijn dorpen (Alsemberg, Huizingen, Lot), aan huis of via videogesprek. Een professionele en progressieve begeleiding om je doelen te bereiken, zonder de drempel van de sportzaal.",
      "btnEssai": "Gratis proefsessie",
      "btnVisio": "Bekijk videocoaching",
      "secEyebrow": "In Beersel en omgeving",
      "h2": "Begeleide sport, dicht bij huis in Beersel",
      "secIntro": "Coaching aan huis bespaart je tijd en houdt de motivatie hoog. Video laat je het ritme aanhouden, ook in drukke weken of onderweg, het is de regelmaat die resultaten oplevert.",
      "f1h": "Aan huis in Beersel",
      "f1p": "Ik kom bij je langs in Beersel met het nodige materiaal. Je traint in een vertrouwde omgeving, op het uur dat jou uitkomt.",
      "f2h": "Coaching via video",
      "f2p": "Vanuit Beersel of onderweg volg je je sessies via videogesprek, met een bijgewerkt programma en correcties in realtime.",
      "f3h": "Programma & voeding op maat",
      "f3p": "Een plan afgestemd op je niveau en je doelen, met eenvoudige en concrete voedingsrichtlijnen, zonder extreem dieet.",
      "ctaH2": "Klaar om (opnieuw) te sporten in Beersel?",
      "ctaP": "Eerste proefsessie gratis, zonder verbintenis. Aan huis of via video, we starten wanneer je wil.",
      "btnContact": "Contacteer mij"
    },
    "linkebeek": {
      "metaTitle": "Sportcoach in Linkebeek & Holleken | aan huis & video — CoachTanguy",
      "metaDesc": "Sportcoach in Linkebeek en Holleken: coaching aan huis of via video, programma op maat, voedingsadvies. Gediplomeerd coach, 1e proefsessie gratis.",
      "heroEyebrow": "Sportcoaching · Linkebeek",
      "h1": "Sportcoach in Linkebeek",
      "heroLead": "Sportcoach voor de inwoners van Linkebeek en Holleken, vlak naast Sint-Genesius-Rode. Sessies aan huis of via video, programma op maat, voedingsadvies en regelmatige opvolging voor blijvende resultaten.",
      "btnEssai": "Gratis proefsessie",
      "btnVisio": "Bekijk videocoaching",
      "secEyebrow": "In Linkebeek en omgeving",
      "h2": "Coaching dichtbij in Linkebeek",
      "secIntro": "Dankzij de nabijheid van Sint-Genesius-Rode zijn sessies aan huis makkelijk te plannen. Video blijft beschikbaar om de regelmaat nooit te breken, dé sleutel tot vooruitgang op lange termijn.",
      "f1h": "Aan huis in Linkebeek",
      "f1p": "Ik kom bij je langs in Linkebeek met het nodige materiaal. Je traint in een vertrouwde omgeving, op het uur dat jou uitkomt.",
      "f2h": "Coaching via video",
      "f2p": "Vanuit Linkebeek of onderweg volg je je sessies via videogesprek, met een bijgewerkt programma en correcties in realtime.",
      "f3h": "Programma & voeding op maat",
      "f3p": "Een plan afgestemd op je niveau en je doelen, met eenvoudige en concrete voedingsrichtlijnen, zonder extreem dieet.",
      "ctaH2": "Klaar om (opnieuw) te sporten in Linkebeek?",
      "ctaP": "Eerste proefsessie gratis, zonder verbintenis. Aan huis of via video, we starten wanneer je wil.",
      "btnContact": "Contacteer mij"
    },
    "braine": {
      "metaTitle": "Sportcoach in Eigenbrakel | aan huis & video — CoachTanguy",
      "metaDesc": "Sportcoach in Eigenbrakel: sessies aan huis of via video, begeleid door een gediplomeerd coach. Fit worden, fysieke voorbereiding. 1e proefsessie gratis.",
      "heroEyebrow": "Sportcoaching · Eigenbrakel",
      "h1": "Sportcoach in Eigenbrakel",
      "heroLead": "Sportcoaching in Eigenbrakel: sessies begeleid door een gediplomeerd coach, aan huis of via videogesprek. Van eenvoudige conditieopbouw tot fysieke voorbereiding, ik begeleid je stap voor stap, in alle veiligheid.",
      "btnEssai": "Gratis proefsessie",
      "btnVisio": "Bekijk videocoaching",
      "secEyebrow": "In Eigenbrakel en omgeving",
      "h2": "Begin rustig (opnieuw) met sporten in Eigenbrakel",
      "secIntro": "We gaan stap voor stap vooruit, met realistische doelen en regelmatige opvolging. Het idee is niet om alles in één keer om te gooien, maar om gewoonten te installeren die blijven duren.",
      "f1h": "Aan huis in Eigenbrakel",
      "f1p": "Ik kom bij je langs in Eigenbrakel met het nodige materiaal. Je traint in een vertrouwde omgeving, op het uur dat jou uitkomt.",
      "f2h": "Coaching via video",
      "f2p": "Vanuit Eigenbrakel of onderweg volg je je sessies via videogesprek, met een bijgewerkt programma en correcties in realtime.",
      "f3h": "Programma & voeding op maat",
      "f3p": "Een plan afgestemd op je niveau en je doelen, met eenvoudige en concrete voedingsrichtlijnen, zonder extreem dieet.",
      "ctaH2": "Klaar om (opnieuw) te sporten in Eigenbrakel?",
      "ctaP": "Eerste proefsessie gratis, zonder verbintenis. Aan huis of via video, we starten wanneer je wil.",
      "btnContact": "Contacteer mij"
    }
  },
  "legal": {
    "privacy": {
      "title": "Privacybeleid — CoachTanguy",
      "desc": "Hoe CoachTanguy uw persoonsgegevens verwerkt: doeleinden, rechtsgronden, bewaartermijnen en uw rechten (AVG).",
      "body": "      <span class=\"eyebrow\">Privacy</span>\n      <h1>Privacybeleid</h1>\n      <p class=\"legal__update\">Laatste update: 29 juli 2026</p>\n\n      <h2>1. Verwerkingsverantwoordelijke</h2>\n      <p>De verwerkingsverantwoordelijke voor de persoonsgegevens is:</p>\n      <ul>\n        <li>Tanguy Witters, CoachTanguy</li>\n        <li>Zelfstandig sportcoach</li>\n        <li>Adres: Avenue de la Pépinière 11, 1640 Sint-Genesius-Rode, België</li>\n        <li>Ondernemingsnummer KBO: 1026.048.974</li>\n        <li>Btw-nummer: BE1026048974</li>\n        <li>E-mail: <a href=\"mailto:contact@coachtanguy.com\">contact@coachtanguy.com</a></li>\n        <li>Telefoon: +32 472 76 16 39</li>\n      </ul>\n      <p>Dit beleid legt uit hoe persoonsgegevens worden verzameld en gebruikt via de website coachtanguy.com en in het kader van de sportcoachingdiensten.</p>\n\n      <h2>2. Verzamelde gegevens, doeleinden en rechtsgronden</h2>\n\n      <h3>Contactaanvragen</h3>\n      <p>Wanneer u het contactformulier gebruikt of CoachTanguy rechtstreeks contacteert via e-mail, telefoon of WhatsApp, kunnen de volgende gegevens worden verwerkt:</p>\n      <ul>\n        <li>naam en voornaam;</li>\n        <li>e-mailadres;</li>\n        <li>telefoonnummer;</li>\n        <li>inhoud van de berichten;</li>\n        <li>informatie met betrekking tot uw aanvraag.</li>\n      </ul>\n      <p>Deze gegevens worden gebruikt om uw aanvraag te beantwoorden, een gesprek te organiseren en u de nodige informatie te bezorgen voor een eventuele bestelling. De rechtsgrond is de uitvoering van precontractuele maatregelen op uw verzoek en het gerechtvaardigd belang van CoachTanguy om te antwoorden aan wie hem contacteert.</p>\n\n      <h3>Organisatie van de begeleiding</h3>\n      <p>Wanneer u Klant wordt, kunnen met name de volgende gegevens worden verwerkt:</p>\n      <ul>\n        <li>identiteit en contactgegevens;</li>\n        <li>sportieve doelstellingen;</li>\n        <li>niveau en ervaring;</li>\n        <li>beschikbaarheid en organisatie;</li>\n        <li>beschikbaar materiaal;</li>\n        <li>overzicht van de sessies;</li>\n        <li>prestaties, vooruitgang en feedback;</li>\n        <li>trainingsprogramma's;</li>\n        <li>antwoorden op vragenlijsten en check-ups;</li>\n        <li>uitwisselingen via e-mail of WhatsApp.</li>\n      </ul>\n      <p>Deze gegevens zijn nodig om uw begeleiding te creëren, te organiseren, te personaliseren en op te volgen. De rechtsgrond is de uitvoering van de met de Klant gesloten overeenkomst.</p>\n\n      <h3>Gezondheidsgegevens</h3>\n      <p>Om de oefeningen aan te passen en de veiligheid van de Klant te waarborgen, kan CoachTanguy met name informatie inzamelen over:</p>\n      <ul>\n        <li>pijnklachten;</li>\n        <li>blessures;</li>\n        <li>aandoeningen;</li>\n        <li>fysieke beperkingen;</li>\n        <li>behandelingen met een invloed op de sportpraktijk;</li>\n        <li>zwangerschap of het geven van borstvoeding wanneer dit relevant is;</li>\n        <li>voorgeschiedenis die nuttig is voor de begeleiding.</li>\n      </ul>\n      <p>Gezondheidsgegevens zijn gevoelige gegevens. Zij worden uitsluitend verwerkt met de expliciete en afzonderlijke toestemming van de Klant en enkel in de mate die nodig is om de begeleiding aan te passen en te beveiligen. De toestemming kan met name worden verkregen via het volgende vakje in de initiële vragenlijst:</p>\n      <blockquote>\n        <p>Ik geef uitdrukkelijk toestemming dat de gezondheidsinformatie die ik meedeel door CoachTanguy uitsluitend wordt gebruikt om mijn sportieve begeleiding aan te passen en te beveiligen.</p>\n      </blockquote>\n      <p>De Klant kan zijn toestemming op elk moment intrekken. Wanneer bepaalde informatie onmisbaar is voor zijn veiligheid, kan het intrekken ervan de voortzetting van bepaalde oefeningen of van een gepersonaliseerde begeleiding verhinderen.</p>\n\n      <h3>Foto's en video's</h3>\n      <p>De Klant kan vrijwillig foto's of video's bezorgen om het volgende mogelijk te maken:</p>\n      <ul>\n        <li>een technische correctie;</li>\n        <li>de analyse van een oefening;</li>\n        <li>de opvolging van zijn vooruitgang.</li>\n      </ul>\n      <p>Deze inhoud wordt niet gepubliceerd en wordt niet voor publicitaire doeleinden gebruikt zonder een voorafgaande, afzonderlijke en expliciete toestemming van de Klant.</p>\n\n      <h3>Reservaties</h3>\n      <p>Wanneer een reservatietool zoals Zcal wordt gebruikt, kunnen de voor de reservatie noodzakelijke gegevens worden verwerkt:</p>\n      <ul>\n        <li>naam;</li>\n        <li>e-mailadres;</li>\n        <li>datum en uur van de afspraak;</li>\n        <li>informatie meegedeeld bij de reservatie.</li>\n      </ul>\n      <p>Deze gegevens worden gebruikt om de afspraken te organiseren en te bevestigen.</p>\n\n      <h3>Betalingen en facturatie</h3>\n      <p>De betalingen worden verwerkt via Stripe en de betaalmiddelen die op zijn beveiligde pagina beschikbaar zijn. CoachTanguy verzamelt en bewaart de volledige bankgegevens van de Klant niet rechtstreeks.</p>\n      <p>De gegevens die nodig zijn voor de facturatie en de boekhouding kunnen worden doorgegeven aan de tool Accountable of aan een boekhoudkundig adviseur. Zij worden verwerkt om de bestelling uit te voeren en om de fiscale en boekhoudkundige verplichtingen na te leven.</p>\n\n      <h3>Voedingscalculator</h3>\n      <p>De gegevens die in de gratis voedingscalculator worden ingevuld, met name leeftijd, geslacht, lengte, gewicht, activiteit en doelstelling, worden rechtstreeks in de browser van de gebruiker verwerkt. Zij worden niet aan CoachTanguy doorgegeven en niet op een server opgeslagen, behoudens een toekomstige en duidelijk aangekondigde wijziging van de werking van de calculator.</p>\n\n      <h3>Technische gegevens</h3>\n      <p>Bij het bezoeken van de website kan de hostingprovider bepaalde technische gegevens verwerken die nodig zijn voor de werking en de veiligheid van de site, met name:</p>\n      <ul>\n        <li>IP-adres;</li>\n        <li>type browser en toestel;</li>\n        <li>datum en uur van de verbinding;</li>\n        <li>technische logbestanden en veiligheidsinformatie.</li>\n      </ul>\n      <p>De informatie over cookies en lokale opslag wordt toegelicht in het <a href=\"cookies.html\">Cookiebeleid</a>.</p>\n\n      <h3>Geen profilering</h3>\n      <p>CoachTanguy gebruikt de persoonsgegevens momenteel voor geen enkele geautomatiseerde beslissing met rechtsgevolgen, geen enkele geautomatiseerde profilering en geen enkele geautomatiseerde commerciële prospectie.</p>\n\n      <h2>3. Verplicht of facultatief karakter van de gegevens</h2>\n      <p>De als verplicht aangeduide informatie is noodzakelijk om:</p>\n      <ul>\n        <li>een aanvraag te beantwoorden;</li>\n        <li>een reservatie uit te voeren;</li>\n        <li>een factuur op te maken;</li>\n        <li>een programma te creëren;</li>\n        <li>de veiligheid en de opvolging van de Klant te waarborgen.</li>\n      </ul>\n      <p>Het weigeren om bepaalde gegevens te verstrekken kan CoachTanguy verhinderen om de aanvraag te beantwoorden, de bestelling af te sluiten of een voldoende aangepaste begeleiding voor te stellen. De facultatieve informatie wordt duidelijk als dusdanig gepresenteerd.</p>\n      <p>De gegevens worden hoofdzakelijk rechtstreeks bij de betrokken persoon verkregen. Voor een minderjarige Klant kan bepaalde informatie door zijn wettelijke vertegenwoordiger worden meegedeeld.</p>\n\n      <h2>4. Ontvangers van de gegevens</h2>\n      <p>De persoonsgegevens worden nooit verkocht. Zij zijn uitsluitend toegankelijk voor CoachTanguy en, wanneer dit noodzakelijk is, voor de volgende dienstverleners:</p>\n      <ul>\n        <li>Netlify, voor de hosting van de website en het contactformulier;</li>\n        <li>de aanbieder van de door CoachTanguy gebruikte e-maildienst;</li>\n        <li>WhatsApp en Meta, voor de communicatie via WhatsApp;</li>\n        <li>FitPros, voor de creatie, de hosting en de opvolging van de sportprogramma's;</li>\n        <li>Zcal, voor de reservatie van de afspraken;</li>\n        <li>de tool die wordt gebruikt voor de vragenlijsten en check-ups, met name Google Forms wanneer die wordt gebruikt;</li>\n        <li>Stripe en de door de Klant gekozen betaaldienstverleners;</li>\n        <li>Accountable of de boekhoudkundig adviseur, voor de facturatie en de boekhouding;</li>\n        <li>de administratieve of gerechtelijke overheden wanneer de wet dit vereist.</li>\n      </ul>\n      <p>Elke dienstverlener ontvangt enkel de gegevens die nodig zijn voor zijn opdracht. Wanneer de Klant een extern platform gebruikt, is het gebruik daarvan eveneens onderworpen aan het privacybeleid van de betrokken dienstverlener.</p>\n\n      <h2>5. Doorgifte buiten de Europese Economische Ruimte</h2>\n      <p>Bepaalde technische dienstverleners, met name Netlify, Meta, Stripe of Google, kunnen gegevens buiten de Europese Economische Ruimte verwerken.</p>\n      <p>Wanneer dit gebeurt, worden de doorgiften omkaderd door de mechanismen waarin de AVG voorziet, met name een adequaatheidsbesluit, standaardcontractbepalingen of andere passende waarborgen.</p>\n\n      <h2>6. Bewaartermijnen</h2>\n      <p>De gegevens worden uitsluitend bewaard voor de duur die nodig is voor hun doeleinde:</p>\n      <ul>\n        <li>contactaanvragen zonder gevolg: maximaal 12 maanden na de laatste uitwisseling;</li>\n        <li>reservaties en precontractuele uitwisselingen: maximaal 12 maanden na de afspraak of de laatste uitwisseling;</li>\n        <li>programma's, vragenlijsten, check-ups en klantenopvolging: tijdens de begeleiding, daarna maximaal 12 maanden na het einde ervan;</li>\n        <li>WhatsApp-berichten en e-mails verbonden aan de begeleiding: tijdens de klantenrelatie, daarna maximaal 12 maanden na het einde ervan, behalve wanneer een specifieke uitwisseling moet worden bewaard;</li>\n        <li>gezondheidsgegevens: tijdens de begeleiding, daarna maximaal 12 maanden na het einde ervan, behoudens vroegtijdige intrekking van de toestemming, geschil of wettelijke verplichting;</li>\n        <li>foto's en video's van uitvoering of vooruitgang: tijdens de tijd die nodig is voor de analyse ervan en maximaal 12 maanden na het einde van de begeleiding;</li>\n        <li>boekhoudkundige documenten en facturen: 10 jaar overeenkomstig de Belgische wettelijke verplichtingen;</li>\n        <li>gegevens die in de browser worden opgeslagen: tot de verwijdering ervan door de gebruiker;</li>\n        <li>technische logbestanden: voor de duur die nodig is voor de veiligheid en de goede werking van de site, volgens de instellingen van de hostingprovider.</li>\n      </ul>\n      <p>Na het verstrijken van deze termijnen worden de gegevens verwijderd of geanonimiseerd, behalve wanneer een langere bewaring noodzakelijk is om een wettelijke verplichting na te leven of een recht in rechte te verdedigen.</p>\n\n      <h2>7. Rechten van de betrokkenen</h2>\n      <p>Elke betrokken persoon beschikt, onder de door de AVG voorziene voorwaarden, over de volgende rechten:</p>\n      <ul>\n        <li>het recht om informatie over de verwerking te verkrijgen;</li>\n        <li>het recht op inzage van zijn gegevens;</li>\n        <li>het recht om onjuiste gegevens te laten rechtzetten;</li>\n        <li>het recht om verwijdering te vragen;</li>\n        <li>het recht om beperking van de verwerking te vragen;</li>\n        <li>het recht om zich tegen bepaalde verwerkingen te verzetten;</li>\n        <li>het recht op overdraagbaarheid van de gegevens;</li>\n        <li>het recht om zijn toestemming op elk moment in te trekken.</li>\n      </ul>\n      <p>Het intrekken van de toestemming doet geen afbreuk aan de rechtmatigheid van de verwerkingen die voor die intrekking werden uitgevoerd.</p>\n      <p>Om deze rechten uit te oefenen kan een verzoek worden verzonden naar: <a href=\"mailto:contact@coachtanguy.com\">contact@coachtanguy.com</a>. Er wordt binnen een termijn van één maand geantwoord. Een identiteitsbewijs kan uitsluitend worden gevraagd in geval van redelijke twijfel over de identiteit van de verzoeker.</p>\n\n      <h2>8. Beveiliging</h2>\n      <p>CoachTanguy neemt redelijke technische en organisatorische maatregelen om de persoonsgegevens te beschermen, met name:</p>\n      <ul>\n        <li>gebruik van een HTTPS-verbinding;</li>\n        <li>beperking van de toegang tot de gegevens;</li>\n        <li>gebruik van beveiligde accounts;</li>\n        <li>inzameling beperkt tot de noodzakelijke informatie;</li>\n        <li>beroep op professionele dienstverleners;</li>\n        <li>verwijdering of archivering van gegevens die nutteloos zijn geworden.</li>\n      </ul>\n      <p>Ondanks deze maatregelen kan geen enkel informaticasysteem of via internet toegankelijke dienst een absolute veiligheid garanderen.</p>\n\n      <h2>9. Links en externe platformen</h2>\n      <p>De website kan links bevatten naar externe platformen zoals Stripe, WhatsApp, FitPros, Zcal of de sociale media.</p>\n      <p>CoachTanguy heeft geen controle over de verwerkingen die rechtstreeks door deze platformen worden uitgevoerd. De gebruiker wordt uitgenodigd om hun eigen privacybeleid te raadplegen vooraleer hij hen gegevens bezorgt.</p>\n\n      <h2>10. Klacht bij de Gegevensbeschermingsautoriteit</h2>\n      <p>Elke persoon die meent dat zijn gegevens niet overeenkomstig de regelgeving worden verwerkt, kan een klacht indienen bij:</p>\n      <ul>\n        <li>Gegevensbeschermingsautoriteit</li>\n        <li>Drukpersstraat 35, 1000 Brussel</li>\n        <li>Telefoon: +32 (0)2 274 48 00</li>\n        <li>E-mail: <a href=\"mailto:contact@apd-gba.be\">contact@apd-gba.be</a></li>\n      </ul>\n\n      <h2>11. Wijziging van het beleid</h2>\n      <p>Dit beleid kan worden gewijzigd om rekening te houden met:</p>\n      <ul>\n        <li>een evolutie van de website;</li>\n        <li>de toevoeging of het wegvallen van een dienstverlener;</li>\n        <li>een wijziging van de diensten;</li>\n        <li>een evolutie van de regelgeving.</li>\n      </ul>\n      <p>De datum van de laatste update staat boven aan de pagina vermeld.</p>\n\n      <p class=\"legal__back\"><a href=\"index.html\">← Terug naar de homepage</a></p>"
    },
    "cookies": {
      "title": "Cookiebeleid — CoachTanguy",
      "desc": "CoachTanguy gebruikt geen enkele trackingcookie. Overzicht van de functionele lokale opslag en uw opties.",
      "body": "<span class=\"eyebrow\">Cookies &amp; lokale opslag</span>\n      <h1>Cookiebeleid</h1>\n      <p class=\"legal__update\">Laatste update: juni 2026</p>\n\n      <h2>1. Geen trackingcookies</h2>\n      <p>De site <strong>coachtanguy.com</strong> gebruikt <strong>geen enkele cookie voor statistieken, reclame of sociale media</strong>, en geen trackers van derden. Een toestemmingsbanner is dus niet nodig: overeenkomstig de aanbevelingen van de Gegevensbeschermingsautoriteit (GBA) wordt enkel opslag gebruikt die strikt noodzakelijk is voor de werking van de site, en die is vrijgesteld van toestemming.</p>\n\n      <h2>2. Functionele lokale opslag</h2>\n      <p>De site gebruikt de lokale opslag van uw browser (localStorage / sessionStorage / Cache Storage) uitsluitend voor de volgende technische doeleinden:</p>\n      <ul>\n        <li><strong>Cache van de app \"Calculator\"</strong> (Cache Storage, als u de calculator als app installeert): bewaart de bestanden die nodig zijn om offline te werken. Duur: tot u de app verwijdert of de cache wist.</li>\n        <li><strong>SITE_CONTENT_fr / _nl / _en</strong> en <strong>CALC_I18N_fr / _nl / _en</strong> (localStorage): conceptversies van de inhoud, enkel gebruikt in voorbeeldmodus door de beheerder van de site. Ze worden niet gelezen of aangemaakt bij een gewoon bezoek. Duur: tot handmatige verwijdering.</li>\n        <li><strong>dash_ok</strong> (sessionStorage): houdt de sessie van de beheerder op het bewerkingsdashboard actief. Duur: sluiten van het tabblad.</li>\n        <li><strong>cookie_consent</strong> (localStorage): zou uw keuze onthouden indien ooit een toestemmingsbanner wordt geactiveerd. <em>Momenteel niet in gebruik.</em> Maximale duur: 6 maanden.</li>\n      </ul>\n      <p>Deze opslag blijft in uw browser: er wordt geen informatie naar derden gestuurd en u kan er niet mee worden gevolgd.</p>\n\n      <h2>3. Externe diensten</h2>\n      <ul>\n        <li><strong>Lettertypen</strong>: lokaal gehost op de site, geen enkele aanvraag naar Google Fonts.</li>\n        <li><strong>Stripe-betalingen</strong>: de betaalknoppen zijn gewone links naar de beveiligde pagina's van Stripe; de cookies van Stripe gelden enkel op de site van Stripe (zie hun <a href=\"https://stripe.com/nl-be/privacy\" target=\"_blank\" rel=\"noopener\">privacybeleid</a>).</li>\n        <li><strong>WhatsApp</strong>: de WhatsApp-knoppen zijn links; er wordt geen script van Meta op deze site geladen.</li>\n      </ul>\n\n      <h2>4. Hoe deze gegevens verwijderen?</h2>\n      <p>U kan op elk moment de lokale opslag en de cache van uw browser wissen: Instellingen → Privacy → Browsegegevens wissen (of gelijkaardig volgens uw browser). Voor de geïnstalleerde app: verwijder ze gewoon.</p>\n\n      <h2>5. Als er ooit trackers worden toegevoegd</h2>\n      <p>Indien ooit niet-essentiële cookies (statistieken, marketing) zouden worden gebruikt, worden die enkel geplaatst <strong>na uw voorafgaande, vrije en geïnformeerde toestemming</strong>, via een banner waarmee weigeren even eenvoudig is als aanvaarden, zonder vooraf aangevinkte vakjes, en uw keuze wordt maximaal 6 maanden bewaard. Deze pagina zou dan worden bijgewerkt.</p>\n\n      <p class=\"legal__back\"><a href=\"index.html\">← Terug naar de startpagina</a></p>"
    }
  },
  "collab": {
    "title": "Partner-kinesitherapeut in Sint-Genesius-Rode — ZOWE × CoachTanguy",
    "desc": "CoachTanguy werkt samen met ZOWE, de kinesitherapiepraktijk van Zoé Grêde in Sint-Genesius-Rode: zorg en sportcoaching gaan hand in hand.",
    "eyebrow": "Gezondheidspartnerschap",
    "h1": "ZOWE Kine × CoachTanguy",
    "intro": "Om je van herstel tot prestatie te begeleiden, werk ik samen met Zoé Grêde, gediplomeerd kinesitherapeute (Master in de kinesitherapie en revalidatie, ULB) en beoefenaar van de BELTRA-methode. Haar praktijk ZOWE is gevestigd bij Kinovea, Rue des Iris in Sint-Genesius-Rode, midden in mijn coachingzone.",
    "f1h": "Van zorg naar training",
    "f1p": "Blessure, pijn, verminderde mobiliteit? Zoé herstelt de beweging; ik neem het over om kracht en uithouding veilig weer op te bouwen.",
    "f2h": "Precieze expertise",
    "f2p": "Morfostatische diagnose, diep myofasciaal werk, IASTM, vacuümtherapie, mobilisaties: een gerichte aanpak die de oorzaak behandelt, niet alleen de symptomen.",
    "f3h": "Dezelfde regio",
    "f3p": "Praktijk in Sint-Genesius-Rode en huisbezoeken in Linkebeek, Beersel, Lot, Eigenbrakel en Waterloo, precies waar ik coach.",
    "cardEyebrow": "ZOWE, Kinesitherapie",
    "cardTitle": "Nood aan kine-advies?",
    "cardText": "Lage rugpijn, nekpijn, tendinitis, chronische pijn of terugkeer naar sport na een blessure: ontdek de aanpak van Zoé, \"L'art de la justesse, l'expertise du soin\".",
    "chip1": "✓ BELTRA-methode",
    "chip2": "✓ Praktijk Kinovea · Sint-Genesius-Rode",
    "chip3": "✓ FR · NL · EN",
    "button": "Bezoek zowekine.com",
    "aboutEyebrow": "Wie ben ik?",
    "aboutTitle": "Zoé Grêde, BELTRA-kinesitherapeute",
    "aboutP1": "Ik heb Zowe ontworpen met een duidelijke visie: de kinesitherapiesessie omvormen tot een ervaring van hoge precisie.",
    "aboutP2": "Mijn aanpak stopt niet bij het verdwijnen van de pijn, maar mikt op de duurzame optimalisatie van uw fysieke kapitaal.",
    "tick1": "Université Libre de Bruxelles",
    "tick2": "Master in de kinesitherapie en revalidatie",
    "tick3": "Ook conventionele kinesitherapie, via Kinovea",
    "aboutP3": "Om dat niveau van precisie te bereiken, heb ik mij specifiek gevormd in de Beltra-methode. Die expertise laat mij toe geavanceerde zorgprotocollen in mijn praktijk te integreren, gericht op technische controle en een diepe herharmonisatie van het lichaam.",
    "aboutP4": "Omdat elke patiënt uniek is, stel ik mijn vakkennis en deze specialisatie ten dienste van een begeleiding op maat, waar wetenschappelijke nauwkeurigheid het comfort van een exclusieve aanpak ontmoet."
  }
};
(window.SITE_CONTENT_ALL = window.SITE_CONTENT_ALL || {}).nl = window.SITE_CONTENT;
