/* ===========================================================
   INHOUD NEDERLANDS — CoachTanguy (bewerkt via dashboard.html)
   =========================================================== */
window.SITE_CONTENT = {
  "nav": {
    "accueil": "Home",
    "visio": "Videocoaching",
    "suivi": "Online opvolging",
    "calculateur": "Calculator",
    "faq": "FAQ",
    "contact": "Contact",
    "cta": "Plan een gesprek"
  },
  "calc": {
    "eyebrow": "Gratis tool",
    "title": "Voedingscalculator",
    "subtitle": "Schat je caloriebehoefte en macroverdeling in enkele seconden, op basis van je profiel en doelen."
  },
  "home": {
    "hero": {
      "eyebrow": "Gediplomeerd sportcoach",
      "titleHtml": "Sporten wordt makkelijk,<br />overal en altijd.",
      "subtitle": "Videocoaching en online opvolging, afgestemd op jouw niveau, je doelen en je agenda.",
      "ctaPrimary": "Ontdek de formules",
      "ctaSecondary": "Gratis proefsessie",
      "pill1": "✓ Videocoaching",
      "pill2": "✓ Online opvolging",
      "pill3": "✓ Zonder verbintenis"
    },
    "trust": {
      "v1": "500+",
      "l1": "uren opleiding",
      "v2": "100%",
      "l2": "op maat",
      "v3": "7/7",
      "l3": "begeleiding",
      "v4": "1e",
      "l4": "sessie gratis"
    },
    "services": {
      "eyebrow": "Diensten",
      "title": "Begeleiding op jouw tempo",
      "subtitle": "Twee formules om je vooruit te helpen, waar je ook bent.",
      "c1Title": "Videocoaching",
      "c1Text": "Geniet van professionele begeleiding op afstand via videogesprek, om overal gemotiveerd te blijven.",
      "c1Link": "Ontdek de formule →",
      "c2Title": "Online opvolging",
      "c2Text": "Krijg persoonlijke opvolging, trainingsschema's en advies via een app.",
      "c2Link": "Ontdek de formule →"
    },
    "process": {
      "eyebrow": "Hoe het werkt",
      "title": "Of het nu met videocoaching of online opvolging is: vorder in 3 eenvoudige stappen",
      "s1Title": "Kennismakingsgesprek",
      "s1Text": "Een eerste gratis gesprek om je behoeften en doelen te begrijpen en samen de methode te testen.",
      "s2Title": "Schema op maat",
      "s2Text": "Ik stel een programma op, afgestemd op jouw niveau, je agenda en je materiaal.",
      "s3Title": "Opvolging & resultaten",
      "s3Text": "We gaan samen vooruit: sessies, regelmatige bijsturing en motivatie voor blijvende resultaten."
    },
    "about": {
      "eyebrow": "Over mij",
      "title": "Tanguy, jouw sportcoach",
      "p1": "Afgestudeerd met een Bachelier en Coaching Sportif steun ik op een stevige kennis van anatomie, fysiologie, voeding en trainingswetenschap om je in alle veiligheid te begeleiden.",
      "p2": "Ik werkte met uiteenlopende profielen, van kinderen tot senioren, en pas elk programma aan jouw behoeften aan. Mijn parcours: meer dan 500 stage-uren, 2 jaar ervaring als personal coach en meer dan 10 jaar eigen krachttraining.",
      "s1v": "500+",
      "s1l": "stage-uren",
      "s2v": "2 jaar",
      "s2l": "coaching",
      "s3v": "10+ jaar",
      "s3l": "praktijk",
      "cta": "Werk met mij"
    },
    "faq": {
      "eyebrow": "FAQ",
      "title": "Veelgestelde vragen",
      "q1": "Waarom sessiepakketten aanbieden?",
      "a1": "Pakketten vereenvoudigen de betaling en stimuleren engagement. Regelmaat is de sleutel tot resultaat: je inzetten voor meerdere sessies helpt je consistent te blijven en duurzaam vooruit te gaan.",
      "q2": "Hoe boek ik een sessie?",
      "a2": "Om de twee weken wordt een agendalink gedeeld via WhatsApp. Je kiest de momenten die het best bij je passen.",
      "q3": "Kan ik een sessie annuleren of verplaatsen?",
      "a3": "Ja, je kan een sessie annuleren of verplaatsen zolang je pakket geldig is. Eens het pakket verlopen is, gaan ongebruikte sessies verloren.",
      "q4": "Hoe lang is een pakket geldig?",
      "a4": "Pakketten van 4 sessies zijn 5 weken geldig, pakketten van 8 sessies 10 weken, vanaf de aankoopdatum.",
      "q5": "Welke betaalmethodes worden aanvaard?",
      "a5": "Visa, Mastercard, PayPal, Klarna, Apple Pay, Google Pay en andere betaalmethodes worden veilig aanvaard via Stripe.",
      "q6": "En als ik op vakantie ga?",
      "a6": "Geen zorgen: je pakket wordt gepauzeerd tijdens je afwezigheid en hervat bij je terugkeer.",
      "q7": "Kan ik in schijven betalen?",
      "a7": "Ja, gespreid betalen kan via Klarna."
    },
    "cta": {
      "title": "Klaar om te starten?",
      "text": "Neem contact op om je doelen te bespreken en de juiste formule te vinden. De eerste sessie is gratis.",
      "button": "Contacteer mij"
    },
    "payments": {
      "title": "Beveiligde betaling via Stripe"
    }
  },
  "footer": {
    "tagline": "Sporten wordt makkelijk, overal en altijd.",
    "areas": "Sportcoach in Sint-Genesius-Rode, Ukkel, Waterloo, Beersel, Linkebeek en Eigenbrakel — aan huis of via video.",
    "lVisio": "Videocoaching",
    "lSuivi": "Online opvolging",
    "lFaq": "FAQ",
    "lContact": "Contact",
    "lMentions": "Juridische info",
    "lCgv": "Voorwaarden",
    "copyright": "© 2026 CoachTanguy. Alle rechten voorbehouden."
  },
  "contact": {
    "eyebrow": "Contact",
    "title": "Contacteer Tanguy",
    "subtitle": "Een vraag? Klaar om te starten? Stuur me een bericht, ik antwoord snel.",
    "asideTitle": "Een vraag?",
    "asideText": "Het eenvoudigst en snelst: een direct bericht via WhatsApp.",
    "waLabel": "WhatsApp",
    "waSub": "+32 472 76 16 39",
    "emailLabel": "E-mail",
    "emailSub": "tanguy_coaching@hotmail.com",
    "note": "✓ Eerste proefsessie gratis",
    "formTitle": "Snel bericht",
    "fName": "Naam",
    "phName": "Je naam",
    "fEmail": "E-mail",
    "phEmail": "jij@email.com",
    "fSubject": "Onderwerp",
    "optVisio": "Videocoaching",
    "optSuivi": "Online opvolging",
    "optEssai": "Gratis proefsessie",
    "optAutre": "Andere vraag",
    "fMessage": "Bericht",
    "phMessage": "Vertel me over je doelen...",
    "submit": "Bericht versturen",
    "consent": "Door dit formulier te versturen, ga je akkoord dat CoachTanguy contact met je opneemt."
  },
  "visio": {
    "heroEyebrow": "Videocoaching",
    "heroTitleHtml": "Flexibel, interactief,<br />efficiënt.",
    "heroSubtitle": "Geniet van individuele sportcoachingsessies op afstand, overal toegankelijk. Persoonlijke coaching, advies in realtime en opvolging op maat via videogesprek.",
    "heroCta1": "Direct naar de pakketten",
    "heroCta2": "Gratis proefsessie",
    "f1Title": "Coaching op maat",
    "f1Text": "Sessies afgestemd op jouw tempo, je doelen en je ruimte, waar je ook bent.",
    "f2Title": "Sessiepakketten",
    "f2Text": "Pakketten afgestemd op je trainingsfrequentie voor échte regelmaat.",
    "f3Title": "Gratis proefsessie",
    "f3Text": "Een eerste gesprek om je behoeften te ontdekken, de methode te testen en samen je doelen te bepalen.",
    "packsEyebrow": "Pakketten",
    "packsTitle": "Kies de formule die bij je past",
    "packsSubtitle": "Aangepast en persoonlijk · feedback na elke sessie · uitstel mogelijk bij vakantie.",
    "p1Name": "Losse sessie",
    "p1Meta": "Sessie van 30 tot 40 min",
    "p1l1": "Aangepaste en persoonlijke sessie",
    "p1l2": "Feedback na de sessie",
    "p1l3": "Zonder verbintenis",
    "p1Note": "💳 Betaling bij de reservering",
    "p1Btn": "Reserveren",
    "p2Ribbon": "Meest gekozen",
    "p2Name": "Pakket 4 sessies",
    "p2PriceSub": "ofwel 35€ / sessie",
    "p2Meta": "Geldig 5 weken",
    "p2l1": "4 persoonlijke sessies",
    "p2l2": "Feedback na elke sessie",
    "p2l3": "Uitstel mogelijk bij vakantie",
    "p2l4": "Ideaal 1 sessie / week",
    "p2Btn": "Kiezen",
    "p3Name": "Pakket 8 sessies",
    "p3PriceSub": "ofwel 30€ / sessie",
    "p3Meta": "Geldig 10 weken",
    "p3l1": "8 persoonlijke sessies",
    "p3l2": "Feedback na elke sessie",
    "p3l3": "Uitstel mogelijk bij vakantie",
    "p3l4": "Beste tarief / sessie",
    "p3Btn": "Kiezen",
    "ctaTitle": "Klaar om te starten?",
    "ctaText": "Reserveer je gratis proefsessie en we beginnen samen.",
    "ctaBtn": "Contacteren"
  },
  "suivi": {
    "heroEyebrow": "Online Opvolging",
    "heroTitleHtml": "Sportcoaching<br />op afstand.",
    "heroSubtitle": "Opvolging op jouw tempo, 100% persoonlijk, waar je ook bent via de FitPros-app. Evoluerend programma, regelmatig advies en begeleiding op maat om efficiënt vooruit te gaan.",
    "heroCta1": "Direct naar de formules",
    "heroCta2": "Een vraag stellen",
    "appEyebrow": "FitPros",
    "appTitle": "Jouw programma op maat in je broekzak.",
    "appText": "Een eenvoudige ruimte om je vooruitgang te volgen en gemotiveerd te blijven.",
    "appB1Title": "Een eenvoudige ruimte om je vooruitgang te volgen.",
    "appB1Text": "In de app vind je makkelijk je lopende trainingen, je vooruitgang van de week en je volgende geplande sessies terug. Alles staat gecentraliseerd zodat je een helder overzicht houdt en regelmatig blijft trainen.",
    "appB2Title": "Stap-voor-stap begeleide sessies.",
    "appB2Text": "Elke sessie is helder opgebouwd met de oefeningen, de reeksen, de herhalingen, de bijhorende richtlijnen en uitvoeringsvideo's. Je start je training rechtstreeks vanuit de app en volgt het programma op jouw tempo, volledig zelfstandig.",
    "appT1": "Stap-voor-stap begeleide sessies",
    "appT2": "Duidelijke opvolging van je vooruitgang",
    "appT3": "Regelmatig advies en bijsturing",
    "appT4": "Rechtstreekse communicatie via WhatsApp",
    "appBtn": "Bekijk de formules",
    "suivisEyebrow": "Formules",
    "suivisTitle": "Deskundige opvolging, 100% persoonlijk",
    "suivisSubtitle": "Programma op maat, regelmatige bijsturing en menselijke begeleiding.",
    "flowLabel": "daarna",
    "s1Ribbon": "Om te starten",
    "s1Name": "Initiële begeleiding",
    "s1PriceSub": "voor 8 weken",
    "s1l1": "Persoonlijke begeleiding gedurende 8 weken",
    "s1l2": "Trainingsprogramma op maat afgestemd op je doelen",
    "s1l3": "Toegang via de FitPros-app",
    "s1l4": "Communicatie & opvolging via WhatsApp",
    "s1l5": "Introductiegesprek via video (~30 min) gratis",
    "s1l6": "Programma beschikbaar binnen 72u na het gesprek",
    "s1l7": "Check-up om de 2 weken via een formulier",
    "s1l8": "Regelmatige bijsturing voor optimale resultaten",
    "s1l9": "Pauze mogelijk bij vakantie",
    "s1Btn": "Kiezen",
    "s2Name": "Maandelijkse opvolging",
    "s2PriceSub": "per maand",
    "s2Meta": "Enkel na de initiële begeleiding",
    "s2l1": "Trainingsprogramma op maat",
    "s2l2": "Toegang via de FitPros-app",
    "s2l3": "Communicatie & opvolging via WhatsApp",
    "s2l4": "Check-up om de 2 weken",
    "s2l5": "Regelmatige bijsturing",
    "s2l6": "Pauze mogelijk bij vakantie",
    "s2Btn": "Kiezen",
    "ctaTitle": "Klaar om vooruit te gaan?",
    "ctaText": "Reserveer je gratis introductiegesprek en we bouwen je programma.",
    "ctaBtn": "Contacteren"
  },
  "stripe": {
    "unite": "contact.html",
    "pack4": "https://buy.stripe.com/5kQ4gBdvB0Yz85A7Pa0RG0a",
    "pack8": "https://buy.stripe.com/8x2cN7fDJePpadI8Te0RG0b",
    "initial": "https://buy.stripe.com/8x214p8bh22D0D84CY0RG08",
    "mensuel": "https://buy.stripe.com/dRm8wR63922DdpUfhC0RG09"
  },
  "meta": {
    "index": {
      "title": "Sportcoach in Sint-Genesius-Rode & Brabant — CoachTanguy",
      "desc": "Sportcoach in Sint-Genesius-Rode: coaching aan huis, via video en online opvolging. Ook in Waterloo, Beersel, Linkebeek en Eigenbrakel. 1e sessie gratis."
    },
    "visio": {
      "title": "Videocoaching — CoachTanguy",
      "desc": "Individuele sportcoaching op afstand via videogesprek. Flexibel, interactief en doeltreffend. Eerste proefsessie gratis."
    },
    "suivi": {
      "title": "Online opvolging — CoachTanguy",
      "desc": "100% gepersonaliseerde sportopvolging via de FitPros-app: evoluerend programma, regelmatig advies en begeleiding op maat om efficiënt vooruit te gaan."
    },
    "contact": {
      "title": "Contact — CoachTanguy",
      "desc": "Een vraag? Neem contact op met CoachTanguy via WhatsApp of bericht. Eerste proefsessie gratis."
    },
    "calc": {
      "title": "Voedingscalculator — CoachTanguy",
      "desc": "Gratis voedingscalculator: bereken je caloriebehoefte en de verdeling van je macro's (eiwitten, koolhydraten, vetten) volgens je profiel en doelen."
    }
  },
  "local": {
    "rhode": {
      "metaTitle": "Sportcoach in Sint-Genesius-Rode | aan huis & video — CoachTanguy",
      "metaDesc": "Sportcoach in Sint-Genesius-Rode: sessies aan huis of via video, programma en voeding op maat. Gediplomeerd coach, 1e proefsessie gratis.",
      "heroEyebrow": "Sportcoaching · Sint-Genesius-Rode",
      "h1": "Sportcoach in Sint-Genesius-Rode",
      "heroLead": "Gevestigd in Sint-Genesius-Rode bied ik persoonlijke sportcoaching aan, rechtstreeks bij je thuis of via videogesprek. Van het centrum tot de wijken bij het Zoniënwoud pas ik me aan jouw niveau, je doelen en je agenda aan — beginner of gevorderd.",
      "btnEssai": "Gratis proefsessie",
      "btnVisio": "Bekijk videocoaching",
      "secEyebrow": "In Sint-Genesius-Rode en omgeving",
      "h2": "Je sportcoach aan huis en via video in Sint-Genesius-Rode",
      "secIntro": "Geen sportzaal of lange verplaatsingen nodig: ik kom bij je thuis, of we werken via video met een programma tussen de sessies. Ideaal als je weinig tijd hebt of een privé en persoonlijke aanpak verkiest.",
      "f1h": "Aan huis in Sint-Genesius-Rode",
      "f1p": "Ik kom bij je langs in Sint-Genesius-Rode met het nodige materiaal. Je traint in een vertrouwde omgeving, op het uur dat jou uitkomt.",
      "f2h": "Coaching via video",
      "f2p": "Vanuit Sint-Genesius-Rode of onderweg volg je je sessies via videogesprek, met een bijgewerkt programma en correcties in realtime.",
      "f3h": "Programma & voeding op maat",
      "f3p": "Een plan afgestemd op je niveau en je doelen, met eenvoudige en concrete voedingsrichtlijnen — zonder extreem dieet.",
      "ctaH2": "Klaar om (opnieuw) te sporten in Sint-Genesius-Rode?",
      "ctaP": "Eerste proefsessie gratis, zonder verbintenis. Aan huis of via video, we starten wanneer je wil.",
      "btnContact": "Contacteer mij"
    },
    "uccle": {
      "metaTitle": "Sportcoach in Ukkel | aan huis & video — CoachTanguy",
      "metaDesc": "Sportcoach in Ukkel: sessies aan huis of via video, programma en voeding op maat. Gediplomeerd coach, 1e proefsessie gratis.",
      "heroEyebrow": "Sportcoaching · Ukkel",
      "h1": "Sportcoach in Ukkel",
      "heroLead": "Net ten noorden van Sint-Genesius-Rode begeleid ik de inwoners van Ukkel met persoonlijke sportcoaching, aan huis of via videogesprek. Van Fort-Jaco tot Diesdelle pas ik me aan jouw niveau, je doelen en je agenda aan.",
      "btnEssai": "Gratis proefsessie",
      "btnVisio": "Bekijk videocoaching",
      "secEyebrow": "In Ukkel en omgeving",
      "h2": "Je sportcoach aan huis en via video in Ukkel",
      "secIntro": "Geen drukke sportzaal nodig: ik kom bij je thuis, of we werken via video met een programma tussen de sessies. Handig voor drukke agenda's en de residentiële wijken van Ukkel.",
      "f1h": "Aan huis in Ukkel",
      "f1p": "Ik kom bij je langs in Ukkel met het nodige materiaal. Je traint in een vertrouwde omgeving, op het uur dat jou uitkomt.",
      "f2h": "Coaching via video",
      "f2p": "Vanuit Ukkel of onderweg volg je je sessies via videogesprek, met een bijgewerkt programma en correcties in realtime.",
      "f3h": "Programma & voeding op maat",
      "f3p": "Een plan afgestemd op je niveau en je doelen, met eenvoudige en concrete voedingsrichtlijnen — zonder extreem dieet.",
      "ctaH2": "Klaar om (opnieuw) te sporten in Ukkel?",
      "ctaP": "Eerste proefsessie gratis, zonder verbintenis. Aan huis of via video, we starten wanneer je wil.",
      "btnContact": "Contacteer mij"
    },
    "waterloo": {
      "metaTitle": "Sportcoach in Waterloo | aan huis & video — CoachTanguy",
      "metaDesc": "Sportcoach in Waterloo: persoonlijke coaching aan huis of via video — gewichtsverlies, fit worden, spieropbouw. 1e proefsessie gratis.",
      "heroEyebrow": "Sportcoaching · Waterloo",
      "h1": "Sportcoach in Waterloo",
      "heroLead": "Op enkele minuten van Sint-Genesius-Rode begeleid ik de inwoners van Waterloo met persoonlijke sportcoaching, aan huis of via video. Gewichtsverlies, fit worden, spieropbouw of fysieke voorbereiding: we bouwen samen een realistisch en progressief programma.",
      "btnEssai": "Gratis proefsessie",
      "btnVisio": "Bekijk videocoaching",
      "secEyebrow": "In Waterloo en omgeving",
      "h2": "Sportcoaching op maat in Waterloo",
      "secIntro": "Of je nu beginner of regelmatige sporter bent, elke sessie is aangepast aan je vorm van de dag. Tussen de afspraken houd je een duidelijk programma en advies om dagelijks vooruit te gaan, op jouw tempo.",
      "f1h": "Aan huis in Waterloo",
      "f1p": "Ik kom bij je langs in Waterloo met het nodige materiaal. Je traint in een vertrouwde omgeving, op het uur dat jou uitkomt.",
      "f2h": "Coaching via video",
      "f2p": "Vanuit Waterloo of onderweg volg je je sessies via videogesprek, met een bijgewerkt programma en correcties in realtime.",
      "f3h": "Programma & voeding op maat",
      "f3p": "Een plan afgestemd op je niveau en je doelen, met eenvoudige en concrete voedingsrichtlijnen — zonder extreem dieet.",
      "ctaH2": "Klaar om (opnieuw) te sporten in Waterloo?",
      "ctaP": "Eerste proefsessie gratis, zonder verbintenis. Aan huis of via video, we starten wanneer je wil.",
      "btnContact": "Contacteer mij"
    },
    "beersel": {
      "metaTitle": "Sportcoach in Beersel | aan huis & video — CoachTanguy",
      "metaDesc": "Sportcoach in Beersel (Alsemberg, Huizingen, Lot): sessies aan huis of via video, programma en voeding op maat. 1e proefsessie gratis.",
      "heroEyebrow": "Sportcoaching · Beersel",
      "h1": "Sportcoach in Beersel",
      "heroLead": "Persoonlijke sportcoaching in Beersel en zijn dorpen (Alsemberg, Huizingen, Lot), aan huis of via videogesprek. Een professionele en progressieve begeleiding om je doelen te bereiken, zonder de drempel van de sportzaal.",
      "btnEssai": "Gratis proefsessie",
      "btnVisio": "Bekijk videocoaching",
      "secEyebrow": "In Beersel en omgeving",
      "h2": "Begeleide sport, dicht bij huis in Beersel",
      "secIntro": "Coaching aan huis bespaart je tijd en houdt de motivatie hoog. Video laat je het ritme aanhouden, ook in drukke weken of onderweg — het is de regelmaat die resultaten oplevert.",
      "f1h": "Aan huis in Beersel",
      "f1p": "Ik kom bij je langs in Beersel met het nodige materiaal. Je traint in een vertrouwde omgeving, op het uur dat jou uitkomt.",
      "f2h": "Coaching via video",
      "f2p": "Vanuit Beersel of onderweg volg je je sessies via videogesprek, met een bijgewerkt programma en correcties in realtime.",
      "f3h": "Programma & voeding op maat",
      "f3p": "Een plan afgestemd op je niveau en je doelen, met eenvoudige en concrete voedingsrichtlijnen — zonder extreem dieet.",
      "ctaH2": "Klaar om (opnieuw) te sporten in Beersel?",
      "ctaP": "Eerste proefsessie gratis, zonder verbintenis. Aan huis of via video, we starten wanneer je wil.",
      "btnContact": "Contacteer mij"
    },
    "linkebeek": {
      "metaTitle": "Sportcoach in Linkebeek & Holleken | aan huis & video — CoachTanguy",
      "metaDesc": "Sportcoach in Linkebeek en Holleken: coaching aan huis of via video, programma op maat, voedingsadvies. Gediplomeerd coach, 1e proefsessie gratis.",
      "heroEyebrow": "Sportcoaching · Linkebeek",
      "h1": "Sportcoach in Linkebeek",
      "heroLead": "Sportcoach voor de inwoners van Linkebeek en Holleken, vlak naast Sint-Genesius-Rode. Sessies aan huis of via video, programma op maat, voedingsadvies en regelmatige opvolging voor blijvende resultaten.",
      "btnEssai": "Gratis proefsessie",
      "btnVisio": "Bekijk videocoaching",
      "secEyebrow": "In Linkebeek en omgeving",
      "h2": "Coaching dichtbij in Linkebeek",
      "secIntro": "Dankzij de nabijheid van Sint-Genesius-Rode zijn sessies aan huis makkelijk te plannen. Video blijft beschikbaar om de regelmaat nooit te breken, dé sleutel tot vooruitgang op lange termijn.",
      "f1h": "Aan huis in Linkebeek",
      "f1p": "Ik kom bij je langs in Linkebeek met het nodige materiaal. Je traint in een vertrouwde omgeving, op het uur dat jou uitkomt.",
      "f2h": "Coaching via video",
      "f2p": "Vanuit Linkebeek of onderweg volg je je sessies via videogesprek, met een bijgewerkt programma en correcties in realtime.",
      "f3h": "Programma & voeding op maat",
      "f3p": "Een plan afgestemd op je niveau en je doelen, met eenvoudige en concrete voedingsrichtlijnen — zonder extreem dieet.",
      "ctaH2": "Klaar om (opnieuw) te sporten in Linkebeek?",
      "ctaP": "Eerste proefsessie gratis, zonder verbintenis. Aan huis of via video, we starten wanneer je wil.",
      "btnContact": "Contacteer mij"
    },
    "braine": {
      "metaTitle": "Sportcoach in Eigenbrakel | aan huis & video — CoachTanguy",
      "metaDesc": "Sportcoach in Eigenbrakel: sessies aan huis of via video, begeleid door een gediplomeerd coach. Fit worden, fysieke voorbereiding. 1e proefsessie gratis.",
      "heroEyebrow": "Sportcoaching · Eigenbrakel",
      "h1": "Sportcoach in Eigenbrakel",
      "heroLead": "Sportcoaching in Eigenbrakel: sessies begeleid door een gediplomeerd coach, aan huis of via videogesprek. Van eenvoudige conditieopbouw tot fysieke voorbereiding, ik begeleid je stap voor stap, in alle veiligheid.",
      "btnEssai": "Gratis proefsessie",
      "btnVisio": "Bekijk videocoaching",
      "secEyebrow": "In Eigenbrakel en omgeving",
      "h2": "Begin rustig (opnieuw) met sporten in Eigenbrakel",
      "secIntro": "We gaan stap voor stap vooruit, met realistische doelen en regelmatige opvolging. Het idee is niet om alles in één keer om te gooien, maar om gewoonten te installeren die blijven duren.",
      "f1h": "Aan huis in Eigenbrakel",
      "f1p": "Ik kom bij je langs in Eigenbrakel met het nodige materiaal. Je traint in een vertrouwde omgeving, op het uur dat jou uitkomt.",
      "f2h": "Coaching via video",
      "f2p": "Vanuit Eigenbrakel of onderweg volg je je sessies via videogesprek, met een bijgewerkt programma en correcties in realtime.",
      "f3h": "Programma & voeding op maat",
      "f3p": "Een plan afgestemd op je niveau en je doelen, met eenvoudige en concrete voedingsrichtlijnen — zonder extreem dieet.",
      "ctaH2": "Klaar om (opnieuw) te sporten in Eigenbrakel?",
      "ctaP": "Eerste proefsessie gratis, zonder verbintenis. Aan huis of via video, we starten wanneer je wil.",
      "btnContact": "Contacteer mij"
    }
  }
};
(window.SITE_CONTENT_ALL = window.SITE_CONTENT_ALL || {}).nl = window.SITE_CONTENT;
